"""Best Practice SNS Topic

Generated by cfn-dataclasses-import."""

from cloudformation_dataclasses.core import (
    Output,
    Parameter,
    STRING,
    Template,
    cloudformation_dataclass,
    get_att,
    ref,
)
from cloudformation_dataclasses.aws import sns

from .stack import *  # noqa: F403, F401

__all__ = [
    "Output",
    "Parameter",
    "QueueNameOutput",
    "SNSSubscription",
    "SNSTopic",
    "STRING",
    "SubscriptionEndPoint",
    "SubscriptionProtocol",
    "Template",
    "TopicARNOutput",
    "cloudformation_dataclass",
    "get_att",
    "ref",
    "sns",
]
