"""Auto-generated stub for IDE type checking."""

from cloudformation_dataclasses.core import (
    ARN_LIKE,
    BOOL,
    DenyStatement,
    Output,
    Parameter,
    PolicyDocument,
    PolicyStatement,
    STRING,
    STRING_EQUALS,
    Template,
    cloudformation_dataclass,
    get_att,
    ref,
)
from cloudformation_dataclasses.core.resource_loader import setup_resources
from cloudformation_dataclasses.aws import cloudfront, iam, s3
from cloudformation_dataclasses.aws.s3 import (
    ObjectLockEnabled,
    ObjectLockRetentionMode,
    ReplicationRuleStatus,
    ServerSideEncryption,
)
from cloudformation_dataclasses.intrinsics import (
    AWS_ACCOUNT_ID,
    AWS_STACK_ID,
    Join,
    Select,
    Split,
    Sub,
)
from .params import *  # noqa: F403, F401
from .outputs import *  # noqa: F403, F401

from .network import Distribution as Distribution
from .network import DistributionDefaultCacheBehavior as DistributionDefaultCacheBehavior
from .network import DistributionDistributionConfig as DistributionDistributionConfig
from .network import DistributionLogging as DistributionLogging
from .network import DistributionOrigin as DistributionOrigin
from .network import DistributionS3OriginConfig as DistributionS3OriginConfig
from .network import DistributionViewerCertificate as DistributionViewerCertificate
from .network import OriginAccessControl as OriginAccessControl
from .network import OriginAccessControlOriginAccessControlConfig as OriginAccessControlOriginAccessControlConfig
from .outputs import SiteURLOutput as SiteURLOutput
from .params import AppName as AppName
from .params import WebACL as WebACL
from .security import CloudFrontLogsReplicationPolicy as CloudFrontLogsReplicationPolicy
from .security import CloudFrontLogsReplicationPolicyAllowStatement0 as CloudFrontLogsReplicationPolicyAllowStatement0
from .security import CloudFrontLogsReplicationPolicyAllowStatement1 as CloudFrontLogsReplicationPolicyAllowStatement1
from .security import CloudFrontLogsReplicationPolicyAllowStatement2 as CloudFrontLogsReplicationPolicyAllowStatement2
from .security import CloudFrontLogsReplicationPolicyPolicyDocument as CloudFrontLogsReplicationPolicyPolicyDocument
from .security import CloudFrontLogsReplicationRole as CloudFrontLogsReplicationRole
from .security import CloudFrontLogsReplicationRoleAllowStatement0 as CloudFrontLogsReplicationRoleAllowStatement0
from .security import CloudFrontLogsReplicationRoleAssumeRolePolicyDocument as CloudFrontLogsReplicationRoleAssumeRolePolicyDocument
from .security import ContentReplicationPolicy as ContentReplicationPolicy
from .security import ContentReplicationPolicyAllowStatement0 as ContentReplicationPolicyAllowStatement0
from .security import ContentReplicationPolicyAllowStatement1 as ContentReplicationPolicyAllowStatement1
from .security import ContentReplicationPolicyAllowStatement2 as ContentReplicationPolicyAllowStatement2
from .security import ContentReplicationPolicyPolicyDocument as ContentReplicationPolicyPolicyDocument
from .security import ContentReplicationRole as ContentReplicationRole
from .security import ContentReplicationRoleAllowStatement0 as ContentReplicationRoleAllowStatement0
from .security import ContentReplicationRoleAssumeRolePolicyDocument as ContentReplicationRoleAssumeRolePolicyDocument
from .storage import CloudFrontLogsBucket as CloudFrontLogsBucket
from .storage import CloudFrontLogsBucketBucketEncryption as CloudFrontLogsBucketBucketEncryption
from .storage import CloudFrontLogsBucketDeleteMarkerReplication as CloudFrontLogsBucketDeleteMarkerReplication
from .storage import CloudFrontLogsBucketLoggingConfiguration as CloudFrontLogsBucketLoggingConfiguration
from .storage import CloudFrontLogsBucketPolicyPolicy as CloudFrontLogsBucketPolicyPolicy
from .storage import CloudFrontLogsBucketPolicyPolicyAllowStatement1 as CloudFrontLogsBucketPolicyPolicyAllowStatement1
from .storage import CloudFrontLogsBucketPolicyPolicyDenyStatement0 as CloudFrontLogsBucketPolicyPolicyDenyStatement0
from .storage import CloudFrontLogsBucketPolicyPolicyPolicyDocument as CloudFrontLogsBucketPolicyPolicyPolicyDocument
from .storage import CloudFrontLogsBucketPublicAccessBlockConfiguration as CloudFrontLogsBucketPublicAccessBlockConfiguration
from .storage import CloudFrontLogsBucketReplicationConfiguration as CloudFrontLogsBucketReplicationConfiguration
from .storage import CloudFrontLogsBucketReplicationDestination as CloudFrontLogsBucketReplicationDestination
from .storage import CloudFrontLogsBucketReplicationRule as CloudFrontLogsBucketReplicationRule
from .storage import CloudFrontLogsBucketServerSideEncryptionByDefault as CloudFrontLogsBucketServerSideEncryptionByDefault
from .storage import CloudFrontLogsBucketServerSideEncryptionRule as CloudFrontLogsBucketServerSideEncryptionRule
from .storage import CloudFrontLogsLogBucket as CloudFrontLogsLogBucket
from .storage import CloudFrontLogsLogBucketBucketEncryption as CloudFrontLogsLogBucketBucketEncryption
from .storage import CloudFrontLogsLogBucketDefaultRetention as CloudFrontLogsLogBucketDefaultRetention
from .storage import CloudFrontLogsLogBucketDeleteMarkerReplication as CloudFrontLogsLogBucketDeleteMarkerReplication
from .storage import CloudFrontLogsLogBucketObjectLockConfiguration as CloudFrontLogsLogBucketObjectLockConfiguration
from .storage import CloudFrontLogsLogBucketObjectLockRule as CloudFrontLogsLogBucketObjectLockRule
from .storage import CloudFrontLogsLogBucketPolicyPolicy as CloudFrontLogsLogBucketPolicyPolicy
from .storage import CloudFrontLogsLogBucketPolicyPolicyAllowStatement1 as CloudFrontLogsLogBucketPolicyPolicyAllowStatement1
from .storage import CloudFrontLogsLogBucketPolicyPolicyDenyStatement0 as CloudFrontLogsLogBucketPolicyPolicyDenyStatement0
from .storage import CloudFrontLogsLogBucketPolicyPolicyPolicyDocument as CloudFrontLogsLogBucketPolicyPolicyPolicyDocument
from .storage import CloudFrontLogsLogBucketPublicAccessBlockConfiguration as CloudFrontLogsLogBucketPublicAccessBlockConfiguration
from .storage import CloudFrontLogsLogBucketServerSideEncryptionByDefault as CloudFrontLogsLogBucketServerSideEncryptionByDefault
from .storage import CloudFrontLogsLogBucketServerSideEncryptionRule as CloudFrontLogsLogBucketServerSideEncryptionRule
from .storage import CloudFrontLogsReplicaBucket as CloudFrontLogsReplicaBucket
from .storage import CloudFrontLogsReplicaBucketBucketEncryption as CloudFrontLogsReplicaBucketBucketEncryption
from .storage import CloudFrontLogsReplicaBucketDeleteMarkerReplication as CloudFrontLogsReplicaBucketDeleteMarkerReplication
from .storage import CloudFrontLogsReplicaBucketPolicyPolicy as CloudFrontLogsReplicaBucketPolicyPolicy
from .storage import CloudFrontLogsReplicaBucketPolicyPolicyAllowStatement1 as CloudFrontLogsReplicaBucketPolicyPolicyAllowStatement1
from .storage import CloudFrontLogsReplicaBucketPolicyPolicyDenyStatement0 as CloudFrontLogsReplicaBucketPolicyPolicyDenyStatement0
from .storage import CloudFrontLogsReplicaBucketPolicyPolicyPolicyDocument as CloudFrontLogsReplicaBucketPolicyPolicyPolicyDocument
from .storage import CloudFrontLogsReplicaBucketPublicAccessBlockConfiguration as CloudFrontLogsReplicaBucketPublicAccessBlockConfiguration
from .storage import CloudFrontLogsReplicaBucketServerSideEncryptionByDefault as CloudFrontLogsReplicaBucketServerSideEncryptionByDefault
from .storage import CloudFrontLogsReplicaBucketServerSideEncryptionRule as CloudFrontLogsReplicaBucketServerSideEncryptionRule
from .storage import ContentBucket as ContentBucket
from .storage import ContentBucketBucketEncryption as ContentBucketBucketEncryption
from .storage import ContentBucketDeleteMarkerReplication as ContentBucketDeleteMarkerReplication
from .storage import ContentBucketLoggingConfiguration as ContentBucketLoggingConfiguration
from .storage import ContentBucketPolicyPolicy as ContentBucketPolicyPolicy
from .storage import ContentBucketPolicyPolicyAllowStatement1 as ContentBucketPolicyPolicyAllowStatement1
from .storage import ContentBucketPolicyPolicyDenyStatement0 as ContentBucketPolicyPolicyDenyStatement0
from .storage import ContentBucketPolicyPolicyPolicyDocument as ContentBucketPolicyPolicyPolicyDocument
from .storage import ContentBucketPublicAccessBlockConfiguration as ContentBucketPublicAccessBlockConfiguration
from .storage import ContentBucketReplicationConfiguration as ContentBucketReplicationConfiguration
from .storage import ContentBucketReplicationDestination as ContentBucketReplicationDestination
from .storage import ContentBucketReplicationRule as ContentBucketReplicationRule
from .storage import ContentBucketServerSideEncryptionByDefault as ContentBucketServerSideEncryptionByDefault
from .storage import ContentBucketServerSideEncryptionRule as ContentBucketServerSideEncryptionRule
from .storage import ContentLogBucket as ContentLogBucket
from .storage import ContentLogBucketBucketEncryption as ContentLogBucketBucketEncryption
from .storage import ContentLogBucketDefaultRetention as ContentLogBucketDefaultRetention
from .storage import ContentLogBucketDeleteMarkerReplication as ContentLogBucketDeleteMarkerReplication
from .storage import ContentLogBucketObjectLockConfiguration as ContentLogBucketObjectLockConfiguration
from .storage import ContentLogBucketObjectLockRule as ContentLogBucketObjectLockRule
from .storage import ContentLogBucketPolicyPolicy as ContentLogBucketPolicyPolicy
from .storage import ContentLogBucketPolicyPolicyAllowStatement1 as ContentLogBucketPolicyPolicyAllowStatement1
from .storage import ContentLogBucketPolicyPolicyDenyStatement0 as ContentLogBucketPolicyPolicyDenyStatement0
from .storage import ContentLogBucketPolicyPolicyPolicyDocument as ContentLogBucketPolicyPolicyPolicyDocument
from .storage import ContentLogBucketPublicAccessBlockConfiguration as ContentLogBucketPublicAccessBlockConfiguration
from .storage import ContentLogBucketServerSideEncryptionByDefault as ContentLogBucketServerSideEncryptionByDefault
from .storage import ContentLogBucketServerSideEncryptionRule as ContentLogBucketServerSideEncryptionRule
from .storage import ContentReplicaBucket as ContentReplicaBucket
from .storage import ContentReplicaBucketBucketEncryption as ContentReplicaBucketBucketEncryption
from .storage import ContentReplicaBucketDeleteMarkerReplication as ContentReplicaBucketDeleteMarkerReplication
from .storage import ContentReplicaBucketPolicyPolicy as ContentReplicaBucketPolicyPolicy
from .storage import ContentReplicaBucketPolicyPolicyAllowStatement1 as ContentReplicaBucketPolicyPolicyAllowStatement1
from .storage import ContentReplicaBucketPolicyPolicyDenyStatement0 as ContentReplicaBucketPolicyPolicyDenyStatement0
from .storage import ContentReplicaBucketPolicyPolicyPolicyDocument as ContentReplicaBucketPolicyPolicyPolicyDocument
from .storage import ContentReplicaBucketPublicAccessBlockConfiguration as ContentReplicaBucketPublicAccessBlockConfiguration
from .storage import ContentReplicaBucketServerSideEncryptionByDefault as ContentReplicaBucketServerSideEncryptionByDefault
from .storage import ContentReplicaBucketServerSideEncryptionRule as ContentReplicaBucketServerSideEncryptionRule

__all__: list[str] = ['ARN_LIKE', 'AWS_ACCOUNT_ID', 'AWS_STACK_ID', 'AppName', 'BOOL', 'CloudFrontLogsBucket', 'CloudFrontLogsBucketBucketEncryption', 'CloudFrontLogsBucketDeleteMarkerReplication', 'CloudFrontLogsBucketLoggingConfiguration', 'CloudFrontLogsBucketPolicyPolicy', 'CloudFrontLogsBucketPolicyPolicyAllowStatement1', 'CloudFrontLogsBucketPolicyPolicyDenyStatement0', 'CloudFrontLogsBucketPolicyPolicyPolicyDocument', 'CloudFrontLogsBucketPublicAccessBlockConfiguration', 'CloudFrontLogsBucketReplicationConfiguration', 'CloudFrontLogsBucketReplicationDestination', 'CloudFrontLogsBucketReplicationRule', 'CloudFrontLogsBucketServerSideEncryptionByDefault', 'CloudFrontLogsBucketServerSideEncryptionRule', 'CloudFrontLogsLogBucket', 'CloudFrontLogsLogBucketBucketEncryption', 'CloudFrontLogsLogBucketDefaultRetention', 'CloudFrontLogsLogBucketDeleteMarkerReplication', 'CloudFrontLogsLogBucketObjectLockConfiguration', 'CloudFrontLogsLogBucketObjectLockRule', 'CloudFrontLogsLogBucketPolicyPolicy', 'CloudFrontLogsLogBucketPolicyPolicyAllowStatement1', 'CloudFrontLogsLogBucketPolicyPolicyDenyStatement0', 'CloudFrontLogsLogBucketPolicyPolicyPolicyDocument', 'CloudFrontLogsLogBucketPublicAccessBlockConfiguration', 'CloudFrontLogsLogBucketServerSideEncryptionByDefault', 'CloudFrontLogsLogBucketServerSideEncryptionRule', 'CloudFrontLogsReplicaBucket', 'CloudFrontLogsReplicaBucketBucketEncryption', 'CloudFrontLogsReplicaBucketDeleteMarkerReplication', 'CloudFrontLogsReplicaBucketPolicyPolicy', 'CloudFrontLogsReplicaBucketPolicyPolicyAllowStatement1', 'CloudFrontLogsReplicaBucketPolicyPolicyDenyStatement0', 'CloudFrontLogsReplicaBucketPolicyPolicyPolicyDocument', 'CloudFrontLogsReplicaBucketPublicAccessBlockConfiguration', 'CloudFrontLogsReplicaBucketServerSideEncryptionByDefault', 'CloudFrontLogsReplicaBucketServerSideEncryptionRule', 'CloudFrontLogsReplicationPolicy', 'CloudFrontLogsReplicationPolicyAllowStatement0', 'CloudFrontLogsReplicationPolicyAllowStatement1', 'CloudFrontLogsReplicationPolicyAllowStatement2', 'CloudFrontLogsReplicationPolicyPolicyDocument', 'CloudFrontLogsReplicationRole', 'CloudFrontLogsReplicationRoleAllowStatement0', 'CloudFrontLogsReplicationRoleAssumeRolePolicyDocument', 'ContentBucket', 'ContentBucketBucketEncryption', 'ContentBucketDeleteMarkerReplication', 'ContentBucketLoggingConfiguration', 'ContentBucketPolicyPolicy', 'ContentBucketPolicyPolicyAllowStatement1', 'ContentBucketPolicyPolicyDenyStatement0', 'ContentBucketPolicyPolicyPolicyDocument', 'ContentBucketPublicAccessBlockConfiguration', 'ContentBucketReplicationConfiguration', 'ContentBucketReplicationDestination', 'ContentBucketReplicationRule', 'ContentBucketServerSideEncryptionByDefault', 'ContentBucketServerSideEncryptionRule', 'ContentLogBucket', 'ContentLogBucketBucketEncryption', 'ContentLogBucketDefaultRetention', 'ContentLogBucketDeleteMarkerReplication', 'ContentLogBucketObjectLockConfiguration', 'ContentLogBucketObjectLockRule', 'ContentLogBucketPolicyPolicy', 'ContentLogBucketPolicyPolicyAllowStatement1', 'ContentLogBucketPolicyPolicyDenyStatement0', 'ContentLogBucketPolicyPolicyPolicyDocument', 'ContentLogBucketPublicAccessBlockConfiguration', 'ContentLogBucketServerSideEncryptionByDefault', 'ContentLogBucketServerSideEncryptionRule', 'ContentReplicaBucket', 'ContentReplicaBucketBucketEncryption', 'ContentReplicaBucketDeleteMarkerReplication', 'ContentReplicaBucketPolicyPolicy', 'ContentReplicaBucketPolicyPolicyAllowStatement1', 'ContentReplicaBucketPolicyPolicyDenyStatement0', 'ContentReplicaBucketPolicyPolicyPolicyDocument', 'ContentReplicaBucketPublicAccessBlockConfiguration', 'ContentReplicaBucketServerSideEncryptionByDefault', 'ContentReplicaBucketServerSideEncryptionRule', 'ContentReplicationPolicy', 'ContentReplicationPolicyAllowStatement0', 'ContentReplicationPolicyAllowStatement1', 'ContentReplicationPolicyAllowStatement2', 'ContentReplicationPolicyPolicyDocument', 'ContentReplicationRole', 'ContentReplicationRoleAllowStatement0', 'ContentReplicationRoleAssumeRolePolicyDocument', 'DenyStatement', 'Distribution', 'DistributionDefaultCacheBehavior', 'DistributionDistributionConfig', 'DistributionLogging', 'DistributionOrigin', 'DistributionS3OriginConfig', 'DistributionViewerCertificate', 'Join', 'ObjectLockEnabled', 'ObjectLockRetentionMode', 'OriginAccessControl', 'OriginAccessControlOriginAccessControlConfig', 'Output', 'Parameter', 'PolicyDocument', 'PolicyStatement', 'ReplicationRuleStatus', 'STRING', 'STRING_EQUALS', 'Select', 'ServerSideEncryption', 'SiteURLOutput', 'Split', 'Sub', 'Template', 'WebACL', 'cloudformation_dataclass', 'cloudfront', 'get_att', 'iam', 'ref', 's3', 'setup_resources']
