"""S3 bucket with encryption-required policy

Generated by cfn-dataclasses-import."""

from cloudformation_dataclasses.core import (
    DenyStatement,
    DeploymentContext,
    PolicyDocument,
    STRING_NOT_EQUALS,
    Tag,
    Template,
    cloudformation_dataclass,
    get_att,
    ref,
)
from cloudformation_dataclasses.aws import s3
from cloudformation_dataclasses.aws.s3 import ServerSideEncryption
from cloudformation_dataclasses.intrinsics import Sub

from .resources import *  # noqa: F403, F401

__all__ = [
    "DenyStatement",
    "MyData",
    "MyDataPolicy",
    "PolicyDocument",
    "STRING_NOT_EQUALS",
    "ServerSideEncryption",
    "Sub",
    "Template",
    "cloudformation_dataclass",
    "get_att",
    "ref",
    "s3",
]
