"""AWS CloudFormation Sample Template RDS_Snapshot_On_Delete: Sample template showing how to create an RDS DBInstance that is snapshotted on stack deletion. **WARNING** This template creates an Amazon...

Generated by cfn-dataclasses-import."""

from cloudformation_dataclasses.core import (
    Output,
    Template,
    cloudformation_dataclass,
    get_att,
    ref,
)
from cloudformation_dataclasses.aws import rds
from cloudformation_dataclasses.intrinsics import Join

from .stack import *  # noqa: F403, F401

__all__ = [
    "JDBCConnectionStringOutput",
    "Join",
    "MyDB",
    "Output",
    "Template",
    "cloudformation_dataclass",
    "get_att",
    "rds",
    "ref",
]
