"""Create an Amazon Data Firehose stream with server-side encryption set using AWS Managed keys and destination error logging enabled to a created Amazon CloudWatch log group and log stream.

Generated by cfn-dataclasses-import."""

from cloudformation_dataclasses.core import (
    Condition,
    Parameter,
    PolicyDocument,
    PolicyStatement,
    STRING,
    STRING_EQUALS,
    Template,
    cloudformation_dataclass,
    get_att,
    ref,
)
from cloudformation_dataclasses.aws import iam, kinesisfirehose, logs
from cloudformation_dataclasses.intrinsics import (
    AWS_ACCOUNT_ID,
    AWS_NO_VALUE,
    Equals,
    If,
    Join,
    Not,
    Sub,
)

from .stack import *  # noqa: F403, F401

__all__ = [
    "AWS_ACCOUNT_ID",
    "AWS_NO_VALUE",
    "CloudWatchLogGroupRetention",
    "CloudWatchLogsKMSKey",
    "CloudWatchLogsKMSKeyConditionCondition",
    "Condition",
    "DeliveryRole",
    "DeliveryStream",
    "DeliveryStreamName",
    "DestinationBucketName",
    "Equals",
    "FirehoseLogGroup",
    "FirehoseLogStream",
    "If",
    "Join",
    "LogGroupName",
    "LogStreamName",
    "Not",
    "Parameter",
    "PolicyDocument",
    "PolicyStatement",
    "STRING",
    "STRING_EQUALS",
    "Sub",
    "Template",
    "cloudformation_dataclass",
    "get_att",
    "iam",
    "kinesisfirehose",
    "logs",
    "ref",
]
