"""CI/CD optimized AWS CloudFormation Sample Template for AWS Service Catalog Portfolio creation. ### Before deployment please make sure that all parameters are reviewed and updated according the spec...

Generated by cfn-dataclasses-import."""

from cloudformation_dataclasses.core import (
    Output,
    Parameter,
    STRING,
    Template,
    cloudformation_dataclass,
    get_att,
    ref,
)
from cloudformation_dataclasses.core.template import Condition as TemplateCondition
from cloudformation_dataclasses.core.resource_loader import setup_resources
from cloudformation_dataclasses.aws import servicecatalog
from cloudformation_dataclasses.intrinsics import Equals, Sub

from .params import *  # noqa: F403, F401

# Auto-discover and import resource files in topological order
setup_resources(__file__, __name__, globals())

# Import outputs after resources (outputs reference resource classes)
from .outputs import *  # noqa: F403, F401

__all__ = [
    "AccountIdOfChildAWSAccount",
    "ActivateProductTagOptions",
    "ConditionShareThisPortfolioCondition",
    "Dept",
    "Env",
    "Equals",
    "Output",
    "Owner",
    "Parameter",
    "PortfolioDescription",
    "PortfolioDisplayName",
    "PortfolioProviderName",
    "ProductDept",
    "ProductEnv",
    "ProductOwner",
    "ProductUser",
    "STRING",
    "ServiceCatalogPortfolio",
    "ServiceCatalogPortfolioNameOutput",
    "ServiceCatalogPortfolioOutput",
    "ServiceCatalogPortfolioShare",
    "ServiceCatalogProductTagOptionsDept",
    "ServiceCatalogProductTagOptionsDeptOutput",
    "ServiceCatalogProductTagOptionsEnv",
    "ServiceCatalogProductTagOptionsOwner",
    "ServiceCatalogProductTagOptionsUser",
    "ShareThisPortfolio",
    "Sub",
    "Template",
    "User",
    "cloudformation_dataclass",
    "get_att",
    "ref",
    "servicecatalog",
]
