"""DynamoDB CloudFormation template examples."""

from cloudformation_dataclasses.aws.dynamodb import (
    AttributeDefinition,
    GlobalSecondaryIndex,
    KeySchema,
    LocalSecondaryIndex,
    PointInTimeRecoverySpecification,
    Projection,
    ProvisionedThroughput,
    Table,
)
from cloudformation_dataclasses.core import (
    HASH,
    KEYS_ONLY,
    NUMBER,
    RANGE,
    S,
    STRING,
    AttributeType,
    KeyType,
    Output,
    Parameter,
    ParameterType,
    ProjectionType,
    Template,
    cloudformation_dataclass,
    ref,
)

__all__ = [
    "AttributeDefinition",
    "AttributeType",
    "GlobalSecondaryIndex",
    "HASH",
    "KEYS_ONLY",
    "KeySchema",
    "KeyType",
    "LocalSecondaryIndex",
    "NUMBER",
    "Output",
    "Parameter",
    "ParameterType",
    "PointInTimeRecoverySpecification",
    "Projection",
    "ProjectionType",
    "ProvisionedThroughput",
    "RANGE",
    "S",
    "STRING",
    "Table",
    "Template",
    "cloudformation_dataclass",
    "ref",
]
