"""
AWS CloudFormation RTBFabric Resources

⚠️  AUTO-GENERATED FILE - DO NOT EDIT MANUALLY ⚠️

This file is automatically generated from the AWS CloudFormation Resource Specification.
Any manual changes will be overwritten when regenerated.

Version Information:
  CloudFormation Spec: 2025.12.11
  Generator Version: 1.0.0
  Combined: spec-2025.12.11_gen-1.0.0
  Generated: 2025-12-22 14:55:27

To regenerate:
    uv run python -m cloudformation_dataclasses.codegen.generator --service RTBFabric
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, ClassVar, Optional, Union

from cloudformation_dataclasses.core.base import CloudFormationResource, PropertyType, Tag
from cloudformation_dataclasses.intrinsics.functions import GetAtt, Ref, Sub


# =============================================================================
# Service Constants (auto-generated from botocore)
# =============================================================================

class FilterType:
    """FilterType enum values."""

    INCLUDE = "INCLUDE"
    EXCLUDE = "EXCLUDE"


class LinkDirection:
    """LinkDirection enum values."""

    RESPONSE = "RESPONSE"
    REQUEST = "REQUEST"


class LinkStatus:
    """LinkStatus enum values."""

    PENDING_CREATION = "PENDING_CREATION"
    PENDING_REQUEST = "PENDING_REQUEST"
    REQUESTED = "REQUESTED"
    ACCEPTED = "ACCEPTED"
    ACTIVE = "ACTIVE"
    REJECTED = "REJECTED"
    FAILED = "FAILED"
    PENDING_DELETION = "PENDING_DELETION"
    DELETED = "DELETED"
    PENDING_UPDATE = "PENDING_UPDATE"
    PENDING_ISOLATION = "PENDING_ISOLATION"
    ISOLATED = "ISOLATED"
    PENDING_RESTORATION = "PENDING_RESTORATION"


class Protocol:
    """Protocol enum values."""

    HTTP = "HTTP"
    HTTPS = "HTTPS"


class RequesterGatewayStatus:
    """RequesterGatewayStatus enum values."""

    PENDING_CREATION = "PENDING_CREATION"
    ACTIVE = "ACTIVE"
    PENDING_DELETION = "PENDING_DELETION"
    DELETED = "DELETED"
    ERROR = "ERROR"
    PENDING_UPDATE = "PENDING_UPDATE"
    ISOLATED = "ISOLATED"
    PENDING_ISOLATION = "PENDING_ISOLATION"
    PENDING_RESTORATION = "PENDING_RESTORATION"


class ResponderErrorMaskingAction:
    """ResponderErrorMaskingAction enum values."""

    NO_BID = "NO_BID"
    PASSTHROUGH = "PASSTHROUGH"


class ResponderErrorMaskingLoggingType:
    """ResponderErrorMaskingLoggingType enum values."""

    NONE = "NONE"
    METRIC = "METRIC"
    RESPONSE = "RESPONSE"


class ResponderGatewayStatus:
    """ResponderGatewayStatus enum values."""

    PENDING_CREATION = "PENDING_CREATION"
    ACTIVE = "ACTIVE"
    PENDING_DELETION = "PENDING_DELETION"
    DELETED = "DELETED"
    ERROR = "ERROR"
    PENDING_UPDATE = "PENDING_UPDATE"
    ISOLATED = "ISOLATED"
    PENDING_ISOLATION = "PENDING_ISOLATION"
    PENDING_RESTORATION = "PENDING_RESTORATION"


# Convenient aliases for enum values
INCLUDE = FilterType.INCLUDE
EXCLUDE = FilterType.EXCLUDE
RESPONSE = LinkDirection.RESPONSE
REQUEST = LinkDirection.REQUEST
PENDING_CREATION = LinkStatus.PENDING_CREATION
PENDING_REQUEST = LinkStatus.PENDING_REQUEST
REQUESTED = LinkStatus.REQUESTED
ACCEPTED = LinkStatus.ACCEPTED
ACTIVE = LinkStatus.ACTIVE
REJECTED = LinkStatus.REJECTED
FAILED = LinkStatus.FAILED
PENDING_DELETION = LinkStatus.PENDING_DELETION
DELETED = LinkStatus.DELETED
PENDING_UPDATE = LinkStatus.PENDING_UPDATE
PENDING_ISOLATION = LinkStatus.PENDING_ISOLATION
ISOLATED = LinkStatus.ISOLATED
PENDING_RESTORATION = LinkStatus.PENDING_RESTORATION
HTTP = Protocol.HTTP
HTTPS = Protocol.HTTPS
PENDING_CREATION = RequesterGatewayStatus.PENDING_CREATION
ACTIVE = RequesterGatewayStatus.ACTIVE
PENDING_DELETION = RequesterGatewayStatus.PENDING_DELETION
DELETED = RequesterGatewayStatus.DELETED
ERROR = RequesterGatewayStatus.ERROR
PENDING_UPDATE = RequesterGatewayStatus.PENDING_UPDATE
ISOLATED = RequesterGatewayStatus.ISOLATED
PENDING_ISOLATION = RequesterGatewayStatus.PENDING_ISOLATION
PENDING_RESTORATION = RequesterGatewayStatus.PENDING_RESTORATION
NO_BID = ResponderErrorMaskingAction.NO_BID
PASSTHROUGH = ResponderErrorMaskingAction.PASSTHROUGH
NONE = ResponderErrorMaskingLoggingType.NONE
METRIC = ResponderErrorMaskingLoggingType.METRIC
RESPONSE = ResponderErrorMaskingLoggingType.RESPONSE
PENDING_CREATION = ResponderGatewayStatus.PENDING_CREATION
ACTIVE = ResponderGatewayStatus.ACTIVE
PENDING_DELETION = ResponderGatewayStatus.PENDING_DELETION
DELETED = ResponderGatewayStatus.DELETED
ERROR = ResponderGatewayStatus.ERROR
PENDING_UPDATE = ResponderGatewayStatus.PENDING_UPDATE
ISOLATED = ResponderGatewayStatus.ISOLATED
PENDING_ISOLATION = ResponderGatewayStatus.PENDING_ISOLATION
PENDING_RESTORATION = ResponderGatewayStatus.PENDING_RESTORATION


# PropertyType submodules (e.g., ec2.instance.NetworkInterface)
from . import inbound_external_link
from . import link
from . import outbound_external_link
from . import responder_gateway


@dataclass
class InboundExternalLink(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rtbfa"""

    resource_type: ClassVar[str] = "AWS::RTBFabric::InboundExternalLink"
    LINK_ATTRIBUTES = "LinkAttributes"
    LINK_LOG_SETTINGS = "LinkLogSettings"
    GATEWAY_ID = "GatewayId"
    TAGS = "Tags"

    _property_mappings: ClassVar[dict[str, str]] = {
        "link_attributes": "LinkAttributes",
        "link_log_settings": "LinkLogSettings",
        "gateway_id": "GatewayId",
        "tags": "Tags",
    }

    link_attributes: Optional[inbound_external_link.LinkAttributes] = None
    link_log_settings: Optional[inbound_external_link.LinkLogSettings] = None
    gateway_id: Optional[Union[str, Ref, GetAtt, Sub]] = None
    tags: Optional[list[inbound_external_link.Tag]] = None

    @property
    def attr_link_status(self) -> GetAtt:
        """Get the LinkStatus attribute."""
        return self.get_att("LinkStatus")

    @property
    def attr_updated_timestamp(self) -> GetAtt:
        """Get the UpdatedTimestamp attribute."""
        return self.get_att("UpdatedTimestamp")

    @property
    def attr_created_timestamp(self) -> GetAtt:
        """Get the CreatedTimestamp attribute."""
        return self.get_att("CreatedTimestamp")

    @property
    def attr_arn(self) -> GetAtt:
        """Get the Arn attribute."""
        return self.get_att("Arn")

    @property
    def attr_link_id(self) -> GetAtt:
        """Get the LinkId attribute."""
        return self.get_att("LinkId")



@dataclass
class Link(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rtbfa"""

    resource_type: ClassVar[str] = "AWS::RTBFabric::Link"
    LINK_ATTRIBUTES = "LinkAttributes"
    MODULE_CONFIGURATION_LIST = "ModuleConfigurationList"
    HTTP_RESPONDER_ALLOWED = "HttpResponderAllowed"
    LINK_LOG_SETTINGS = "LinkLogSettings"
    PEER_GATEWAY_ID = "PeerGatewayId"
    GATEWAY_ID = "GatewayId"
    TAGS = "Tags"

    _property_mappings: ClassVar[dict[str, str]] = {
        "link_attributes": "LinkAttributes",
        "module_configuration_list": "ModuleConfigurationList",
        "http_responder_allowed": "HttpResponderAllowed",
        "link_log_settings": "LinkLogSettings",
        "peer_gateway_id": "PeerGatewayId",
        "gateway_id": "GatewayId",
        "tags": "Tags",
    }

    link_attributes: Optional[link.LinkAttributes] = None
    module_configuration_list: Optional[list[link.ModuleConfiguration]] = None
    http_responder_allowed: Optional[Union[bool, Ref, GetAtt, Sub]] = None
    link_log_settings: Optional[link.LinkLogSettings] = None
    peer_gateway_id: Optional[Union[str, Ref, GetAtt, Sub]] = None
    gateway_id: Optional[Union[str, Ref, GetAtt, Sub]] = None
    tags: Optional[list[link.Tag]] = None

    @property
    def attr_link_status(self) -> GetAtt:
        """Get the LinkStatus attribute."""
        return self.get_att("LinkStatus")

    @property
    def attr_updated_timestamp(self) -> GetAtt:
        """Get the UpdatedTimestamp attribute."""
        return self.get_att("UpdatedTimestamp")

    @property
    def attr_created_timestamp(self) -> GetAtt:
        """Get the CreatedTimestamp attribute."""
        return self.get_att("CreatedTimestamp")

    @property
    def attr_link_direction(self) -> GetAtt:
        """Get the LinkDirection attribute."""
        return self.get_att("LinkDirection")

    @property
    def attr_arn(self) -> GetAtt:
        """Get the Arn attribute."""
        return self.get_att("Arn")

    @property
    def attr_link_id(self) -> GetAtt:
        """Get the LinkId attribute."""
        return self.get_att("LinkId")



@dataclass
class OutboundExternalLink(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rtbfa"""

    resource_type: ClassVar[str] = "AWS::RTBFabric::OutboundExternalLink"
    LINK_ATTRIBUTES = "LinkAttributes"
    LINK_LOG_SETTINGS = "LinkLogSettings"
    PUBLIC_ENDPOINT = "PublicEndpoint"
    GATEWAY_ID = "GatewayId"
    TAGS = "Tags"

    _property_mappings: ClassVar[dict[str, str]] = {
        "link_attributes": "LinkAttributes",
        "link_log_settings": "LinkLogSettings",
        "public_endpoint": "PublicEndpoint",
        "gateway_id": "GatewayId",
        "tags": "Tags",
    }

    link_attributes: Optional[outbound_external_link.LinkAttributes] = None
    link_log_settings: Optional[outbound_external_link.LinkLogSettings] = None
    public_endpoint: Optional[Union[str, Ref, GetAtt, Sub]] = None
    gateway_id: Optional[Union[str, Ref, GetAtt, Sub]] = None
    tags: Optional[list[outbound_external_link.Tag]] = None

    @property
    def attr_link_status(self) -> GetAtt:
        """Get the LinkStatus attribute."""
        return self.get_att("LinkStatus")

    @property
    def attr_updated_timestamp(self) -> GetAtt:
        """Get the UpdatedTimestamp attribute."""
        return self.get_att("UpdatedTimestamp")

    @property
    def attr_created_timestamp(self) -> GetAtt:
        """Get the CreatedTimestamp attribute."""
        return self.get_att("CreatedTimestamp")

    @property
    def attr_arn(self) -> GetAtt:
        """Get the Arn attribute."""
        return self.get_att("Arn")

    @property
    def attr_link_id(self) -> GetAtt:
        """Get the LinkId attribute."""
        return self.get_att("LinkId")



@dataclass
class RequesterGateway(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rtbfa"""

    resource_type: ClassVar[str] = "AWS::RTBFabric::RequesterGateway"
    DESCRIPTION = "Description"
    VPC_ID = "VpcId"
    SUBNET_IDS = "SubnetIds"
    SECURITY_GROUP_IDS = "SecurityGroupIds"
    TAGS = "Tags"

    _property_mappings: ClassVar[dict[str, str]] = {
        "description": "Description",
        "vpc_id": "VpcId",
        "subnet_ids": "SubnetIds",
        "security_group_ids": "SecurityGroupIds",
        "tags": "Tags",
    }

    description: Optional[Union[str, Ref, GetAtt, Sub]] = None
    vpc_id: Optional[Union[str, Ref, GetAtt, Sub]] = None
    subnet_ids: Optional[Union[list[str], Ref]] = None
    security_group_ids: Optional[Union[list[str], Ref]] = None
    tags: Optional[list[Tag]] = None

    @property
    def attr_updated_timestamp(self) -> GetAtt:
        """Get the UpdatedTimestamp attribute."""
        return self.get_att("UpdatedTimestamp")

    @property
    def attr_created_timestamp(self) -> GetAtt:
        """Get the CreatedTimestamp attribute."""
        return self.get_att("CreatedTimestamp")

    @property
    def attr_requester_gateway_status(self) -> GetAtt:
        """Get the RequesterGatewayStatus attribute."""
        return self.get_att("RequesterGatewayStatus")

    @property
    def attr_domain_name(self) -> GetAtt:
        """Get the DomainName attribute."""
        return self.get_att("DomainName")

    @property
    def attr_active_links_count(self) -> GetAtt:
        """Get the ActiveLinksCount attribute."""
        return self.get_att("ActiveLinksCount")

    @property
    def attr_total_links_count(self) -> GetAtt:
        """Get the TotalLinksCount attribute."""
        return self.get_att("TotalLinksCount")

    @property
    def attr_gateway_id(self) -> GetAtt:
        """Get the GatewayId attribute."""
        return self.get_att("GatewayId")

    @property
    def attr_arn(self) -> GetAtt:
        """Get the Arn attribute."""
        return self.get_att("Arn")



@dataclass
class ResponderGateway(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rtbfa"""

    resource_type: ClassVar[str] = "AWS::RTBFabric::ResponderGateway"
    TRUST_STORE_CONFIGURATION = "TrustStoreConfiguration"
    DESCRIPTION = "Description"
    VPC_ID = "VpcId"
    DOMAIN_NAME = "DomainName"
    PORT = "Port"
    MANAGED_ENDPOINT_CONFIGURATION = "ManagedEndpointConfiguration"
    PROTOCOL = "Protocol"
    SUBNET_IDS = "SubnetIds"
    SECURITY_GROUP_IDS = "SecurityGroupIds"
    TAGS = "Tags"

    _property_mappings: ClassVar[dict[str, str]] = {
        "trust_store_configuration": "TrustStoreConfiguration",
        "description": "Description",
        "vpc_id": "VpcId",
        "domain_name": "DomainName",
        "port": "Port",
        "managed_endpoint_configuration": "ManagedEndpointConfiguration",
        "protocol": "Protocol",
        "subnet_ids": "SubnetIds",
        "security_group_ids": "SecurityGroupIds",
        "tags": "Tags",
    }

    trust_store_configuration: Optional[responder_gateway.TrustStoreConfiguration] = None
    description: Optional[Union[str, Ref, GetAtt, Sub]] = None
    vpc_id: Optional[Union[str, Ref, GetAtt, Sub]] = None
    domain_name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    port: Optional[Union[int, Ref, GetAtt, Sub]] = None
    managed_endpoint_configuration: Optional[responder_gateway.ManagedEndpointConfiguration] = None
    protocol: Optional[Union[str, Ref, GetAtt, Sub]] = None
    subnet_ids: Optional[Union[list[str], Ref]] = None
    security_group_ids: Optional[Union[list[str], Ref]] = None
    tags: Optional[list[responder_gateway.Tag]] = None

    @property
    def attr_updated_timestamp(self) -> GetAtt:
        """Get the UpdatedTimestamp attribute."""
        return self.get_att("UpdatedTimestamp")

    @property
    def attr_created_timestamp(self) -> GetAtt:
        """Get the CreatedTimestamp attribute."""
        return self.get_att("CreatedTimestamp")

    @property
    def attr_responder_gateway_status(self) -> GetAtt:
        """Get the ResponderGatewayStatus attribute."""
        return self.get_att("ResponderGatewayStatus")

    @property
    def attr_gateway_id(self) -> GetAtt:
        """Get the GatewayId attribute."""
        return self.get_att("GatewayId")

    @property
    def attr_arn(self) -> GetAtt:
        """Get the Arn attribute."""
        return self.get_att("Arn")


