"""
AWS CloudFormation AppStream Resources

⚠️  AUTO-GENERATED FILE - DO NOT EDIT MANUALLY ⚠️

This file is automatically generated from the AWS CloudFormation Resource Specification.
Any manual changes will be overwritten when regenerated.

Version Information:
  CloudFormation Spec: 2025.12.11
  Generator Version: 1.0.0
  Combined: spec-2025.12.11_gen-1.0.0
  Generated: 2025-12-22 14:55:22

To regenerate:
    uv run python -m cloudformation_dataclasses.codegen.generator --service AppStream
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, ClassVar, Optional, Union

from cloudformation_dataclasses.core.base import CloudFormationResource, PropertyType, Tag
from cloudformation_dataclasses.intrinsics.functions import GetAtt, Ref, Sub


# =============================================================================
# Service Constants (auto-generated from botocore)
# =============================================================================

class AccessEndpointType:
    """AccessEndpointType enum values."""

    STREAMING = "STREAMING"


class Action:
    """Action enum values."""

    CLIPBOARD_COPY_FROM_LOCAL_DEVICE = "CLIPBOARD_COPY_FROM_LOCAL_DEVICE"
    CLIPBOARD_COPY_TO_LOCAL_DEVICE = "CLIPBOARD_COPY_TO_LOCAL_DEVICE"
    FILE_UPLOAD = "FILE_UPLOAD"
    FILE_DOWNLOAD = "FILE_DOWNLOAD"
    PRINTING_TO_LOCAL_DEVICE = "PRINTING_TO_LOCAL_DEVICE"
    DOMAIN_PASSWORD_SIGNIN = "DOMAIN_PASSWORD_SIGNIN"
    DOMAIN_SMART_CARD_SIGNIN = "DOMAIN_SMART_CARD_SIGNIN"
    AUTO_TIME_ZONE_REDIRECTION = "AUTO_TIME_ZONE_REDIRECTION"


class AgentSoftwareVersion:
    """AgentSoftwareVersion enum values."""

    CURRENT_LATEST = "CURRENT_LATEST"
    ALWAYS_LATEST = "ALWAYS_LATEST"


class AppBlockBuilderAttribute:
    """AppBlockBuilderAttribute enum values."""

    IAM_ROLE_ARN = "IAM_ROLE_ARN"
    ACCESS_ENDPOINTS = "ACCESS_ENDPOINTS"
    VPC_CONFIGURATION_SECURITY_GROUP_IDS = "VPC_CONFIGURATION_SECURITY_GROUP_IDS"


class AppBlockBuilderPlatformType:
    """AppBlockBuilderPlatformType enum values."""

    WINDOWS_SERVER_2019 = "WINDOWS_SERVER_2019"


class AppBlockBuilderState:
    """AppBlockBuilderState enum values."""

    STARTING = "STARTING"
    RUNNING = "RUNNING"
    STOPPING = "STOPPING"
    STOPPED = "STOPPED"


class AppBlockBuilderStateChangeReasonCode:
    """AppBlockBuilderStateChangeReasonCode enum values."""

    INTERNAL_ERROR = "INTERNAL_ERROR"


class AppBlockState:
    """AppBlockState enum values."""

    INACTIVE = "INACTIVE"
    ACTIVE = "ACTIVE"


class AppVisibility:
    """AppVisibility enum values."""

    ALL = "ALL"
    ASSOCIATED = "ASSOCIATED"


class ApplicationAttribute:
    """ApplicationAttribute enum values."""

    LAUNCH_PARAMETERS = "LAUNCH_PARAMETERS"
    WORKING_DIRECTORY = "WORKING_DIRECTORY"


class AuthenticationType:
    """AuthenticationType enum values."""

    API = "API"
    SAML = "SAML"
    USERPOOL = "USERPOOL"
    AWS_AD = "AWS_AD"


class CertificateBasedAuthStatus:
    """CertificateBasedAuthStatus enum values."""

    DISABLED = "DISABLED"
    ENABLED = "ENABLED"
    ENABLED_NO_DIRECTORY_LOGIN_FALLBACK = "ENABLED_NO_DIRECTORY_LOGIN_FALLBACK"


class DynamicAppProvidersEnabled:
    """DynamicAppProvidersEnabled enum values."""

    ENABLED = "ENABLED"
    DISABLED = "DISABLED"


class ExportImageTaskState:
    """ExportImageTaskState enum values."""

    EXPORTING = "EXPORTING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class FleetAttribute:
    """FleetAttribute enum values."""

    VPC_CONFIGURATION = "VPC_CONFIGURATION"
    VPC_CONFIGURATION_SECURITY_GROUP_IDS = "VPC_CONFIGURATION_SECURITY_GROUP_IDS"
    DOMAIN_JOIN_INFO = "DOMAIN_JOIN_INFO"
    IAM_ROLE_ARN = "IAM_ROLE_ARN"
    USB_DEVICE_FILTER_STRINGS = "USB_DEVICE_FILTER_STRINGS"
    SESSION_SCRIPT_S3_LOCATION = "SESSION_SCRIPT_S3_LOCATION"
    MAX_SESSIONS_PER_INSTANCE = "MAX_SESSIONS_PER_INSTANCE"
    VOLUME_CONFIGURATION = "VOLUME_CONFIGURATION"


class FleetErrorCode:
    """FleetErrorCode enum values."""

    IAM_SERVICE_ROLE_MISSING_ENI_DESCRIBE_ACTION = "IAM_SERVICE_ROLE_MISSING_ENI_DESCRIBE_ACTION"
    IAM_SERVICE_ROLE_MISSING_ENI_CREATE_ACTION = "IAM_SERVICE_ROLE_MISSING_ENI_CREATE_ACTION"
    IAM_SERVICE_ROLE_MISSING_ENI_DELETE_ACTION = "IAM_SERVICE_ROLE_MISSING_ENI_DELETE_ACTION"
    NETWORK_INTERFACE_LIMIT_EXCEEDED = "NETWORK_INTERFACE_LIMIT_EXCEEDED"
    INTERNAL_SERVICE_ERROR = "INTERNAL_SERVICE_ERROR"
    IAM_SERVICE_ROLE_IS_MISSING = "IAM_SERVICE_ROLE_IS_MISSING"
    MACHINE_ROLE_IS_MISSING = "MACHINE_ROLE_IS_MISSING"
    STS_DISABLED_IN_REGION = "STS_DISABLED_IN_REGION"
    SUBNET_HAS_INSUFFICIENT_IP_ADDRESSES = "SUBNET_HAS_INSUFFICIENT_IP_ADDRESSES"
    IAM_SERVICE_ROLE_MISSING_DESCRIBE_SUBNET_ACTION = "IAM_SERVICE_ROLE_MISSING_DESCRIBE_SUBNET_ACTION"
    SUBNET_NOT_FOUND = "SUBNET_NOT_FOUND"
    IMAGE_NOT_FOUND = "IMAGE_NOT_FOUND"
    INVALID_SUBNET_CONFIGURATION = "INVALID_SUBNET_CONFIGURATION"
    SECURITY_GROUPS_NOT_FOUND = "SECURITY_GROUPS_NOT_FOUND"
    IGW_NOT_ATTACHED = "IGW_NOT_ATTACHED"
    IAM_SERVICE_ROLE_MISSING_DESCRIBE_SECURITY_GROUPS_ACTION = "IAM_SERVICE_ROLE_MISSING_DESCRIBE_SECURITY_GROUPS_ACTION"
    FLEET_STOPPED = "FLEET_STOPPED"
    FLEET_INSTANCE_PROVISIONING_FAILURE = "FLEET_INSTANCE_PROVISIONING_FAILURE"
    DOMAIN_JOIN_ERROR_FILE_NOT_FOUND = "DOMAIN_JOIN_ERROR_FILE_NOT_FOUND"
    DOMAIN_JOIN_ERROR_ACCESS_DENIED = "DOMAIN_JOIN_ERROR_ACCESS_DENIED"
    DOMAIN_JOIN_ERROR_LOGON_FAILURE = "DOMAIN_JOIN_ERROR_LOGON_FAILURE"
    DOMAIN_JOIN_ERROR_INVALID_PARAMETER = "DOMAIN_JOIN_ERROR_INVALID_PARAMETER"
    DOMAIN_JOIN_ERROR_MORE_DATA = "DOMAIN_JOIN_ERROR_MORE_DATA"
    DOMAIN_JOIN_ERROR_NO_SUCH_DOMAIN = "DOMAIN_JOIN_ERROR_NO_SUCH_DOMAIN"
    DOMAIN_JOIN_ERROR_NOT_SUPPORTED = "DOMAIN_JOIN_ERROR_NOT_SUPPORTED"
    DOMAIN_JOIN_NERR_INVALID_WORKGROUP_NAME = "DOMAIN_JOIN_NERR_INVALID_WORKGROUP_NAME"
    DOMAIN_JOIN_NERR_WORKSTATION_NOT_STARTED = "DOMAIN_JOIN_NERR_WORKSTATION_NOT_STARTED"
    DOMAIN_JOIN_ERROR_DS_MACHINE_ACCOUNT_QUOTA_EXCEEDED = "DOMAIN_JOIN_ERROR_DS_MACHINE_ACCOUNT_QUOTA_EXCEEDED"
    DOMAIN_JOIN_NERR_PASSWORD_EXPIRED = "DOMAIN_JOIN_NERR_PASSWORD_EXPIRED"
    DOMAIN_JOIN_INTERNAL_SERVICE_ERROR = "DOMAIN_JOIN_INTERNAL_SERVICE_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"


class FleetState:
    """FleetState enum values."""

    STARTING = "STARTING"
    RUNNING = "RUNNING"
    STOPPING = "STOPPING"
    STOPPED = "STOPPED"


class FleetType:
    """FleetType enum values."""

    ALWAYS_ON = "ALWAYS_ON"
    ON_DEMAND = "ON_DEMAND"
    ELASTIC = "ELASTIC"


class ImageBuilderState:
    """ImageBuilderState enum values."""

    PENDING = "PENDING"
    UPDATING_AGENT = "UPDATING_AGENT"
    RUNNING = "RUNNING"
    STOPPING = "STOPPING"
    STOPPED = "STOPPED"
    REBOOTING = "REBOOTING"
    SNAPSHOTTING = "SNAPSHOTTING"
    DELETING = "DELETING"
    FAILED = "FAILED"
    UPDATING = "UPDATING"
    PENDING_QUALIFICATION = "PENDING_QUALIFICATION"
    PENDING_SYNCING_APPS = "PENDING_SYNCING_APPS"
    SYNCING_APPS = "SYNCING_APPS"
    PENDING_IMAGE_IMPORT = "PENDING_IMAGE_IMPORT"


class ImageBuilderStateChangeReasonCode:
    """ImageBuilderStateChangeReasonCode enum values."""

    INTERNAL_ERROR = "INTERNAL_ERROR"
    IMAGE_UNAVAILABLE = "IMAGE_UNAVAILABLE"


class ImageSharedWithOthers:
    """ImageSharedWithOthers enum values."""

    TRUE = "TRUE"
    FALSE = "FALSE"


class ImageState:
    """ImageState enum values."""

    PENDING = "PENDING"
    AVAILABLE = "AVAILABLE"
    FAILED = "FAILED"
    COPYING = "COPYING"
    DELETING = "DELETING"
    CREATING = "CREATING"
    IMPORTING = "IMPORTING"
    VALIDATING = "VALIDATING"


class ImageStateChangeReasonCode:
    """ImageStateChangeReasonCode enum values."""

    INTERNAL_ERROR = "INTERNAL_ERROR"
    IMAGE_BUILDER_NOT_AVAILABLE = "IMAGE_BUILDER_NOT_AVAILABLE"
    IMAGE_COPY_FAILURE = "IMAGE_COPY_FAILURE"
    IMAGE_UPDATE_FAILURE = "IMAGE_UPDATE_FAILURE"
    IMAGE_IMPORT_FAILURE = "IMAGE_IMPORT_FAILURE"


class ImageType:
    """ImageType enum values."""

    CUSTOM = "CUSTOM"
    NATIVE = "NATIVE"


class LatestAppstreamAgentVersion:
    """LatestAppstreamAgentVersion enum values."""

    TRUE = "TRUE"
    FALSE = "FALSE"


class MessageAction:
    """MessageAction enum values."""

    SUPPRESS = "SUPPRESS"
    RESEND = "RESEND"


class PackagingType:
    """PackagingType enum values."""

    CUSTOM = "CUSTOM"
    APPSTREAM2 = "APPSTREAM2"


class Permission:
    """Permission enum values."""

    ENABLED = "ENABLED"
    DISABLED = "DISABLED"


class PlatformType:
    """PlatformType enum values."""

    WINDOWS = "WINDOWS"
    WINDOWS_SERVER_2016 = "WINDOWS_SERVER_2016"
    WINDOWS_SERVER_2019 = "WINDOWS_SERVER_2019"
    WINDOWS_SERVER_2022 = "WINDOWS_SERVER_2022"
    AMAZON_LINUX2 = "AMAZON_LINUX2"
    RHEL8 = "RHEL8"
    ROCKY_LINUX8 = "ROCKY_LINUX8"


class PreferredProtocol:
    """PreferredProtocol enum values."""

    TCP = "TCP"
    UDP = "UDP"


class SessionConnectionState:
    """SessionConnectionState enum values."""

    CONNECTED = "CONNECTED"
    NOT_CONNECTED = "NOT_CONNECTED"


class SessionState:
    """SessionState enum values."""

    ACTIVE = "ACTIVE"
    PENDING = "PENDING"
    EXPIRED = "EXPIRED"


class SoftwareDeploymentStatus:
    """SoftwareDeploymentStatus enum values."""

    STAGED_FOR_INSTALLATION = "STAGED_FOR_INSTALLATION"
    PENDING_INSTALLATION = "PENDING_INSTALLATION"
    INSTALLED = "INSTALLED"
    STAGED_FOR_UNINSTALLATION = "STAGED_FOR_UNINSTALLATION"
    PENDING_UNINSTALLATION = "PENDING_UNINSTALLATION"
    FAILED_TO_INSTALL = "FAILED_TO_INSTALL"
    FAILED_TO_UNINSTALL = "FAILED_TO_UNINSTALL"


class StackAttribute:
    """StackAttribute enum values."""

    STORAGE_CONNECTORS = "STORAGE_CONNECTORS"
    STORAGE_CONNECTOR_HOMEFOLDERS = "STORAGE_CONNECTOR_HOMEFOLDERS"
    STORAGE_CONNECTOR_GOOGLE_DRIVE = "STORAGE_CONNECTOR_GOOGLE_DRIVE"
    STORAGE_CONNECTOR_ONE_DRIVE = "STORAGE_CONNECTOR_ONE_DRIVE"
    REDIRECT_URL = "REDIRECT_URL"
    FEEDBACK_URL = "FEEDBACK_URL"
    THEME_NAME = "THEME_NAME"
    USER_SETTINGS = "USER_SETTINGS"
    EMBED_HOST_DOMAINS = "EMBED_HOST_DOMAINS"
    IAM_ROLE_ARN = "IAM_ROLE_ARN"
    ACCESS_ENDPOINTS = "ACCESS_ENDPOINTS"
    STREAMING_EXPERIENCE_SETTINGS = "STREAMING_EXPERIENCE_SETTINGS"


class StackErrorCode:
    """StackErrorCode enum values."""

    STORAGE_CONNECTOR_ERROR = "STORAGE_CONNECTOR_ERROR"
    INTERNAL_SERVICE_ERROR = "INTERNAL_SERVICE_ERROR"


class StorageConnectorType:
    """StorageConnectorType enum values."""

    HOMEFOLDERS = "HOMEFOLDERS"
    GOOGLE_DRIVE = "GOOGLE_DRIVE"
    ONE_DRIVE = "ONE_DRIVE"


class StreamView:
    """StreamView enum values."""

    APP = "APP"
    DESKTOP = "DESKTOP"


class ThemeAttribute:
    """ThemeAttribute enum values."""

    FOOTER_LINKS = "FOOTER_LINKS"


class ThemeState:
    """ThemeState enum values."""

    ENABLED = "ENABLED"
    DISABLED = "DISABLED"


class ThemeStyling:
    """ThemeStyling enum values."""

    LIGHT_BLUE = "LIGHT_BLUE"
    BLUE = "BLUE"
    PINK = "PINK"
    RED = "RED"


class UsageReportExecutionErrorCode:
    """UsageReportExecutionErrorCode enum values."""

    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
    ACCESS_DENIED = "ACCESS_DENIED"
    INTERNAL_SERVICE_ERROR = "INTERNAL_SERVICE_ERROR"


class UsageReportSchedule:
    """UsageReportSchedule enum values."""

    DAILY = "DAILY"


class UserStackAssociationErrorCode:
    """UserStackAssociationErrorCode enum values."""

    STACK_NOT_FOUND = "STACK_NOT_FOUND"
    USER_NAME_NOT_FOUND = "USER_NAME_NOT_FOUND"
    DIRECTORY_NOT_FOUND = "DIRECTORY_NOT_FOUND"
    INTERNAL_ERROR = "INTERNAL_ERROR"


class VisibilityType:
    """VisibilityType enum values."""

    PUBLIC = "PUBLIC"
    PRIVATE = "PRIVATE"
    SHARED = "SHARED"


# Convenient aliases for enum values
STREAMING = AccessEndpointType.STREAMING
CLIPBOARD_COPY_FROM_LOCAL_DEVICE = Action.CLIPBOARD_COPY_FROM_LOCAL_DEVICE
CLIPBOARD_COPY_TO_LOCAL_DEVICE = Action.CLIPBOARD_COPY_TO_LOCAL_DEVICE
FILE_UPLOAD = Action.FILE_UPLOAD
FILE_DOWNLOAD = Action.FILE_DOWNLOAD
PRINTING_TO_LOCAL_DEVICE = Action.PRINTING_TO_LOCAL_DEVICE
DOMAIN_PASSWORD_SIGNIN = Action.DOMAIN_PASSWORD_SIGNIN
DOMAIN_SMART_CARD_SIGNIN = Action.DOMAIN_SMART_CARD_SIGNIN
AUTO_TIME_ZONE_REDIRECTION = Action.AUTO_TIME_ZONE_REDIRECTION
CURRENT_LATEST = AgentSoftwareVersion.CURRENT_LATEST
ALWAYS_LATEST = AgentSoftwareVersion.ALWAYS_LATEST
IAM_ROLE_ARN = AppBlockBuilderAttribute.IAM_ROLE_ARN
ACCESS_ENDPOINTS = AppBlockBuilderAttribute.ACCESS_ENDPOINTS
VPC_CONFIGURATION_SECURITY_GROUP_IDS = AppBlockBuilderAttribute.VPC_CONFIGURATION_SECURITY_GROUP_IDS
WINDOWS_SERVER_2019 = AppBlockBuilderPlatformType.WINDOWS_SERVER_2019
STARTING = AppBlockBuilderState.STARTING
RUNNING = AppBlockBuilderState.RUNNING
STOPPING = AppBlockBuilderState.STOPPING
STOPPED = AppBlockBuilderState.STOPPED
INTERNAL_ERROR = AppBlockBuilderStateChangeReasonCode.INTERNAL_ERROR
INACTIVE = AppBlockState.INACTIVE
ACTIVE = AppBlockState.ACTIVE
ALL = AppVisibility.ALL
ASSOCIATED = AppVisibility.ASSOCIATED
LAUNCH_PARAMETERS = ApplicationAttribute.LAUNCH_PARAMETERS
WORKING_DIRECTORY = ApplicationAttribute.WORKING_DIRECTORY
API = AuthenticationType.API
SAML = AuthenticationType.SAML
USERPOOL = AuthenticationType.USERPOOL
AWS_AD = AuthenticationType.AWS_AD
DISABLED = CertificateBasedAuthStatus.DISABLED
ENABLED = CertificateBasedAuthStatus.ENABLED
ENABLED_NO_DIRECTORY_LOGIN_FALLBACK = CertificateBasedAuthStatus.ENABLED_NO_DIRECTORY_LOGIN_FALLBACK
ENABLED = DynamicAppProvidersEnabled.ENABLED
DISABLED = DynamicAppProvidersEnabled.DISABLED
EXPORTING = ExportImageTaskState.EXPORTING
COMPLETED = ExportImageTaskState.COMPLETED
FAILED = ExportImageTaskState.FAILED
VPC_CONFIGURATION = FleetAttribute.VPC_CONFIGURATION
VPC_CONFIGURATION_SECURITY_GROUP_IDS = FleetAttribute.VPC_CONFIGURATION_SECURITY_GROUP_IDS
DOMAIN_JOIN_INFO = FleetAttribute.DOMAIN_JOIN_INFO
IAM_ROLE_ARN = FleetAttribute.IAM_ROLE_ARN
USB_DEVICE_FILTER_STRINGS = FleetAttribute.USB_DEVICE_FILTER_STRINGS
SESSION_SCRIPT_S3_LOCATION = FleetAttribute.SESSION_SCRIPT_S3_LOCATION
MAX_SESSIONS_PER_INSTANCE = FleetAttribute.MAX_SESSIONS_PER_INSTANCE
VOLUME_CONFIGURATION = FleetAttribute.VOLUME_CONFIGURATION
IAM_SERVICE_ROLE_MISSING_ENI_DESCRIBE_ACTION = FleetErrorCode.IAM_SERVICE_ROLE_MISSING_ENI_DESCRIBE_ACTION
IAM_SERVICE_ROLE_MISSING_ENI_CREATE_ACTION = FleetErrorCode.IAM_SERVICE_ROLE_MISSING_ENI_CREATE_ACTION
IAM_SERVICE_ROLE_MISSING_ENI_DELETE_ACTION = FleetErrorCode.IAM_SERVICE_ROLE_MISSING_ENI_DELETE_ACTION
NETWORK_INTERFACE_LIMIT_EXCEEDED = FleetErrorCode.NETWORK_INTERFACE_LIMIT_EXCEEDED
INTERNAL_SERVICE_ERROR = FleetErrorCode.INTERNAL_SERVICE_ERROR
IAM_SERVICE_ROLE_IS_MISSING = FleetErrorCode.IAM_SERVICE_ROLE_IS_MISSING
MACHINE_ROLE_IS_MISSING = FleetErrorCode.MACHINE_ROLE_IS_MISSING
STS_DISABLED_IN_REGION = FleetErrorCode.STS_DISABLED_IN_REGION
SUBNET_HAS_INSUFFICIENT_IP_ADDRESSES = FleetErrorCode.SUBNET_HAS_INSUFFICIENT_IP_ADDRESSES
IAM_SERVICE_ROLE_MISSING_DESCRIBE_SUBNET_ACTION = FleetErrorCode.IAM_SERVICE_ROLE_MISSING_DESCRIBE_SUBNET_ACTION
SUBNET_NOT_FOUND = FleetErrorCode.SUBNET_NOT_FOUND
IMAGE_NOT_FOUND = FleetErrorCode.IMAGE_NOT_FOUND
INVALID_SUBNET_CONFIGURATION = FleetErrorCode.INVALID_SUBNET_CONFIGURATION
SECURITY_GROUPS_NOT_FOUND = FleetErrorCode.SECURITY_GROUPS_NOT_FOUND
IGW_NOT_ATTACHED = FleetErrorCode.IGW_NOT_ATTACHED
IAM_SERVICE_ROLE_MISSING_DESCRIBE_SECURITY_GROUPS_ACTION = FleetErrorCode.IAM_SERVICE_ROLE_MISSING_DESCRIBE_SECURITY_GROUPS_ACTION
FLEET_STOPPED = FleetErrorCode.FLEET_STOPPED
FLEET_INSTANCE_PROVISIONING_FAILURE = FleetErrorCode.FLEET_INSTANCE_PROVISIONING_FAILURE
DOMAIN_JOIN_ERROR_FILE_NOT_FOUND = FleetErrorCode.DOMAIN_JOIN_ERROR_FILE_NOT_FOUND
DOMAIN_JOIN_ERROR_ACCESS_DENIED = FleetErrorCode.DOMAIN_JOIN_ERROR_ACCESS_DENIED
DOMAIN_JOIN_ERROR_LOGON_FAILURE = FleetErrorCode.DOMAIN_JOIN_ERROR_LOGON_FAILURE
DOMAIN_JOIN_ERROR_INVALID_PARAMETER = FleetErrorCode.DOMAIN_JOIN_ERROR_INVALID_PARAMETER
DOMAIN_JOIN_ERROR_MORE_DATA = FleetErrorCode.DOMAIN_JOIN_ERROR_MORE_DATA
DOMAIN_JOIN_ERROR_NO_SUCH_DOMAIN = FleetErrorCode.DOMAIN_JOIN_ERROR_NO_SUCH_DOMAIN
DOMAIN_JOIN_ERROR_NOT_SUPPORTED = FleetErrorCode.DOMAIN_JOIN_ERROR_NOT_SUPPORTED
DOMAIN_JOIN_NERR_INVALID_WORKGROUP_NAME = FleetErrorCode.DOMAIN_JOIN_NERR_INVALID_WORKGROUP_NAME
DOMAIN_JOIN_NERR_WORKSTATION_NOT_STARTED = FleetErrorCode.DOMAIN_JOIN_NERR_WORKSTATION_NOT_STARTED
DOMAIN_JOIN_ERROR_DS_MACHINE_ACCOUNT_QUOTA_EXCEEDED = FleetErrorCode.DOMAIN_JOIN_ERROR_DS_MACHINE_ACCOUNT_QUOTA_EXCEEDED
DOMAIN_JOIN_NERR_PASSWORD_EXPIRED = FleetErrorCode.DOMAIN_JOIN_NERR_PASSWORD_EXPIRED
DOMAIN_JOIN_INTERNAL_SERVICE_ERROR = FleetErrorCode.DOMAIN_JOIN_INTERNAL_SERVICE_ERROR
VALIDATION_ERROR = FleetErrorCode.VALIDATION_ERROR
STARTING = FleetState.STARTING
RUNNING = FleetState.RUNNING
STOPPING = FleetState.STOPPING
STOPPED = FleetState.STOPPED
ALWAYS_ON = FleetType.ALWAYS_ON
ON_DEMAND = FleetType.ON_DEMAND
ELASTIC = FleetType.ELASTIC
PENDING = ImageBuilderState.PENDING
UPDATING_AGENT = ImageBuilderState.UPDATING_AGENT
RUNNING = ImageBuilderState.RUNNING
STOPPING = ImageBuilderState.STOPPING
STOPPED = ImageBuilderState.STOPPED
REBOOTING = ImageBuilderState.REBOOTING
SNAPSHOTTING = ImageBuilderState.SNAPSHOTTING
DELETING = ImageBuilderState.DELETING
FAILED = ImageBuilderState.FAILED
UPDATING = ImageBuilderState.UPDATING
PENDING_QUALIFICATION = ImageBuilderState.PENDING_QUALIFICATION
PENDING_SYNCING_APPS = ImageBuilderState.PENDING_SYNCING_APPS
SYNCING_APPS = ImageBuilderState.SYNCING_APPS
PENDING_IMAGE_IMPORT = ImageBuilderState.PENDING_IMAGE_IMPORT
INTERNAL_ERROR = ImageBuilderStateChangeReasonCode.INTERNAL_ERROR
IMAGE_UNAVAILABLE = ImageBuilderStateChangeReasonCode.IMAGE_UNAVAILABLE
TRUE = ImageSharedWithOthers.TRUE
FALSE = ImageSharedWithOthers.FALSE
PENDING = ImageState.PENDING
AVAILABLE = ImageState.AVAILABLE
FAILED = ImageState.FAILED
COPYING = ImageState.COPYING
DELETING = ImageState.DELETING
CREATING = ImageState.CREATING
IMPORTING = ImageState.IMPORTING
VALIDATING = ImageState.VALIDATING
INTERNAL_ERROR = ImageStateChangeReasonCode.INTERNAL_ERROR
IMAGE_BUILDER_NOT_AVAILABLE = ImageStateChangeReasonCode.IMAGE_BUILDER_NOT_AVAILABLE
IMAGE_COPY_FAILURE = ImageStateChangeReasonCode.IMAGE_COPY_FAILURE
IMAGE_UPDATE_FAILURE = ImageStateChangeReasonCode.IMAGE_UPDATE_FAILURE
IMAGE_IMPORT_FAILURE = ImageStateChangeReasonCode.IMAGE_IMPORT_FAILURE
CUSTOM = ImageType.CUSTOM
NATIVE = ImageType.NATIVE
TRUE = LatestAppstreamAgentVersion.TRUE
FALSE = LatestAppstreamAgentVersion.FALSE
SUPPRESS = MessageAction.SUPPRESS
RESEND = MessageAction.RESEND
CUSTOM = PackagingType.CUSTOM
APPSTREAM2 = PackagingType.APPSTREAM2
ENABLED = Permission.ENABLED
DISABLED = Permission.DISABLED
WINDOWS = PlatformType.WINDOWS
WINDOWS_SERVER_2016 = PlatformType.WINDOWS_SERVER_2016
WINDOWS_SERVER_2019 = PlatformType.WINDOWS_SERVER_2019
WINDOWS_SERVER_2022 = PlatformType.WINDOWS_SERVER_2022
AMAZON_LINUX2 = PlatformType.AMAZON_LINUX2
RHEL8 = PlatformType.RHEL8
ROCKY_LINUX8 = PlatformType.ROCKY_LINUX8
TCP = PreferredProtocol.TCP
UDP = PreferredProtocol.UDP
CONNECTED = SessionConnectionState.CONNECTED
NOT_CONNECTED = SessionConnectionState.NOT_CONNECTED
ACTIVE = SessionState.ACTIVE
PENDING = SessionState.PENDING
EXPIRED = SessionState.EXPIRED
STAGED_FOR_INSTALLATION = SoftwareDeploymentStatus.STAGED_FOR_INSTALLATION
PENDING_INSTALLATION = SoftwareDeploymentStatus.PENDING_INSTALLATION
INSTALLED = SoftwareDeploymentStatus.INSTALLED
STAGED_FOR_UNINSTALLATION = SoftwareDeploymentStatus.STAGED_FOR_UNINSTALLATION
PENDING_UNINSTALLATION = SoftwareDeploymentStatus.PENDING_UNINSTALLATION
FAILED_TO_INSTALL = SoftwareDeploymentStatus.FAILED_TO_INSTALL
FAILED_TO_UNINSTALL = SoftwareDeploymentStatus.FAILED_TO_UNINSTALL
STORAGE_CONNECTORS = StackAttribute.STORAGE_CONNECTORS
STORAGE_CONNECTOR_HOMEFOLDERS = StackAttribute.STORAGE_CONNECTOR_HOMEFOLDERS
STORAGE_CONNECTOR_GOOGLE_DRIVE = StackAttribute.STORAGE_CONNECTOR_GOOGLE_DRIVE
STORAGE_CONNECTOR_ONE_DRIVE = StackAttribute.STORAGE_CONNECTOR_ONE_DRIVE
REDIRECT_URL = StackAttribute.REDIRECT_URL
FEEDBACK_URL = StackAttribute.FEEDBACK_URL
THEME_NAME = StackAttribute.THEME_NAME
USER_SETTINGS = StackAttribute.USER_SETTINGS
EMBED_HOST_DOMAINS = StackAttribute.EMBED_HOST_DOMAINS
IAM_ROLE_ARN = StackAttribute.IAM_ROLE_ARN
ACCESS_ENDPOINTS = StackAttribute.ACCESS_ENDPOINTS
STREAMING_EXPERIENCE_SETTINGS = StackAttribute.STREAMING_EXPERIENCE_SETTINGS
STORAGE_CONNECTOR_ERROR = StackErrorCode.STORAGE_CONNECTOR_ERROR
INTERNAL_SERVICE_ERROR = StackErrorCode.INTERNAL_SERVICE_ERROR
HOMEFOLDERS = StorageConnectorType.HOMEFOLDERS
GOOGLE_DRIVE = StorageConnectorType.GOOGLE_DRIVE
ONE_DRIVE = StorageConnectorType.ONE_DRIVE
APP = StreamView.APP
DESKTOP = StreamView.DESKTOP
FOOTER_LINKS = ThemeAttribute.FOOTER_LINKS
ENABLED = ThemeState.ENABLED
DISABLED = ThemeState.DISABLED
LIGHT_BLUE = ThemeStyling.LIGHT_BLUE
BLUE = ThemeStyling.BLUE
PINK = ThemeStyling.PINK
RED = ThemeStyling.RED
RESOURCE_NOT_FOUND = UsageReportExecutionErrorCode.RESOURCE_NOT_FOUND
ACCESS_DENIED = UsageReportExecutionErrorCode.ACCESS_DENIED
INTERNAL_SERVICE_ERROR = UsageReportExecutionErrorCode.INTERNAL_SERVICE_ERROR
DAILY = UsageReportSchedule.DAILY
STACK_NOT_FOUND = UserStackAssociationErrorCode.STACK_NOT_FOUND
USER_NAME_NOT_FOUND = UserStackAssociationErrorCode.USER_NAME_NOT_FOUND
DIRECTORY_NOT_FOUND = UserStackAssociationErrorCode.DIRECTORY_NOT_FOUND
INTERNAL_ERROR = UserStackAssociationErrorCode.INTERNAL_ERROR
PUBLIC = VisibilityType.PUBLIC
PRIVATE = VisibilityType.PRIVATE
SHARED = VisibilityType.SHARED


# PropertyType submodules (e.g., ec2.instance.NetworkInterface)
from . import app_block
from . import app_block_builder
from . import application
from . import directory_config
from . import entitlement
from . import fleet
from . import image_builder
from . import stack


@dataclass
class AppBlock(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appst"""

    resource_type: ClassVar[str] = "AWS::AppStream::AppBlock"
    SETUP_SCRIPT_DETAILS = "SetupScriptDetails"
    DESCRIPTION = "Description"
    POST_SETUP_SCRIPT_DETAILS = "PostSetupScriptDetails"
    DISPLAY_NAME = "DisplayName"
    SOURCE_S3_LOCATION = "SourceS3Location"
    TAGS = "Tags"
    PACKAGING_TYPE = "PackagingType"
    NAME = "Name"

    _property_mappings: ClassVar[dict[str, str]] = {
        "setup_script_details": "SetupScriptDetails",
        "description": "Description",
        "post_setup_script_details": "PostSetupScriptDetails",
        "display_name": "DisplayName",
        "source_s3_location": "SourceS3Location",
        "tags": "Tags",
        "packaging_type": "PackagingType",
        "name": "Name",
    }

    setup_script_details: Optional[app_block.ScriptDetails] = None
    description: Optional[Union[str, Ref, GetAtt, Sub]] = None
    post_setup_script_details: Optional[app_block.ScriptDetails] = None
    display_name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    source_s3_location: Optional[app_block.S3Location] = None
    tags: Optional[list[app_block.Tag]] = None
    packaging_type: Optional[Union[str, PackagingType, Ref, GetAtt, Sub]] = None
    name: Optional[Union[str, Ref, GetAtt, Sub]] = None

    @property
    def attr_created_time(self) -> GetAtt:
        """Get the CreatedTime attribute."""
        return self.get_att("CreatedTime")

    @property
    def attr_arn(self) -> GetAtt:
        """Get the Arn attribute."""
        return self.get_att("Arn")



@dataclass
class AppBlockBuilder(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appst"""

    resource_type: ClassVar[str] = "AWS::AppStream::AppBlockBuilder"
    DESCRIPTION = "Description"
    PLATFORM = "Platform"
    VPC_CONFIG = "VpcConfig"
    APP_BLOCK_ARNS = "AppBlockArns"
    ENABLE_DEFAULT_INTERNET_ACCESS = "EnableDefaultInternetAccess"
    DISPLAY_NAME = "DisplayName"
    IAM_ROLE_ARN = "IamRoleArn"
    INSTANCE_TYPE = "InstanceType"
    TAGS = "Tags"
    NAME = "Name"
    ACCESS_ENDPOINTS = "AccessEndpoints"

    _property_mappings: ClassVar[dict[str, str]] = {
        "description": "Description",
        "platform": "Platform",
        "vpc_config": "VpcConfig",
        "app_block_arns": "AppBlockArns",
        "enable_default_internet_access": "EnableDefaultInternetAccess",
        "display_name": "DisplayName",
        "iam_role_arn": "IamRoleArn",
        "instance_type": "InstanceType",
        "tags": "Tags",
        "name": "Name",
        "access_endpoints": "AccessEndpoints",
    }

    description: Optional[Union[str, Ref, GetAtt, Sub]] = None
    platform: Optional[Union[str, AppBlockBuilderPlatformType, Ref, GetAtt, Sub]] = None
    vpc_config: Optional[app_block_builder.VpcConfig] = None
    app_block_arns: Optional[Union[list[str], Ref]] = None
    enable_default_internet_access: Optional[Union[bool, Ref, GetAtt, Sub]] = None
    display_name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    iam_role_arn: Optional[Union[str, Ref, GetAtt, Sub]] = None
    instance_type: Optional[Union[str, Ref, GetAtt, Sub]] = None
    tags: Optional[list[app_block_builder.Tag]] = None
    name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    access_endpoints: Optional[list[app_block_builder.AccessEndpoint]] = None

    @property
    def attr_created_time(self) -> GetAtt:
        """Get the CreatedTime attribute."""
        return self.get_att("CreatedTime")

    @property
    def attr_arn(self) -> GetAtt:
        """Get the Arn attribute."""
        return self.get_att("Arn")



@dataclass
class Application(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appst"""

    resource_type: ClassVar[str] = "AWS::AppStream::Application"
    WORKING_DIRECTORY = "WorkingDirectory"
    PLATFORMS = "Platforms"
    APP_BLOCK_ARN = "AppBlockArn"
    DESCRIPTION = "Description"
    INSTANCE_FAMILIES = "InstanceFamilies"
    ATTRIBUTES_TO_DELETE = "AttributesToDelete"
    DISPLAY_NAME = "DisplayName"
    LAUNCH_PATH = "LaunchPath"
    LAUNCH_PARAMETERS = "LaunchParameters"
    TAGS = "Tags"
    NAME = "Name"
    ICON_S3_LOCATION = "IconS3Location"

    _property_mappings: ClassVar[dict[str, str]] = {
        "working_directory": "WorkingDirectory",
        "platforms": "Platforms",
        "app_block_arn": "AppBlockArn",
        "description": "Description",
        "instance_families": "InstanceFamilies",
        "attributes_to_delete": "AttributesToDelete",
        "display_name": "DisplayName",
        "launch_path": "LaunchPath",
        "launch_parameters": "LaunchParameters",
        "tags": "Tags",
        "name": "Name",
        "icon_s3_location": "IconS3Location",
    }

    working_directory: Optional[Union[str, Ref, GetAtt, Sub]] = None
    platforms: Optional[Union[list[str], Ref]] = None
    app_block_arn: Optional[Union[str, Ref, GetAtt, Sub]] = None
    description: Optional[Union[str, Ref, GetAtt, Sub]] = None
    instance_families: Optional[Union[list[str], Ref]] = None
    attributes_to_delete: Optional[Union[list[str], Ref]] = None
    display_name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    launch_path: Optional[Union[str, Ref, GetAtt, Sub]] = None
    launch_parameters: Optional[Union[str, Ref, GetAtt, Sub]] = None
    tags: Optional[list[application.Tag]] = None
    name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    icon_s3_location: Optional[application.S3Location] = None

    @property
    def attr_created_time(self) -> GetAtt:
        """Get the CreatedTime attribute."""
        return self.get_att("CreatedTime")

    @property
    def attr_arn(self) -> GetAtt:
        """Get the Arn attribute."""
        return self.get_att("Arn")



@dataclass
class ApplicationEntitlementAssociation(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appst"""

    resource_type: ClassVar[str] = "AWS::AppStream::ApplicationEntitlementAssociation"
    ENTITLEMENT_NAME = "EntitlementName"
    APPLICATION_IDENTIFIER = "ApplicationIdentifier"
    STACK_NAME = "StackName"

    _property_mappings: ClassVar[dict[str, str]] = {
        "entitlement_name": "EntitlementName",
        "application_identifier": "ApplicationIdentifier",
        "stack_name": "StackName",
    }

    entitlement_name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    application_identifier: Optional[Union[str, Ref, GetAtt, Sub]] = None
    stack_name: Optional[Union[str, Ref, GetAtt, Sub]] = None


@dataclass
class ApplicationFleetAssociation(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appst"""

    resource_type: ClassVar[str] = "AWS::AppStream::ApplicationFleetAssociation"
    FLEET_NAME = "FleetName"
    APPLICATION_ARN = "ApplicationArn"

    _property_mappings: ClassVar[dict[str, str]] = {
        "fleet_name": "FleetName",
        "application_arn": "ApplicationArn",
    }

    fleet_name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    application_arn: Optional[Union[str, Ref, GetAtt, Sub]] = None


@dataclass
class DirectoryConfig(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appst"""

    resource_type: ClassVar[str] = "AWS::AppStream::DirectoryConfig"
    ORGANIZATIONAL_UNIT_DISTINGUISHED_NAMES = "OrganizationalUnitDistinguishedNames"
    SERVICE_ACCOUNT_CREDENTIALS = "ServiceAccountCredentials"
    CERTIFICATE_BASED_AUTH_PROPERTIES = "CertificateBasedAuthProperties"
    DIRECTORY_NAME = "DirectoryName"

    _property_mappings: ClassVar[dict[str, str]] = {
        "organizational_unit_distinguished_names": "OrganizationalUnitDistinguishedNames",
        "service_account_credentials": "ServiceAccountCredentials",
        "certificate_based_auth_properties": "CertificateBasedAuthProperties",
        "directory_name": "DirectoryName",
    }

    organizational_unit_distinguished_names: Optional[Union[list[str], Ref]] = None
    service_account_credentials: Optional[directory_config.ServiceAccountCredentials] = None
    certificate_based_auth_properties: Optional[directory_config.CertificateBasedAuthProperties] = None
    directory_name: Optional[Union[str, Ref, GetAtt, Sub]] = None


@dataclass
class Entitlement(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appst"""

    resource_type: ClassVar[str] = "AWS::AppStream::Entitlement"
    APP_VISIBILITY = "AppVisibility"
    DESCRIPTION = "Description"
    ATTRIBUTES = "Attributes"
    STACK_NAME = "StackName"
    NAME = "Name"

    _property_mappings: ClassVar[dict[str, str]] = {
        "app_visibility": "AppVisibility",
        "description": "Description",
        "attributes": "Attributes",
        "stack_name": "StackName",
        "name": "Name",
    }

    app_visibility: Optional[Union[str, AppVisibility, Ref, GetAtt, Sub]] = None
    description: Optional[Union[str, Ref, GetAtt, Sub]] = None
    attributes: Optional[list[entitlement.Attribute]] = None
    stack_name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    name: Optional[Union[str, Ref, GetAtt, Sub]] = None

    @property
    def attr_created_time(self) -> GetAtt:
        """Get the CreatedTime attribute."""
        return self.get_att("CreatedTime")

    @property
    def attr_last_modified_time(self) -> GetAtt:
        """Get the LastModifiedTime attribute."""
        return self.get_att("LastModifiedTime")



@dataclass
class Fleet(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appst"""

    resource_type: ClassVar[str] = "AWS::AppStream::Fleet"
    DESCRIPTION = "Description"
    COMPUTE_CAPACITY = "ComputeCapacity"
    PLATFORM = "Platform"
    VPC_CONFIG = "VpcConfig"
    FLEET_TYPE = "FleetType"
    ENABLE_DEFAULT_INTERNET_ACCESS = "EnableDefaultInternetAccess"
    DOMAIN_JOIN_INFO = "DomainJoinInfo"
    SESSION_SCRIPT_S3_LOCATION = "SessionScriptS3Location"
    NAME = "Name"
    IMAGE_NAME = "ImageName"
    MAX_USER_DURATION_IN_SECONDS = "MaxUserDurationInSeconds"
    IDLE_DISCONNECT_TIMEOUT_IN_SECONDS = "IdleDisconnectTimeoutInSeconds"
    USB_DEVICE_FILTER_STRINGS = "UsbDeviceFilterStrings"
    DISCONNECT_TIMEOUT_IN_SECONDS = "DisconnectTimeoutInSeconds"
    DISPLAY_NAME = "DisplayName"
    STREAM_VIEW = "StreamView"
    IAM_ROLE_ARN = "IamRoleArn"
    MAX_SESSIONS_PER_INSTANCE = "MaxSessionsPerInstance"
    INSTANCE_TYPE = "InstanceType"
    MAX_CONCURRENT_SESSIONS = "MaxConcurrentSessions"
    TAGS = "Tags"
    IMAGE_ARN = "ImageArn"

    _property_mappings: ClassVar[dict[str, str]] = {
        "description": "Description",
        "compute_capacity": "ComputeCapacity",
        "platform": "Platform",
        "vpc_config": "VpcConfig",
        "fleet_type": "FleetType",
        "enable_default_internet_access": "EnableDefaultInternetAccess",
        "domain_join_info": "DomainJoinInfo",
        "session_script_s3_location": "SessionScriptS3Location",
        "name": "Name",
        "image_name": "ImageName",
        "max_user_duration_in_seconds": "MaxUserDurationInSeconds",
        "idle_disconnect_timeout_in_seconds": "IdleDisconnectTimeoutInSeconds",
        "usb_device_filter_strings": "UsbDeviceFilterStrings",
        "disconnect_timeout_in_seconds": "DisconnectTimeoutInSeconds",
        "display_name": "DisplayName",
        "stream_view": "StreamView",
        "iam_role_arn": "IamRoleArn",
        "max_sessions_per_instance": "MaxSessionsPerInstance",
        "instance_type": "InstanceType",
        "max_concurrent_sessions": "MaxConcurrentSessions",
        "tags": "Tags",
        "image_arn": "ImageArn",
    }

    description: Optional[Union[str, Ref, GetAtt, Sub]] = None
    compute_capacity: Optional[fleet.ComputeCapacity] = None
    platform: Optional[Union[str, PlatformType, Ref, GetAtt, Sub]] = None
    vpc_config: Optional[fleet.VpcConfig] = None
    fleet_type: Optional[Union[str, FleetType, Ref, GetAtt, Sub]] = None
    enable_default_internet_access: Optional[Union[bool, Ref, GetAtt, Sub]] = None
    domain_join_info: Optional[fleet.DomainJoinInfo] = None
    session_script_s3_location: Optional[fleet.S3Location] = None
    name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    image_name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    max_user_duration_in_seconds: Optional[Union[int, Ref, GetAtt, Sub]] = None
    idle_disconnect_timeout_in_seconds: Optional[Union[int, Ref, GetAtt, Sub]] = None
    usb_device_filter_strings: Optional[Union[list[str], Ref]] = None
    disconnect_timeout_in_seconds: Optional[Union[int, Ref, GetAtt, Sub]] = None
    display_name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    stream_view: Optional[Union[str, StreamView, Ref, GetAtt, Sub]] = None
    iam_role_arn: Optional[Union[str, Ref, GetAtt, Sub]] = None
    max_sessions_per_instance: Optional[Union[int, Ref, GetAtt, Sub]] = None
    instance_type: Optional[Union[str, Ref, GetAtt, Sub]] = None
    max_concurrent_sessions: Optional[Union[int, Ref, GetAtt, Sub]] = None
    tags: Optional[list[fleet.Tag]] = None
    image_arn: Optional[Union[str, Ref, GetAtt, Sub]] = None


@dataclass
class ImageBuilder(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appst"""

    resource_type: ClassVar[str] = "AWS::AppStream::ImageBuilder"
    DESCRIPTION = "Description"
    VPC_CONFIG = "VpcConfig"
    ENABLE_DEFAULT_INTERNET_ACCESS = "EnableDefaultInternetAccess"
    DOMAIN_JOIN_INFO = "DomainJoinInfo"
    APPSTREAM_AGENT_VERSION = "AppstreamAgentVersion"
    NAME = "Name"
    IMAGE_NAME = "ImageName"
    DISPLAY_NAME = "DisplayName"
    IAM_ROLE_ARN = "IamRoleArn"
    INSTANCE_TYPE = "InstanceType"
    TAGS = "Tags"
    IMAGE_ARN = "ImageArn"
    ACCESS_ENDPOINTS = "AccessEndpoints"

    _property_mappings: ClassVar[dict[str, str]] = {
        "description": "Description",
        "vpc_config": "VpcConfig",
        "enable_default_internet_access": "EnableDefaultInternetAccess",
        "domain_join_info": "DomainJoinInfo",
        "appstream_agent_version": "AppstreamAgentVersion",
        "name": "Name",
        "image_name": "ImageName",
        "display_name": "DisplayName",
        "iam_role_arn": "IamRoleArn",
        "instance_type": "InstanceType",
        "tags": "Tags",
        "image_arn": "ImageArn",
        "access_endpoints": "AccessEndpoints",
    }

    description: Optional[Union[str, Ref, GetAtt, Sub]] = None
    vpc_config: Optional[image_builder.VpcConfig] = None
    enable_default_internet_access: Optional[Union[bool, Ref, GetAtt, Sub]] = None
    domain_join_info: Optional[image_builder.DomainJoinInfo] = None
    appstream_agent_version: Optional[Union[str, Ref, GetAtt, Sub]] = None
    name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    image_name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    display_name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    iam_role_arn: Optional[Union[str, Ref, GetAtt, Sub]] = None
    instance_type: Optional[Union[str, Ref, GetAtt, Sub]] = None
    tags: Optional[list[image_builder.Tag]] = None
    image_arn: Optional[Union[str, Ref, GetAtt, Sub]] = None
    access_endpoints: Optional[list[image_builder.AccessEndpoint]] = None

    @property
    def attr_streaming_url(self) -> GetAtt:
        """Get the StreamingUrl attribute."""
        return self.get_att("StreamingUrl")



@dataclass
class Stack(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appst"""

    resource_type: ClassVar[str] = "AWS::AppStream::Stack"
    DESCRIPTION = "Description"
    STORAGE_CONNECTORS = "StorageConnectors"
    DELETE_STORAGE_CONNECTORS = "DeleteStorageConnectors"
    EMBED_HOST_DOMAINS = "EmbedHostDomains"
    USER_SETTINGS = "UserSettings"
    ATTRIBUTES_TO_DELETE = "AttributesToDelete"
    REDIRECT_URL = "RedirectURL"
    STREAMING_EXPERIENCE_SETTINGS = "StreamingExperienceSettings"
    NAME = "Name"
    FEEDBACK_URL = "FeedbackURL"
    APPLICATION_SETTINGS = "ApplicationSettings"
    DISPLAY_NAME = "DisplayName"
    TAGS = "Tags"
    ACCESS_ENDPOINTS = "AccessEndpoints"

    _property_mappings: ClassVar[dict[str, str]] = {
        "description": "Description",
        "storage_connectors": "StorageConnectors",
        "delete_storage_connectors": "DeleteStorageConnectors",
        "embed_host_domains": "EmbedHostDomains",
        "user_settings": "UserSettings",
        "attributes_to_delete": "AttributesToDelete",
        "redirect_url": "RedirectURL",
        "streaming_experience_settings": "StreamingExperienceSettings",
        "name": "Name",
        "feedback_url": "FeedbackURL",
        "application_settings": "ApplicationSettings",
        "display_name": "DisplayName",
        "tags": "Tags",
        "access_endpoints": "AccessEndpoints",
    }

    description: Optional[Union[str, Ref, GetAtt, Sub]] = None
    storage_connectors: Optional[list[stack.StorageConnector]] = None
    delete_storage_connectors: Optional[Union[bool, Ref, GetAtt, Sub]] = None
    embed_host_domains: Optional[Union[list[str], Ref]] = None
    user_settings: Optional[list[stack.UserSetting]] = None
    attributes_to_delete: Optional[Union[list[str], Ref]] = None
    redirect_url: Optional[Union[str, Ref, GetAtt, Sub]] = None
    streaming_experience_settings: Optional[stack.StreamingExperienceSettings] = None
    name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    feedback_url: Optional[Union[str, Ref, GetAtt, Sub]] = None
    application_settings: Optional[stack.ApplicationSettings] = None
    display_name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    tags: Optional[list[stack.Tag]] = None
    access_endpoints: Optional[list[stack.AccessEndpoint]] = None


@dataclass
class StackFleetAssociation(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appst"""

    resource_type: ClassVar[str] = "AWS::AppStream::StackFleetAssociation"
    FLEET_NAME = "FleetName"
    STACK_NAME = "StackName"

    _property_mappings: ClassVar[dict[str, str]] = {
        "fleet_name": "FleetName",
        "stack_name": "StackName",
    }

    fleet_name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    stack_name: Optional[Union[str, Ref, GetAtt, Sub]] = None


@dataclass
class StackUserAssociation(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appst"""

    resource_type: ClassVar[str] = "AWS::AppStream::StackUserAssociation"
    SEND_EMAIL_NOTIFICATION = "SendEmailNotification"
    USER_NAME = "UserName"
    STACK_NAME = "StackName"
    AUTHENTICATION_TYPE = "AuthenticationType"

    _property_mappings: ClassVar[dict[str, str]] = {
        "send_email_notification": "SendEmailNotification",
        "user_name": "UserName",
        "stack_name": "StackName",
        "authentication_type": "AuthenticationType",
    }

    send_email_notification: Optional[Union[bool, Ref, GetAtt, Sub]] = None
    user_name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    stack_name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    authentication_type: Optional[Union[str, Ref, GetAtt, Sub]] = None


@dataclass
class User(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appst"""

    resource_type: ClassVar[str] = "AWS::AppStream::User"
    USER_NAME = "UserName"
    FIRST_NAME = "FirstName"
    MESSAGE_ACTION = "MessageAction"
    LAST_NAME = "LastName"
    AUTHENTICATION_TYPE = "AuthenticationType"

    _property_mappings: ClassVar[dict[str, str]] = {
        "user_name": "UserName",
        "first_name": "FirstName",
        "message_action": "MessageAction",
        "last_name": "LastName",
        "authentication_type": "AuthenticationType",
    }

    user_name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    first_name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    message_action: Optional[Union[str, Ref, GetAtt, Sub]] = None
    last_name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    authentication_type: Optional[Union[str, AuthenticationType, Ref, GetAtt, Sub]] = None

