"""Generated by cfn-dataclasses-import."""

from cloudformation_dataclasses.core import (
    Condition,
    Output,
    Parameter,
    ParameterType,
    STRING,
    Template,
    cloudformation_dataclass,
    get_att,
    ref,
)
from cloudformation_dataclasses.aws import directoryservice
from cloudformation_dataclasses.intrinsics import Equals, Select

from .stack import *  # noqa: F403, F401

__all__ = [
    "AliasCondition",
    "Condition",
    "CreateAlias",
    "DirectoryAliasOutput",
    "DirectoryIDOutput",
    "DomainName",
    "Equals",
    "Output",
    "Parameter",
    "ParameterType",
    "PrimaryDNSOutput",
    "PrivateSubnet1",
    "PrivateSubnet2",
    "STRING",
    "SecondaryDNSOutput",
    "Select",
    "SimpleAD",
    "SimpleADShortName",
    "Size",
    "Template",
    "VPCID",
    "cloudformation_dataclass",
    "directoryservice",
    "get_att",
    "ref",
]
