"""CodePipeline for continuous integration build and continuous deployment

Generated by cfn-dataclasses-import."""

from cloudformation_dataclasses.core import (
    Parameter,
    PolicyDocument,
    PolicyStatement,
    STRING,
    Template,
    cloudformation_dataclass,
    get_att,
    ref,
)
from cloudformation_dataclasses.core.resource_loader import setup_resources
from cloudformation_dataclasses.aws import codepipeline, events, iam
from cloudformation_dataclasses.intrinsics import (
    AWS_ACCOUNT_ID,
    AWS_REGION,
    ImportValue,
    Join,
    Sub,
)

from .params import *  # noqa: F403, F401

# Auto-discover and import resource files in topological order
setup_resources(__file__, __name__, globals())

__all__ = [
    "AWS_ACCOUNT_ID",
    "AWS_REGION",
    "CodeBuildStack",
    "EventRole",
    "EventRule",
    "ImportValue",
    "Join",
    "Parameter",
    "Pipeline",
    "PipelineRole",
    "PolicyDocument",
    "PolicyStatement",
    "STRING",
    "Sub",
    "Template",
    "cloudformation_dataclass",
    "codepipeline",
    "events",
    "get_att",
    "iam",
    "ref",
]
