"""Template to install CloudWatchAgent on centos. It was validated on centos 7

Generated by cfn-dataclasses-import."""

from cloudformation_dataclasses.core import (
    Mapping,
    Parameter,
    ParameterType,
    STRING,
    Template,
    cloudformation_dataclass,
    get_att,
    ref,
)
from cloudformation_dataclasses.aws import ec2
from cloudformation_dataclasses.intrinsics import (
    AWS_REGION,
    Base64,
    FindInMap,
    Sub,
)

from .stack_config import (
    CentOSVersion,
    IAMRole,
    InstanceType,
    KeyName,
    RegionMapMapping,
    SSHLocation,
    SubnetId,
)

from .resources import *  # noqa: F403, F401

__all__ = [
    "AWS_REGION",
    "Base64",
    "CentOSVersion",
    "EC2Instance",
    "FindInMap",
    "IAMRole",
    "InstanceSecurityGroup",
    "InstanceType",
    "KeyName",
    "Mapping",
    "Parameter",
    "ParameterType",
    "RegionMapMapping",
    "SSHLocation",
    "STRING",
    "Sub",
    "SubnetId",
    "Template",
    "cloudformation_dataclass",
    "ec2",
    "get_att",
    "ref",
]
