AWSTemplateFormatVersion: '2010-09-09'
Description: S3 bucket with encryption-required policy

Resources:
  MyData:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: DataClassification
          Value: sensitive

  MyDataPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref MyData
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Deny
            Sid: DenyUnencryptedObjectUploads
            Principal: '*'
            Action: s3:PutObject
            Resource: !Sub ${MyData.Arn}/*
            Condition:
              StringNotEquals:
                s3:x-amz-server-side-encryption: AES256
