"""A stack for deploying containerized applications in AWS Fargate. This stack runs containers in a public VPC subnet, and includes a public facing load balancer to register the services in.

Generated by cfn-dataclasses-import."""

from cloudformation_dataclasses.core import (
    Mapping,
    Output,
    PolicyDocument,
    PolicyStatement,
    Template,
    cloudformation_dataclass,
    get_att,
    ref,
)
from cloudformation_dataclasses.aws import (
    ec2,
    ecs,
    elasticloadbalancingv2,
    iam,
)
from cloudformation_dataclasses.intrinsics import (
    AWS_REGION,
    AWS_STACK_NAME,
    FindInMap,
    GetAZs,
    Join,
    Select,
)

from .stack_config import SubnetConfigMapping

from .resources import *  # noqa: F403, F401

__all__ = [
    "AWS_REGION",
    "AWS_STACK_NAME",
    "DummyTargetGroupPublic",
    "ECSCluster",
    "ECSRole",
    "ECSTaskExecutionRole",
    "EcsSecurityGroupIngressFromPublicALB",
    "EcsSecurityGroupIngressFromSelf",
    "FargateContainerSecurityGroup",
    "FindInMap",
    "GatewayAttachement",
    "GetAZs",
    "InternetGateway",
    "Join",
    "Mapping",
    "Output",
    "PolicyDocument",
    "PolicyStatement",
    "PublicLoadBalancer",
    "PublicLoadBalancerListener",
    "PublicLoadBalancerSG",
    "PublicRoute",
    "PublicRouteTable",
    "PublicSubnetOne",
    "PublicSubnetOneRouteTableAssociation",
    "PublicSubnetTwo",
    "PublicSubnetTwoRouteTableAssociation",
    "Select",
    "SubnetConfigMapping",
    "Template",
    "VPC",
    "cloudformation_dataclass",
    "ec2",
    "ecs",
    "elasticloadbalancingv2",
    "get_att",
    "iam",
    "ref",
]
