"""
AWS CloudFormation AppMesh Resources

⚠️  AUTO-GENERATED FILE - DO NOT EDIT MANUALLY ⚠️

This file is automatically generated from the AWS CloudFormation Resource Specification.
Any manual changes will be overwritten when regenerated.

Version Information:
  CloudFormation Spec: 2025.12.11
  Generator Version: 1.0.0
  Combined: spec-2025.12.11_gen-1.0.0
  Generated: 2025-12-17 21:43:29

To regenerate this file:
    uv run python -m cloudformation_dataclasses.codegen.generator --service AppMesh
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, ClassVar, Optional, Union

from cloudformation_dataclasses.core.base import CloudFormationResource, PropertyType
from cloudformation_dataclasses.intrinsics.functions import GetAtt, Ref, Sub


# =============================================================================
# Service Constants (auto-generated from botocore)
# =============================================================================

class DefaultGatewayRouteRewrite:
    """DefaultGatewayRouteRewrite enum values."""

    ENABLED = "ENABLED"
    DISABLED = "DISABLED"


class DnsResponseType:
    """DnsResponseType enum values."""

    LOADBALANCER = "LOADBALANCER"
    ENDPOINTS = "ENDPOINTS"


class DurationUnit:
    """DurationUnit enum values."""

    S = "s"
    MS = "ms"


class EgressFilterType:
    """EgressFilterType enum values."""

    ALLOW_ALL = "ALLOW_ALL"
    DROP_ALL = "DROP_ALL"


class GatewayRouteStatusCode:
    """GatewayRouteStatusCode enum values."""

    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    DELETED = "DELETED"


class GrpcRetryPolicyEvent:
    """GrpcRetryPolicyEvent enum values."""

    CANCELLED = "cancelled"
    DEADLINE_EXCEEDED = "deadline-exceeded"
    INTERNAL = "internal"
    RESOURCE_EXHAUSTED = "resource-exhausted"
    UNAVAILABLE = "unavailable"


class HttpMethod:
    """HttpMethod enum values."""

    GET = "GET"
    HEAD = "HEAD"
    POST = "POST"
    PUT = "PUT"
    DELETE = "DELETE"
    CONNECT = "CONNECT"
    OPTIONS = "OPTIONS"
    TRACE = "TRACE"
    PATCH = "PATCH"


class HttpScheme:
    """HttpScheme enum values."""

    HTTP = "http"
    HTTPS = "https"


class IpPreference:
    """IpPreference enum values."""

    IPV6_PREFERRED = "IPv6_PREFERRED"
    IPV4_PREFERRED = "IPv4_PREFERRED"
    IPV4_ONLY = "IPv4_ONLY"
    IPV6_ONLY = "IPv6_ONLY"


class ListenerTlsMode:
    """ListenerTlsMode enum values."""

    STRICT = "STRICT"
    PERMISSIVE = "PERMISSIVE"
    DISABLED = "DISABLED"


class MeshStatusCode:
    """MeshStatusCode enum values."""

    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    DELETED = "DELETED"


class PortProtocol:
    """PortProtocol enum values."""

    HTTP = "http"
    TCP = "tcp"
    HTTP2 = "http2"
    GRPC = "grpc"


class RouteStatusCode:
    """RouteStatusCode enum values."""

    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    DELETED = "DELETED"


class TcpRetryPolicyEvent:
    """TcpRetryPolicyEvent enum values."""

    CONNECTION_ERROR = "connection-error"


class VirtualGatewayListenerTlsMode:
    """VirtualGatewayListenerTlsMode enum values."""

    STRICT = "STRICT"
    PERMISSIVE = "PERMISSIVE"
    DISABLED = "DISABLED"


class VirtualGatewayPortProtocol:
    """VirtualGatewayPortProtocol enum values."""

    HTTP = "http"
    HTTP2 = "http2"
    GRPC = "grpc"


class VirtualGatewayStatusCode:
    """VirtualGatewayStatusCode enum values."""

    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    DELETED = "DELETED"


class VirtualNodeStatusCode:
    """VirtualNodeStatusCode enum values."""

    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    DELETED = "DELETED"


class VirtualRouterStatusCode:
    """VirtualRouterStatusCode enum values."""

    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    DELETED = "DELETED"


class VirtualServiceStatusCode:
    """VirtualServiceStatusCode enum values."""

    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    DELETED = "DELETED"


# Convenient aliases for enum values
ENABLED = DefaultGatewayRouteRewrite.ENABLED
DISABLED = DefaultGatewayRouteRewrite.DISABLED
LOADBALANCER = DnsResponseType.LOADBALANCER
ENDPOINTS = DnsResponseType.ENDPOINTS
S = DurationUnit.S
MS = DurationUnit.MS
ALLOW_ALL = EgressFilterType.ALLOW_ALL
DROP_ALL = EgressFilterType.DROP_ALL
ACTIVE = GatewayRouteStatusCode.ACTIVE
INACTIVE = GatewayRouteStatusCode.INACTIVE
DELETED = GatewayRouteStatusCode.DELETED
CANCELLED = GrpcRetryPolicyEvent.CANCELLED
DEADLINE_EXCEEDED = GrpcRetryPolicyEvent.DEADLINE_EXCEEDED
INTERNAL = GrpcRetryPolicyEvent.INTERNAL
RESOURCE_EXHAUSTED = GrpcRetryPolicyEvent.RESOURCE_EXHAUSTED
UNAVAILABLE = GrpcRetryPolicyEvent.UNAVAILABLE
GET = HttpMethod.GET
HEAD = HttpMethod.HEAD
POST = HttpMethod.POST
PUT = HttpMethod.PUT
DELETE = HttpMethod.DELETE
CONNECT = HttpMethod.CONNECT
OPTIONS = HttpMethod.OPTIONS
TRACE = HttpMethod.TRACE
PATCH = HttpMethod.PATCH
HTTP = HttpScheme.HTTP
HTTPS = HttpScheme.HTTPS
IPV6_PREFERRED = IpPreference.IPV6_PREFERRED
IPV4_PREFERRED = IpPreference.IPV4_PREFERRED
IPV4_ONLY = IpPreference.IPV4_ONLY
IPV6_ONLY = IpPreference.IPV6_ONLY
STRICT = ListenerTlsMode.STRICT
PERMISSIVE = ListenerTlsMode.PERMISSIVE
DISABLED = ListenerTlsMode.DISABLED
ACTIVE = MeshStatusCode.ACTIVE
INACTIVE = MeshStatusCode.INACTIVE
DELETED = MeshStatusCode.DELETED
HTTP = PortProtocol.HTTP
TCP = PortProtocol.TCP
HTTP2 = PortProtocol.HTTP2
GRPC = PortProtocol.GRPC
ACTIVE = RouteStatusCode.ACTIVE
INACTIVE = RouteStatusCode.INACTIVE
DELETED = RouteStatusCode.DELETED
CONNECTION_ERROR = TcpRetryPolicyEvent.CONNECTION_ERROR
STRICT = VirtualGatewayListenerTlsMode.STRICT
PERMISSIVE = VirtualGatewayListenerTlsMode.PERMISSIVE
DISABLED = VirtualGatewayListenerTlsMode.DISABLED
HTTP = VirtualGatewayPortProtocol.HTTP
HTTP2 = VirtualGatewayPortProtocol.HTTP2
GRPC = VirtualGatewayPortProtocol.GRPC
ACTIVE = VirtualGatewayStatusCode.ACTIVE
INACTIVE = VirtualGatewayStatusCode.INACTIVE
DELETED = VirtualGatewayStatusCode.DELETED
ACTIVE = VirtualNodeStatusCode.ACTIVE
INACTIVE = VirtualNodeStatusCode.INACTIVE
DELETED = VirtualNodeStatusCode.DELETED
ACTIVE = VirtualRouterStatusCode.ACTIVE
INACTIVE = VirtualRouterStatusCode.INACTIVE
DELETED = VirtualRouterStatusCode.DELETED
ACTIVE = VirtualServiceStatusCode.ACTIVE
INACTIVE = VirtualServiceStatusCode.INACTIVE
DELETED = VirtualServiceStatusCode.DELETED


@dataclass
class GatewayRouteHostnameMatch(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "suffix": "Suffix",
        "exact": "Exact",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    suffix: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    exact: Optional[Union[str, Ref, GetAtt, Sub]] = None


@dataclass
class GatewayRouteHostnameRewrite(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "default_target_hostname": "DefaultTargetHostname",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    default_target_hostname: Optional[Union[str, Ref, GetAtt, Sub]] = None


@dataclass
class GatewayRouteMetadataMatch(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "suffix": "Suffix",
        "regex": "Regex",
        "exact": "Exact",
        "prefix": "Prefix",
        "range": "Range",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    suffix: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    regex: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    exact: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    prefix: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    range: Optional[GatewayRouteRangeMatch] = None


@dataclass
class GatewayRouteRangeMatch(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "start": "Start",
        "end": "End",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    start: Optional[Union[int, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    end: Optional[Union[int, Ref, GetAtt, Sub]] = None


@dataclass
class GatewayRouteSpec(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "http_route": "HttpRoute",
        "priority": "Priority",
        "http2_route": "Http2Route",
        "grpc_route": "GrpcRoute",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    http_route: Optional[HttpGatewayRoute] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    priority: Optional[Union[int, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    http2_route: Optional[HttpGatewayRoute] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    grpc_route: Optional[GrpcGatewayRoute] = None


@dataclass
class GatewayRouteTarget(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "port": "Port",
        "virtual_service": "VirtualService",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    port: Optional[Union[int, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    virtual_service: Optional[GatewayRouteVirtualService] = None


@dataclass
class GatewayRouteVirtualService(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "virtual_service_name": "VirtualServiceName",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    virtual_service_name: Optional[Union[str, Ref, GetAtt, Sub]] = None


@dataclass
class GrpcGatewayRoute(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "action": "Action",
        "match": "Match",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    action: Optional[GrpcGatewayRouteAction] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    match: Optional[GrpcGatewayRouteMatch] = None


@dataclass
class GrpcGatewayRouteAction(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "target": "Target",
        "rewrite": "Rewrite",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    target: Optional[GatewayRouteTarget] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    rewrite: Optional[GrpcGatewayRouteRewrite] = None


@dataclass
class GrpcGatewayRouteMatch(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "service_name": "ServiceName",
        "port": "Port",
        "hostname": "Hostname",
        "metadata": "Metadata",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    service_name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    port: Optional[Union[int, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    hostname: Optional[GatewayRouteHostnameMatch] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    metadata: Optional[list[GrpcGatewayRouteMetadata]] = None


@dataclass
class GrpcGatewayRouteMetadata(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "invert": "Invert",
        "name": "Name",
        "match": "Match",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    invert: Optional[Union[bool, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    match: Optional[GatewayRouteMetadataMatch] = None


@dataclass
class GrpcGatewayRouteRewrite(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "hostname": "Hostname",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    hostname: Optional[GatewayRouteHostnameRewrite] = None


@dataclass
class HttpGatewayRoute(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "action": "Action",
        "match": "Match",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    action: Optional[HttpGatewayRouteAction] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    match: Optional[HttpGatewayRouteMatch] = None


@dataclass
class HttpGatewayRouteAction(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "target": "Target",
        "rewrite": "Rewrite",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    target: Optional[GatewayRouteTarget] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    rewrite: Optional[HttpGatewayRouteRewrite] = None


@dataclass
class HttpGatewayRouteHeader(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "invert": "Invert",
        "name": "Name",
        "match": "Match",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    invert: Optional[Union[bool, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    match: Optional[HttpGatewayRouteHeaderMatch] = None


@dataclass
class HttpGatewayRouteHeaderMatch(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "suffix": "Suffix",
        "regex": "Regex",
        "exact": "Exact",
        "prefix": "Prefix",
        "range": "Range",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    suffix: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    regex: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    exact: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    prefix: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    range: Optional[GatewayRouteRangeMatch] = None


@dataclass
class HttpGatewayRouteMatch(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "path": "Path",
        "headers": "Headers",
        "port": "Port",
        "hostname": "Hostname",
        "prefix": "Prefix",
        "method": "Method",
        "query_parameters": "QueryParameters",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    path: Optional[HttpPathMatch] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    headers: Optional[list[HttpGatewayRouteHeader]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    port: Optional[Union[int, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    hostname: Optional[GatewayRouteHostnameMatch] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    prefix: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    method: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    query_parameters: Optional[list[QueryParameter]] = None


@dataclass
class HttpGatewayRoutePathRewrite(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "exact": "Exact",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    exact: Optional[Union[str, Ref, GetAtt, Sub]] = None


@dataclass
class HttpGatewayRoutePrefixRewrite(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "value": "Value",
        "default_prefix": "DefaultPrefix",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    value: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    default_prefix: Optional[Union[str, Ref, GetAtt, Sub]] = None


@dataclass
class HttpGatewayRouteRewrite(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "path": "Path",
        "hostname": "Hostname",
        "prefix": "Prefix",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    path: Optional[HttpGatewayRoutePathRewrite] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    hostname: Optional[GatewayRouteHostnameRewrite] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    prefix: Optional[HttpGatewayRoutePrefixRewrite] = None


@dataclass
class HttpPathMatch(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "regex": "Regex",
        "exact": "Exact",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    regex: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    exact: Optional[Union[str, Ref, GetAtt, Sub]] = None


@dataclass
class HttpQueryParameterMatch(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "exact": "Exact",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    exact: Optional[Union[str, Ref, GetAtt, Sub]] = None


@dataclass
class QueryParameter(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "name": "Name",
        "match": "Match",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    match: Optional[HttpQueryParameterMatch] = None


@dataclass
class GatewayRoute(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appme"""

    resource_type: ClassVar[str] = "AWS::AppMesh::GatewayRoute"
    _property_mappings: ClassVar[dict[str, str]] = {
        "mesh_name": "MeshName",
        "virtual_gateway_name": "VirtualGatewayName",
        "mesh_owner": "MeshOwner",
        "gateway_route_name": "GatewayRouteName",
        "spec": "Spec",
        "tags": "Tags",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    mesh_name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    virtual_gateway_name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    mesh_owner: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    gateway_route_name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    spec: Optional[GatewayRouteSpec] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    tags: Optional[list[Tag]] = None

    @property
    def attr_uid(self) -> GetAtt:
        """Get the Uid attribute."""
        return self.get_att("Uid")

    @property
    def attr_mesh_name(self) -> GetAtt:
        """Get the MeshName attribute."""
        return self.get_att("MeshName")

    @property
    def attr_virtual_gateway_name(self) -> GetAtt:
        """Get the VirtualGatewayName attribute."""
        return self.get_att("VirtualGatewayName")

    @property
    def attr_mesh_owner(self) -> GetAtt:
        """Get the MeshOwner attribute."""
        return self.get_att("MeshOwner")

    @property
    def attr_resource_owner(self) -> GetAtt:
        """Get the ResourceOwner attribute."""
        return self.get_att("ResourceOwner")

    @property
    def attr_gateway_route_name(self) -> GetAtt:
        """Get the GatewayRouteName attribute."""
        return self.get_att("GatewayRouteName")

    @property
    def attr_arn(self) -> GetAtt:
        """Get the Arn attribute."""
        return self.get_att("Arn")




@dataclass
class EgressFilter(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "type_": "Type",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    type_: Optional[Union[str, Ref, GetAtt, Sub]] = None


@dataclass
class MeshServiceDiscovery(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "ip_preference": "IpPreference",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    ip_preference: Optional[Union[str, Ref, GetAtt, Sub]] = None


@dataclass
class MeshSpec(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "egress_filter": "EgressFilter",
        "service_discovery": "ServiceDiscovery",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    egress_filter: Optional[EgressFilter] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    service_discovery: Optional[MeshServiceDiscovery] = None


@dataclass
class Mesh(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appme"""

    resource_type: ClassVar[str] = "AWS::AppMesh::Mesh"
    _property_mappings: ClassVar[dict[str, str]] = {
        "mesh_name": "MeshName",
        "spec": "Spec",
        "tags": "Tags",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    mesh_name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    spec: Optional[MeshSpec] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    tags: Optional[list[Tag]] = None

    @property
    def attr_uid(self) -> GetAtt:
        """Get the Uid attribute."""
        return self.get_att("Uid")

    @property
    def attr_mesh_name(self) -> GetAtt:
        """Get the MeshName attribute."""
        return self.get_att("MeshName")

    @property
    def attr_mesh_owner(self) -> GetAtt:
        """Get the MeshOwner attribute."""
        return self.get_att("MeshOwner")

    @property
    def attr_resource_owner(self) -> GetAtt:
        """Get the ResourceOwner attribute."""
        return self.get_att("ResourceOwner")

    @property
    def attr_arn(self) -> GetAtt:
        """Get the Arn attribute."""
        return self.get_att("Arn")




@dataclass
class Duration(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "value": "Value",
        "unit": "Unit",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    value: Optional[Union[int, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    unit: Optional[Union[str, Ref, GetAtt, Sub]] = None


@dataclass
class GrpcRetryPolicy(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "max_retries": "MaxRetries",
        "per_retry_timeout": "PerRetryTimeout",
        "grpc_retry_events": "GrpcRetryEvents",
        "http_retry_events": "HttpRetryEvents",
        "tcp_retry_events": "TcpRetryEvents",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    max_retries: Optional[Union[int, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    per_retry_timeout: Optional[Duration] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    grpc_retry_events: Optional[Union[list[str], Ref]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    http_retry_events: Optional[Union[list[str], Ref]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    tcp_retry_events: Optional[Union[list[str], Ref]] = None


@dataclass
class GrpcRoute(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "action": "Action",
        "timeout": "Timeout",
        "retry_policy": "RetryPolicy",
        "match": "Match",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    action: Optional[GrpcRouteAction] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    timeout: Optional[GrpcTimeout] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    retry_policy: Optional[GrpcRetryPolicy] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    match: Optional[GrpcRouteMatch] = None


@dataclass
class GrpcRouteAction(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "weighted_targets": "WeightedTargets",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    weighted_targets: Optional[list[WeightedTarget]] = None


@dataclass
class GrpcRouteMatch(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "service_name": "ServiceName",
        "port": "Port",
        "metadata": "Metadata",
        "method_name": "MethodName",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    service_name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    port: Optional[Union[int, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    metadata: Optional[list[GrpcRouteMetadata]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    method_name: Optional[Union[str, Ref, GetAtt, Sub]] = None


@dataclass
class GrpcRouteMetadata(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "invert": "Invert",
        "name": "Name",
        "match": "Match",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    invert: Optional[Union[bool, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    match: Optional[GrpcRouteMetadataMatchMethod] = None


@dataclass
class GrpcRouteMetadataMatchMethod(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "suffix": "Suffix",
        "regex": "Regex",
        "exact": "Exact",
        "prefix": "Prefix",
        "range": "Range",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    suffix: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    regex: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    exact: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    prefix: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    range: Optional[MatchRange] = None


@dataclass
class GrpcTimeout(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "per_request": "PerRequest",
        "idle": "Idle",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    per_request: Optional[Duration] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    idle: Optional[Duration] = None


@dataclass
class HeaderMatchMethod(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "suffix": "Suffix",
        "regex": "Regex",
        "exact": "Exact",
        "prefix": "Prefix",
        "range": "Range",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    suffix: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    regex: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    exact: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    prefix: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    range: Optional[MatchRange] = None


@dataclass
class HttpPathMatch(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "regex": "Regex",
        "exact": "Exact",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    regex: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    exact: Optional[Union[str, Ref, GetAtt, Sub]] = None


@dataclass
class HttpQueryParameterMatch(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "exact": "Exact",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    exact: Optional[Union[str, Ref, GetAtt, Sub]] = None


@dataclass
class HttpRetryPolicy(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "max_retries": "MaxRetries",
        "per_retry_timeout": "PerRetryTimeout",
        "http_retry_events": "HttpRetryEvents",
        "tcp_retry_events": "TcpRetryEvents",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    max_retries: Optional[Union[int, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    per_retry_timeout: Optional[Duration] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    http_retry_events: Optional[Union[list[str], Ref]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    tcp_retry_events: Optional[Union[list[str], Ref]] = None


@dataclass
class HttpRoute(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "action": "Action",
        "timeout": "Timeout",
        "retry_policy": "RetryPolicy",
        "match": "Match",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    action: Optional[HttpRouteAction] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    timeout: Optional[HttpTimeout] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    retry_policy: Optional[HttpRetryPolicy] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    match: Optional[HttpRouteMatch] = None


@dataclass
class HttpRouteAction(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "weighted_targets": "WeightedTargets",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    weighted_targets: Optional[list[WeightedTarget]] = None


@dataclass
class HttpRouteHeader(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "invert": "Invert",
        "name": "Name",
        "match": "Match",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    invert: Optional[Union[bool, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    match: Optional[HeaderMatchMethod] = None


@dataclass
class HttpRouteMatch(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "path": "Path",
        "scheme": "Scheme",
        "headers": "Headers",
        "port": "Port",
        "prefix": "Prefix",
        "method": "Method",
        "query_parameters": "QueryParameters",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    path: Optional[HttpPathMatch] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    scheme: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    headers: Optional[list[HttpRouteHeader]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    port: Optional[Union[int, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    prefix: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    method: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    query_parameters: Optional[list[QueryParameter]] = None


@dataclass
class HttpTimeout(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "per_request": "PerRequest",
        "idle": "Idle",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    per_request: Optional[Duration] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    idle: Optional[Duration] = None


@dataclass
class MatchRange(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "start": "Start",
        "end": "End",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    start: Optional[Union[int, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    end: Optional[Union[int, Ref, GetAtt, Sub]] = None


@dataclass
class QueryParameter(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "name": "Name",
        "match": "Match",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    match: Optional[HttpQueryParameterMatch] = None


@dataclass
class RouteSpec(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "http_route": "HttpRoute",
        "priority": "Priority",
        "http2_route": "Http2Route",
        "grpc_route": "GrpcRoute",
        "tcp_route": "TcpRoute",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    http_route: Optional[HttpRoute] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    priority: Optional[Union[int, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    http2_route: Optional[HttpRoute] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    grpc_route: Optional[GrpcRoute] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    tcp_route: Optional[TcpRoute] = None


@dataclass
class TcpRoute(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "action": "Action",
        "timeout": "Timeout",
        "match": "Match",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    action: Optional[TcpRouteAction] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    timeout: Optional[TcpTimeout] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    match: Optional[TcpRouteMatch] = None


@dataclass
class TcpRouteAction(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "weighted_targets": "WeightedTargets",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    weighted_targets: Optional[list[WeightedTarget]] = None


@dataclass
class TcpRouteMatch(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "port": "Port",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    port: Optional[Union[int, Ref, GetAtt, Sub]] = None


@dataclass
class TcpTimeout(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "idle": "Idle",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    idle: Optional[Duration] = None


@dataclass
class WeightedTarget(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "virtual_node": "VirtualNode",
        "port": "Port",
        "weight": "Weight",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    virtual_node: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    port: Optional[Union[int, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    weight: Optional[Union[int, Ref, GetAtt, Sub]] = None


@dataclass
class Route(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appme"""

    resource_type: ClassVar[str] = "AWS::AppMesh::Route"
    _property_mappings: ClassVar[dict[str, str]] = {
        "mesh_name": "MeshName",
        "virtual_router_name": "VirtualRouterName",
        "mesh_owner": "MeshOwner",
        "route_name": "RouteName",
        "spec": "Spec",
        "tags": "Tags",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    mesh_name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    virtual_router_name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    mesh_owner: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    route_name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    spec: Optional[RouteSpec] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    tags: Optional[list[Tag]] = None

    @property
    def attr_uid(self) -> GetAtt:
        """Get the Uid attribute."""
        return self.get_att("Uid")

    @property
    def attr_mesh_name(self) -> GetAtt:
        """Get the MeshName attribute."""
        return self.get_att("MeshName")

    @property
    def attr_virtual_router_name(self) -> GetAtt:
        """Get the VirtualRouterName attribute."""
        return self.get_att("VirtualRouterName")

    @property
    def attr_mesh_owner(self) -> GetAtt:
        """Get the MeshOwner attribute."""
        return self.get_att("MeshOwner")

    @property
    def attr_resource_owner(self) -> GetAtt:
        """Get the ResourceOwner attribute."""
        return self.get_att("ResourceOwner")

    @property
    def attr_route_name(self) -> GetAtt:
        """Get the RouteName attribute."""
        return self.get_att("RouteName")

    @property
    def attr_arn(self) -> GetAtt:
        """Get the Arn attribute."""
        return self.get_att("Arn")




@dataclass
class JsonFormatRef(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "value": "Value",
        "key": "Key",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    value: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    key: Optional[Union[str, Ref, GetAtt, Sub]] = None


@dataclass
class LoggingFormat(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "text": "Text",
        "json": "Json",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    text: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    json: Optional[list[JsonFormatRef]] = None


@dataclass
class SubjectAlternativeNameMatchers(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "exact": "Exact",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    exact: Optional[Union[list[str], Ref]] = None


@dataclass
class SubjectAlternativeNames(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "match": "Match",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    match: Optional[SubjectAlternativeNameMatchers] = None


@dataclass
class VirtualGatewayAccessLog(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "file": "File",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    file: Optional[VirtualGatewayFileAccessLog] = None


@dataclass
class VirtualGatewayBackendDefaults(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "client_policy": "ClientPolicy",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    client_policy: Optional[VirtualGatewayClientPolicy] = None


@dataclass
class VirtualGatewayClientPolicy(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "tls": "TLS",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    tls: Optional[VirtualGatewayClientPolicyTls] = None


@dataclass
class VirtualGatewayClientPolicyTls(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "validation": "Validation",
        "enforce": "Enforce",
        "ports": "Ports",
        "certificate": "Certificate",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    validation: Optional[VirtualGatewayTlsValidationContext] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    enforce: Optional[Union[bool, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    ports: Optional[Union[list[int], Ref]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    certificate: Optional[VirtualGatewayClientTlsCertificate] = None


@dataclass
class VirtualGatewayClientTlsCertificate(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "sds": "SDS",
        "file": "File",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    sds: Optional[VirtualGatewayListenerTlsSdsCertificate] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    file: Optional[VirtualGatewayListenerTlsFileCertificate] = None


@dataclass
class VirtualGatewayConnectionPool(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "http2": "HTTP2",
        "http": "HTTP",
        "grpc": "GRPC",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    http2: Optional[VirtualGatewayHttp2ConnectionPool] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    http: Optional[VirtualGatewayHttpConnectionPool] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    grpc: Optional[VirtualGatewayGrpcConnectionPool] = None


@dataclass
class VirtualGatewayFileAccessLog(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "path": "Path",
        "format": "Format",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    path: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    format: Optional[LoggingFormat] = None


@dataclass
class VirtualGatewayGrpcConnectionPool(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "max_requests": "MaxRequests",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    max_requests: Optional[Union[int, Ref, GetAtt, Sub]] = None


@dataclass
class VirtualGatewayHealthCheckPolicy(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "path": "Path",
        "unhealthy_threshold": "UnhealthyThreshold",
        "port": "Port",
        "healthy_threshold": "HealthyThreshold",
        "timeout_millis": "TimeoutMillis",
        "protocol": "Protocol",
        "interval_millis": "IntervalMillis",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    path: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    unhealthy_threshold: Optional[Union[int, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    port: Optional[Union[int, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    healthy_threshold: Optional[Union[int, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    timeout_millis: Optional[Union[int, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    protocol: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    interval_millis: Optional[Union[int, Ref, GetAtt, Sub]] = None


@dataclass
class VirtualGatewayHttp2ConnectionPool(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "max_requests": "MaxRequests",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    max_requests: Optional[Union[int, Ref, GetAtt, Sub]] = None


@dataclass
class VirtualGatewayHttpConnectionPool(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "max_connections": "MaxConnections",
        "max_pending_requests": "MaxPendingRequests",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    max_connections: Optional[Union[int, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    max_pending_requests: Optional[Union[int, Ref, GetAtt, Sub]] = None


@dataclass
class VirtualGatewayListener(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "connection_pool": "ConnectionPool",
        "health_check": "HealthCheck",
        "tls": "TLS",
        "port_mapping": "PortMapping",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    connection_pool: Optional[VirtualGatewayConnectionPool] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    health_check: Optional[VirtualGatewayHealthCheckPolicy] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    tls: Optional[VirtualGatewayListenerTls] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    port_mapping: Optional[VirtualGatewayPortMapping] = None


@dataclass
class VirtualGatewayListenerTls(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "validation": "Validation",
        "mode": "Mode",
        "certificate": "Certificate",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    validation: Optional[VirtualGatewayListenerTlsValidationContext] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    mode: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    certificate: Optional[VirtualGatewayListenerTlsCertificate] = None


@dataclass
class VirtualGatewayListenerTlsAcmCertificate(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "certificate_arn": "CertificateArn",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    certificate_arn: Optional[Union[str, Ref, GetAtt, Sub]] = None


@dataclass
class VirtualGatewayListenerTlsCertificate(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "sds": "SDS",
        "acm": "ACM",
        "file": "File",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    sds: Optional[VirtualGatewayListenerTlsSdsCertificate] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    acm: Optional[VirtualGatewayListenerTlsAcmCertificate] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    file: Optional[VirtualGatewayListenerTlsFileCertificate] = None


@dataclass
class VirtualGatewayListenerTlsFileCertificate(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "private_key": "PrivateKey",
        "certificate_chain": "CertificateChain",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    private_key: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    certificate_chain: Optional[Union[str, Ref, GetAtt, Sub]] = None


@dataclass
class VirtualGatewayListenerTlsSdsCertificate(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "secret_name": "SecretName",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    secret_name: Optional[Union[str, Ref, GetAtt, Sub]] = None


@dataclass
class VirtualGatewayListenerTlsValidationContext(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "subject_alternative_names": "SubjectAlternativeNames",
        "trust": "Trust",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    subject_alternative_names: Optional[SubjectAlternativeNames] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    trust: Optional[VirtualGatewayListenerTlsValidationContextTrust] = None


@dataclass
class VirtualGatewayListenerTlsValidationContextTrust(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "sds": "SDS",
        "file": "File",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    sds: Optional[VirtualGatewayTlsValidationContextSdsTrust] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    file: Optional[VirtualGatewayTlsValidationContextFileTrust] = None


@dataclass
class VirtualGatewayLogging(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "access_log": "AccessLog",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    access_log: Optional[VirtualGatewayAccessLog] = None


@dataclass
class VirtualGatewayPortMapping(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "port": "Port",
        "protocol": "Protocol",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    port: Optional[Union[int, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    protocol: Optional[Union[str, Ref, GetAtt, Sub]] = None


@dataclass
class VirtualGatewaySpec(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "logging": "Logging",
        "listeners": "Listeners",
        "backend_defaults": "BackendDefaults",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    logging: Optional[VirtualGatewayLogging] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    listeners: Optional[list[VirtualGatewayListener]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    backend_defaults: Optional[VirtualGatewayBackendDefaults] = None


@dataclass
class VirtualGatewayTlsValidationContext(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "subject_alternative_names": "SubjectAlternativeNames",
        "trust": "Trust",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    subject_alternative_names: Optional[SubjectAlternativeNames] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    trust: Optional[VirtualGatewayTlsValidationContextTrust] = None


@dataclass
class VirtualGatewayTlsValidationContextAcmTrust(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "certificate_authority_arns": "CertificateAuthorityArns",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    certificate_authority_arns: Optional[Union[list[str], Ref]] = None


@dataclass
class VirtualGatewayTlsValidationContextFileTrust(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "certificate_chain": "CertificateChain",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    certificate_chain: Optional[Union[str, Ref, GetAtt, Sub]] = None


@dataclass
class VirtualGatewayTlsValidationContextSdsTrust(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "secret_name": "SecretName",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    secret_name: Optional[Union[str, Ref, GetAtt, Sub]] = None


@dataclass
class VirtualGatewayTlsValidationContextTrust(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "sds": "SDS",
        "acm": "ACM",
        "file": "File",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    sds: Optional[VirtualGatewayTlsValidationContextSdsTrust] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    acm: Optional[VirtualGatewayTlsValidationContextAcmTrust] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    file: Optional[VirtualGatewayTlsValidationContextFileTrust] = None


@dataclass
class VirtualGateway(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appme"""

    resource_type: ClassVar[str] = "AWS::AppMesh::VirtualGateway"
    _property_mappings: ClassVar[dict[str, str]] = {
        "virtual_gateway_name": "VirtualGatewayName",
        "mesh_name": "MeshName",
        "mesh_owner": "MeshOwner",
        "spec": "Spec",
        "tags": "Tags",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    virtual_gateway_name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    mesh_name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    mesh_owner: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    spec: Optional[VirtualGatewaySpec] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    tags: Optional[list[Tag]] = None

    @property
    def attr_uid(self) -> GetAtt:
        """Get the Uid attribute."""
        return self.get_att("Uid")

    @property
    def attr_virtual_gateway_name(self) -> GetAtt:
        """Get the VirtualGatewayName attribute."""
        return self.get_att("VirtualGatewayName")

    @property
    def attr_mesh_name(self) -> GetAtt:
        """Get the MeshName attribute."""
        return self.get_att("MeshName")

    @property
    def attr_mesh_owner(self) -> GetAtt:
        """Get the MeshOwner attribute."""
        return self.get_att("MeshOwner")

    @property
    def attr_resource_owner(self) -> GetAtt:
        """Get the ResourceOwner attribute."""
        return self.get_att("ResourceOwner")

    @property
    def attr_arn(self) -> GetAtt:
        """Get the Arn attribute."""
        return self.get_att("Arn")




@dataclass
class AccessLog(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "file": "File",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    file: Optional[FileAccessLog] = None


@dataclass
class AwsCloudMapInstanceAttribute(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "value": "Value",
        "key": "Key",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    value: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    key: Optional[Union[str, Ref, GetAtt, Sub]] = None


@dataclass
class AwsCloudMapServiceDiscovery(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "namespace_name": "NamespaceName",
        "service_name": "ServiceName",
        "ip_preference": "IpPreference",
        "attributes": "Attributes",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    namespace_name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    service_name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    ip_preference: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    attributes: Optional[list[AwsCloudMapInstanceAttribute]] = None


@dataclass
class Backend(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "virtual_service": "VirtualService",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    virtual_service: Optional[VirtualServiceBackend] = None


@dataclass
class BackendDefaults(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "client_policy": "ClientPolicy",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    client_policy: Optional[ClientPolicy] = None


@dataclass
class ClientPolicy(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "tls": "TLS",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    tls: Optional[ClientPolicyTls] = None


@dataclass
class ClientPolicyTls(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "validation": "Validation",
        "enforce": "Enforce",
        "ports": "Ports",
        "certificate": "Certificate",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    validation: Optional[TlsValidationContext] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    enforce: Optional[Union[bool, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    ports: Optional[Union[list[int], Ref]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    certificate: Optional[ClientTlsCertificate] = None


@dataclass
class ClientTlsCertificate(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "sds": "SDS",
        "file": "File",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    sds: Optional[ListenerTlsSdsCertificate] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    file: Optional[ListenerTlsFileCertificate] = None


@dataclass
class DnsServiceDiscovery(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "ip_preference": "IpPreference",
        "hostname": "Hostname",
        "response_type": "ResponseType",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    ip_preference: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    hostname: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    response_type: Optional[Union[str, Ref, GetAtt, Sub]] = None


@dataclass
class Duration(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "value": "Value",
        "unit": "Unit",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    value: Optional[Union[int, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    unit: Optional[Union[str, Ref, GetAtt, Sub]] = None


@dataclass
class FileAccessLog(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "path": "Path",
        "format": "Format",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    path: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    format: Optional[LoggingFormat] = None


@dataclass
class GrpcTimeout(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "per_request": "PerRequest",
        "idle": "Idle",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    per_request: Optional[Duration] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    idle: Optional[Duration] = None


@dataclass
class HealthCheck(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "path": "Path",
        "unhealthy_threshold": "UnhealthyThreshold",
        "port": "Port",
        "healthy_threshold": "HealthyThreshold",
        "timeout_millis": "TimeoutMillis",
        "protocol": "Protocol",
        "interval_millis": "IntervalMillis",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    path: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    unhealthy_threshold: Optional[Union[int, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    port: Optional[Union[int, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    healthy_threshold: Optional[Union[int, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    timeout_millis: Optional[Union[int, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    protocol: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    interval_millis: Optional[Union[int, Ref, GetAtt, Sub]] = None


@dataclass
class HttpTimeout(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "per_request": "PerRequest",
        "idle": "Idle",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    per_request: Optional[Duration] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    idle: Optional[Duration] = None


@dataclass
class JsonFormatRef(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "value": "Value",
        "key": "Key",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    value: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    key: Optional[Union[str, Ref, GetAtt, Sub]] = None


@dataclass
class Listener(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "connection_pool": "ConnectionPool",
        "timeout": "Timeout",
        "health_check": "HealthCheck",
        "tls": "TLS",
        "port_mapping": "PortMapping",
        "outlier_detection": "OutlierDetection",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    connection_pool: Optional[VirtualNodeConnectionPool] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    timeout: Optional[ListenerTimeout] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    health_check: Optional[HealthCheck] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    tls: Optional[ListenerTls] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    port_mapping: Optional[PortMapping] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    outlier_detection: Optional[OutlierDetection] = None


@dataclass
class ListenerTimeout(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "tcp": "TCP",
        "http2": "HTTP2",
        "http": "HTTP",
        "grpc": "GRPC",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    tcp: Optional[TcpTimeout] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    http2: Optional[HttpTimeout] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    http: Optional[HttpTimeout] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    grpc: Optional[GrpcTimeout] = None


@dataclass
class ListenerTls(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "validation": "Validation",
        "mode": "Mode",
        "certificate": "Certificate",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    validation: Optional[ListenerTlsValidationContext] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    mode: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    certificate: Optional[ListenerTlsCertificate] = None


@dataclass
class ListenerTlsAcmCertificate(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "certificate_arn": "CertificateArn",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    certificate_arn: Optional[Union[str, Ref, GetAtt, Sub]] = None


@dataclass
class ListenerTlsCertificate(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "sds": "SDS",
        "acm": "ACM",
        "file": "File",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    sds: Optional[ListenerTlsSdsCertificate] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    acm: Optional[ListenerTlsAcmCertificate] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    file: Optional[ListenerTlsFileCertificate] = None


@dataclass
class ListenerTlsFileCertificate(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "private_key": "PrivateKey",
        "certificate_chain": "CertificateChain",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    private_key: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    certificate_chain: Optional[Union[str, Ref, GetAtt, Sub]] = None


@dataclass
class ListenerTlsSdsCertificate(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "secret_name": "SecretName",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    secret_name: Optional[Union[str, Ref, GetAtt, Sub]] = None


@dataclass
class ListenerTlsValidationContext(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "subject_alternative_names": "SubjectAlternativeNames",
        "trust": "Trust",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    subject_alternative_names: Optional[SubjectAlternativeNames] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    trust: Optional[ListenerTlsValidationContextTrust] = None


@dataclass
class ListenerTlsValidationContextTrust(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "sds": "SDS",
        "file": "File",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    sds: Optional[TlsValidationContextSdsTrust] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    file: Optional[TlsValidationContextFileTrust] = None


@dataclass
class Logging(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "access_log": "AccessLog",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    access_log: Optional[AccessLog] = None


@dataclass
class LoggingFormat(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "text": "Text",
        "json": "Json",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    text: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    json: Optional[list[JsonFormatRef]] = None


@dataclass
class OutlierDetection(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "max_ejection_percent": "MaxEjectionPercent",
        "base_ejection_duration": "BaseEjectionDuration",
        "max_server_errors": "MaxServerErrors",
        "interval": "Interval",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    max_ejection_percent: Optional[Union[int, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    base_ejection_duration: Optional[Duration] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    max_server_errors: Optional[Union[int, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    interval: Optional[Duration] = None


@dataclass
class PortMapping(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "port": "Port",
        "protocol": "Protocol",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    port: Optional[Union[int, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    protocol: Optional[Union[str, Ref, GetAtt, Sub]] = None


@dataclass
class ServiceDiscovery(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "dns": "DNS",
        "aws_cloud_map": "AWSCloudMap",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    dns: Optional[DnsServiceDiscovery] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    aws_cloud_map: Optional[AwsCloudMapServiceDiscovery] = None


@dataclass
class SubjectAlternativeNameMatchers(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "exact": "Exact",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    exact: Optional[Union[list[str], Ref]] = None


@dataclass
class SubjectAlternativeNames(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "match": "Match",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    match: Optional[SubjectAlternativeNameMatchers] = None


@dataclass
class TcpTimeout(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "idle": "Idle",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    idle: Optional[Duration] = None


@dataclass
class TlsValidationContext(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "subject_alternative_names": "SubjectAlternativeNames",
        "trust": "Trust",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    subject_alternative_names: Optional[SubjectAlternativeNames] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    trust: Optional[TlsValidationContextTrust] = None


@dataclass
class TlsValidationContextAcmTrust(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "certificate_authority_arns": "CertificateAuthorityArns",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    certificate_authority_arns: Optional[Union[list[str], Ref]] = None


@dataclass
class TlsValidationContextFileTrust(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "certificate_chain": "CertificateChain",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    certificate_chain: Optional[Union[str, Ref, GetAtt, Sub]] = None


@dataclass
class TlsValidationContextSdsTrust(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "secret_name": "SecretName",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    secret_name: Optional[Union[str, Ref, GetAtt, Sub]] = None


@dataclass
class TlsValidationContextTrust(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "sds": "SDS",
        "acm": "ACM",
        "file": "File",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    sds: Optional[TlsValidationContextSdsTrust] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    acm: Optional[TlsValidationContextAcmTrust] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    file: Optional[TlsValidationContextFileTrust] = None


@dataclass
class VirtualNodeConnectionPool(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "tcp": "TCP",
        "http2": "HTTP2",
        "http": "HTTP",
        "grpc": "GRPC",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    tcp: Optional[VirtualNodeTcpConnectionPool] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    http2: Optional[VirtualNodeHttp2ConnectionPool] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    http: Optional[VirtualNodeHttpConnectionPool] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    grpc: Optional[VirtualNodeGrpcConnectionPool] = None


@dataclass
class VirtualNodeGrpcConnectionPool(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "max_requests": "MaxRequests",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    max_requests: Optional[Union[int, Ref, GetAtt, Sub]] = None


@dataclass
class VirtualNodeHttp2ConnectionPool(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "max_requests": "MaxRequests",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    max_requests: Optional[Union[int, Ref, GetAtt, Sub]] = None


@dataclass
class VirtualNodeHttpConnectionPool(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "max_connections": "MaxConnections",
        "max_pending_requests": "MaxPendingRequests",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    max_connections: Optional[Union[int, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    max_pending_requests: Optional[Union[int, Ref, GetAtt, Sub]] = None


@dataclass
class VirtualNodeSpec(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "logging": "Logging",
        "backends": "Backends",
        "listeners": "Listeners",
        "backend_defaults": "BackendDefaults",
        "service_discovery": "ServiceDiscovery",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    logging: Optional[Logging] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    backends: Optional[list[Backend]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    listeners: Optional[list[Listener]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    backend_defaults: Optional[BackendDefaults] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    service_discovery: Optional[ServiceDiscovery] = None


@dataclass
class VirtualNodeTcpConnectionPool(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "max_connections": "MaxConnections",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    max_connections: Optional[Union[int, Ref, GetAtt, Sub]] = None


@dataclass
class VirtualServiceBackend(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "client_policy": "ClientPolicy",
        "virtual_service_name": "VirtualServiceName",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    client_policy: Optional[ClientPolicy] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    virtual_service_name: Optional[Union[str, Ref, GetAtt, Sub]] = None


@dataclass
class VirtualNode(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appme"""

    resource_type: ClassVar[str] = "AWS::AppMesh::VirtualNode"
    _property_mappings: ClassVar[dict[str, str]] = {
        "mesh_name": "MeshName",
        "mesh_owner": "MeshOwner",
        "spec": "Spec",
        "virtual_node_name": "VirtualNodeName",
        "tags": "Tags",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    mesh_name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    mesh_owner: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    spec: Optional[VirtualNodeSpec] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    virtual_node_name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    tags: Optional[list[Tag]] = None

    @property
    def attr_uid(self) -> GetAtt:
        """Get the Uid attribute."""
        return self.get_att("Uid")

    @property
    def attr_mesh_name(self) -> GetAtt:
        """Get the MeshName attribute."""
        return self.get_att("MeshName")

    @property
    def attr_mesh_owner(self) -> GetAtt:
        """Get the MeshOwner attribute."""
        return self.get_att("MeshOwner")

    @property
    def attr_resource_owner(self) -> GetAtt:
        """Get the ResourceOwner attribute."""
        return self.get_att("ResourceOwner")

    @property
    def attr_arn(self) -> GetAtt:
        """Get the Arn attribute."""
        return self.get_att("Arn")

    @property
    def attr_virtual_node_name(self) -> GetAtt:
        """Get the VirtualNodeName attribute."""
        return self.get_att("VirtualNodeName")




@dataclass
class PortMapping(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "port": "Port",
        "protocol": "Protocol",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    port: Optional[Union[int, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    protocol: Optional[Union[str, Ref, GetAtt, Sub]] = None


@dataclass
class VirtualRouterListener(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "port_mapping": "PortMapping",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    port_mapping: Optional[PortMapping] = None


@dataclass
class VirtualRouterSpec(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "listeners": "Listeners",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    listeners: Optional[list[VirtualRouterListener]] = None


@dataclass
class VirtualRouter(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appme"""

    resource_type: ClassVar[str] = "AWS::AppMesh::VirtualRouter"
    _property_mappings: ClassVar[dict[str, str]] = {
        "mesh_name": "MeshName",
        "virtual_router_name": "VirtualRouterName",
        "mesh_owner": "MeshOwner",
        "spec": "Spec",
        "tags": "Tags",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    mesh_name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    virtual_router_name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    mesh_owner: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    spec: Optional[VirtualRouterSpec] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    tags: Optional[list[Tag]] = None

    @property
    def attr_uid(self) -> GetAtt:
        """Get the Uid attribute."""
        return self.get_att("Uid")

    @property
    def attr_mesh_name(self) -> GetAtt:
        """Get the MeshName attribute."""
        return self.get_att("MeshName")

    @property
    def attr_virtual_router_name(self) -> GetAtt:
        """Get the VirtualRouterName attribute."""
        return self.get_att("VirtualRouterName")

    @property
    def attr_mesh_owner(self) -> GetAtt:
        """Get the MeshOwner attribute."""
        return self.get_att("MeshOwner")

    @property
    def attr_resource_owner(self) -> GetAtt:
        """Get the ResourceOwner attribute."""
        return self.get_att("ResourceOwner")

    @property
    def attr_arn(self) -> GetAtt:
        """Get the Arn attribute."""
        return self.get_att("Arn")




@dataclass
class VirtualNodeServiceProvider(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "virtual_node_name": "VirtualNodeName",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    virtual_node_name: Optional[Union[str, Ref, GetAtt, Sub]] = None


@dataclass
class VirtualRouterServiceProvider(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "virtual_router_name": "VirtualRouterName",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    virtual_router_name: Optional[Union[str, Ref, GetAtt, Sub]] = None


@dataclass
class VirtualServiceProvider(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "virtual_node": "VirtualNode",
        "virtual_router": "VirtualRouter",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    virtual_node: Optional[VirtualNodeServiceProvider] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    virtual_router: Optional[VirtualRouterServiceProvider] = None


@dataclass
class VirtualServiceSpec(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "provider": "Provider",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    provider: Optional[VirtualServiceProvider] = None


@dataclass
class VirtualService(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appme"""

    resource_type: ClassVar[str] = "AWS::AppMesh::VirtualService"
    _property_mappings: ClassVar[dict[str, str]] = {
        "mesh_name": "MeshName",
        "mesh_owner": "MeshOwner",
        "virtual_service_name": "VirtualServiceName",
        "spec": "Spec",
        "tags": "Tags",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    mesh_name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    mesh_owner: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    virtual_service_name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    spec: Optional[VirtualServiceSpec] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    tags: Optional[list[Tag]] = None

    @property
    def attr_uid(self) -> GetAtt:
        """Get the Uid attribute."""
        return self.get_att("Uid")

    @property
    def attr_mesh_name(self) -> GetAtt:
        """Get the MeshName attribute."""
        return self.get_att("MeshName")

    @property
    def attr_mesh_owner(self) -> GetAtt:
        """Get the MeshOwner attribute."""
        return self.get_att("MeshOwner")

    @property
    def attr_resource_owner(self) -> GetAtt:
        """Get the ResourceOwner attribute."""
        return self.get_att("ResourceOwner")

    @property
    def attr_virtual_service_name(self) -> GetAtt:
        """Get the VirtualServiceName attribute."""
        return self.get_att("VirtualServiceName")

    @property
    def attr_arn(self) -> GetAtt:
        """Get the Arn attribute."""
        return self.get_att("Arn")



