"""
AWS CloudFormation Billing Resources

⚠️  AUTO-GENERATED FILE - DO NOT EDIT MANUALLY ⚠️

This file is automatically generated from the AWS CloudFormation Resource Specification.
Any manual changes will be overwritten when regenerated.

Version Information:
  CloudFormation Spec: 2025.12.11
  Generator Version: 1.0.0
  Combined: spec-2025.12.11_gen-1.0.0
  Generated: 2025-12-17 21:37:33

To regenerate this file:
    uv run python -m cloudformation_dataclasses.codegen.generator --service Billing
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, ClassVar, Optional, Union

from cloudformation_dataclasses.core.base import CloudFormationResource
from cloudformation_dataclasses.intrinsics.functions import GetAtt, Ref, Sub


# =============================================================================
# Service Constants (auto-generated from botocore)
# =============================================================================

class BillingViewStatus:
    """BillingViewStatus enum values."""

    HEALTHY = "HEALTHY"
    UNHEALTHY = "UNHEALTHY"
    CREATING = "CREATING"
    UPDATING = "UPDATING"


class BillingViewStatusReason:
    """BillingViewStatusReason enum values."""

    SOURCE_VIEW_UNHEALTHY = "SOURCE_VIEW_UNHEALTHY"
    SOURCE_VIEW_UPDATING = "SOURCE_VIEW_UPDATING"
    SOURCE_VIEW_ACCESS_DENIED = "SOURCE_VIEW_ACCESS_DENIED"
    SOURCE_VIEW_NOT_FOUND = "SOURCE_VIEW_NOT_FOUND"
    CYCLIC_DEPENDENCY = "CYCLIC_DEPENDENCY"
    SOURCE_VIEW_DEPTH_EXCEEDED = "SOURCE_VIEW_DEPTH_EXCEEDED"
    AGGREGATE_SOURCE = "AGGREGATE_SOURCE"
    VIEW_OWNER_NOT_MANAGEMENT_ACCOUNT = "VIEW_OWNER_NOT_MANAGEMENT_ACCOUNT"


class BillingViewType:
    """BillingViewType enum values."""

    PRIMARY = "PRIMARY"
    BILLING_GROUP = "BILLING_GROUP"
    CUSTOM = "CUSTOM"
    BILLING_TRANSFER = "BILLING_TRANSFER"
    BILLING_TRANSFER_SHOWBACK = "BILLING_TRANSFER_SHOWBACK"


class Dimension:
    """Dimension enum values."""

    LINKED_ACCOUNT = "LINKED_ACCOUNT"


class SearchOption:
    """SearchOption enum values."""

    STARTS_WITH = "STARTS_WITH"


class ValidationExceptionReason:
    """ValidationExceptionReason enum values."""

    UNKNOWNOPERATION = "unknownOperation"
    CANNOTPARSE = "cannotParse"
    FIELDVALIDATIONFAILED = "fieldValidationFailed"
    OTHER = "other"


# Convenient aliases for enum values
HEALTHY = BillingViewStatus.HEALTHY
UNHEALTHY = BillingViewStatus.UNHEALTHY
CREATING = BillingViewStatus.CREATING
UPDATING = BillingViewStatus.UPDATING
SOURCE_VIEW_UNHEALTHY = BillingViewStatusReason.SOURCE_VIEW_UNHEALTHY
SOURCE_VIEW_UPDATING = BillingViewStatusReason.SOURCE_VIEW_UPDATING
SOURCE_VIEW_ACCESS_DENIED = BillingViewStatusReason.SOURCE_VIEW_ACCESS_DENIED
SOURCE_VIEW_NOT_FOUND = BillingViewStatusReason.SOURCE_VIEW_NOT_FOUND
CYCLIC_DEPENDENCY = BillingViewStatusReason.CYCLIC_DEPENDENCY
SOURCE_VIEW_DEPTH_EXCEEDED = BillingViewStatusReason.SOURCE_VIEW_DEPTH_EXCEEDED
AGGREGATE_SOURCE = BillingViewStatusReason.AGGREGATE_SOURCE
VIEW_OWNER_NOT_MANAGEMENT_ACCOUNT = BillingViewStatusReason.VIEW_OWNER_NOT_MANAGEMENT_ACCOUNT
PRIMARY = BillingViewType.PRIMARY
BILLING_GROUP = BillingViewType.BILLING_GROUP
CUSTOM = BillingViewType.CUSTOM
BILLING_TRANSFER = BillingViewType.BILLING_TRANSFER
BILLING_TRANSFER_SHOWBACK = BillingViewType.BILLING_TRANSFER_SHOWBACK
LINKED_ACCOUNT = Dimension.LINKED_ACCOUNT
STARTS_WITH = SearchOption.STARTS_WITH
UNKNOWNOPERATION = ValidationExceptionReason.UNKNOWNOPERATION
CANNOTPARSE = ValidationExceptionReason.CANNOTPARSE
FIELDVALIDATIONFAILED = ValidationExceptionReason.FIELDVALIDATIONFAILED
OTHER = ValidationExceptionReason.OTHER


@dataclass
class DataFilterExpression:
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-bil"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "dimensions": "Dimensions",
        "tags": "Tags",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    dimensions: Optional[Dimensions] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    tags: Optional[Tags] = None

    def _serialize_value(self, value: Any) -> Any:
        """Recursively serialize a value."""
        if hasattr(value, 'to_dict'):
            return value.to_dict()
        if isinstance(value, list):
            return [self._serialize_value(item) for item in value]
        if isinstance(value, dict):
            return {k: self._serialize_value(v) for k, v in value.items()}
        return value

    def to_dict(self) -> dict[str, Any]:
        """Serialize to CloudFormation format."""
        props: dict[str, Any] = {}
        for field_name, cf_name in self._property_mappings.items():
            value = getattr(self, field_name, None)
            if value is not None:
                props[cf_name] = self._serialize_value(value)
        return props


@dataclass
class Dimensions:
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-bil"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "values": "Values",
        "key": "Key",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    values: Optional[Union[list[str], Ref]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    key: Optional[Union[str, Ref, GetAtt, Sub]] = None

    def _serialize_value(self, value: Any) -> Any:
        """Recursively serialize a value."""
        if hasattr(value, 'to_dict'):
            return value.to_dict()
        if isinstance(value, list):
            return [self._serialize_value(item) for item in value]
        if isinstance(value, dict):
            return {k: self._serialize_value(v) for k, v in value.items()}
        return value

    def to_dict(self) -> dict[str, Any]:
        """Serialize to CloudFormation format."""
        props: dict[str, Any] = {}
        for field_name, cf_name in self._property_mappings.items():
            value = getattr(self, field_name, None)
            if value is not None:
                props[cf_name] = self._serialize_value(value)
        return props


@dataclass
class Tags:
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-bil"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "values": "Values",
        "key": "Key",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    values: Optional[Union[list[str], Ref]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    key: Optional[Union[str, Ref, GetAtt, Sub]] = None

    def _serialize_value(self, value: Any) -> Any:
        """Recursively serialize a value."""
        if hasattr(value, 'to_dict'):
            return value.to_dict()
        if isinstance(value, list):
            return [self._serialize_value(item) for item in value]
        if isinstance(value, dict):
            return {k: self._serialize_value(v) for k, v in value.items()}
        return value

    def to_dict(self) -> dict[str, Any]:
        """Serialize to CloudFormation format."""
        props: dict[str, Any] = {}
        for field_name, cf_name in self._property_mappings.items():
            value = getattr(self, field_name, None)
            if value is not None:
                props[cf_name] = self._serialize_value(value)
        return props


@dataclass
class BillingView(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-billi"""

    resource_type: ClassVar[str] = "AWS::Billing::BillingView"
    _property_mappings: ClassVar[dict[str, str]] = {
        "description": "Description",
        "source_views": "SourceViews",
        "data_filter_expression": "DataFilterExpression",
        "tags": "Tags",
        "name": "Name",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    description: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    source_views: Optional[Union[list[str], Ref]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    data_filter_expression: Optional[DataFilterExpression] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    tags: Optional[list[Tag]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    name: Optional[Union[str, Ref, GetAtt, Sub]] = None

    @property
    def attr_created_at(self) -> GetAtt:
        """Get the CreatedAt attribute."""
        return self.get_att("CreatedAt")

    @property
    def attr_arn(self) -> GetAtt:
        """Get the Arn attribute."""
        return self.get_att("Arn")

    @property
    def attr_owner_account_id(self) -> GetAtt:
        """Get the OwnerAccountId attribute."""
        return self.get_att("OwnerAccountId")

    @property
    def attr_billing_view_type(self) -> GetAtt:
        """Get the BillingViewType attribute."""
        return self.get_att("BillingViewType")

    @property
    def attr_updated_at(self) -> GetAtt:
        """Get the UpdatedAt attribute."""
        return self.get_att("UpdatedAt")



