"""
AWS CloudFormation CloudWatch Resources

⚠️  AUTO-GENERATED FILE - DO NOT EDIT MANUALLY ⚠️

This file is automatically generated from the AWS CloudFormation Resource Specification.
Any manual changes will be overwritten when regenerated.

Version Information:
  CloudFormation Spec: 2025.12.11
  Generator Version: 1.0.0
  Combined: spec-2025.12.11_gen-1.0.0
  Generated: 2025-12-17 21:43:34

To regenerate this file:
    uv run python -m cloudformation_dataclasses.codegen.generator --service CloudWatch
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, ClassVar, Optional, Union

from cloudformation_dataclasses.core.base import CloudFormationResource, PropertyType
from cloudformation_dataclasses.intrinsics.functions import GetAtt, Ref, Sub


# =============================================================================
# Service Constants (auto-generated from botocore)
# =============================================================================

class ActionsSuppressedBy:
    """ActionsSuppressedBy enum values."""

    WAITPERIOD = "WaitPeriod"
    EXTENSIONPERIOD = "ExtensionPeriod"
    ALARM = "Alarm"


class AlarmType:
    """AlarmType enum values."""

    COMPOSITEALARM = "CompositeAlarm"
    METRICALARM = "MetricAlarm"


class AnomalyDetectorStateValue:
    """AnomalyDetectorStateValue enum values."""

    PENDING_TRAINING = "PENDING_TRAINING"
    TRAINED_INSUFFICIENT_DATA = "TRAINED_INSUFFICIENT_DATA"
    TRAINED = "TRAINED"


class AnomalyDetectorType:
    """AnomalyDetectorType enum values."""

    SINGLE_METRIC = "SINGLE_METRIC"
    METRIC_MATH = "METRIC_MATH"


class ComparisonOperator:
    """ComparisonOperator enum values."""

    GREATERTHANOREQUALTOTHRESHOLD = "GreaterThanOrEqualToThreshold"
    GREATERTHANTHRESHOLD = "GreaterThanThreshold"
    LESSTHANTHRESHOLD = "LessThanThreshold"
    LESSTHANOREQUALTOTHRESHOLD = "LessThanOrEqualToThreshold"
    LESSTHANLOWERORGREATERTHANUPPERTHRESHOLD = "LessThanLowerOrGreaterThanUpperThreshold"
    LESSTHANLOWERTHRESHOLD = "LessThanLowerThreshold"
    GREATERTHANUPPERTHRESHOLD = "GreaterThanUpperThreshold"


class EvaluationState:
    """EvaluationState enum values."""

    PARTIAL_DATA = "PARTIAL_DATA"


class HistoryItemType:
    """HistoryItemType enum values."""

    CONFIGURATIONUPDATE = "ConfigurationUpdate"
    STATEUPDATE = "StateUpdate"
    ACTION = "Action"
    ALARMCONTRIBUTORSTATEUPDATE = "AlarmContributorStateUpdate"
    ALARMCONTRIBUTORACTION = "AlarmContributorAction"


class MetricStreamOutputFormat:
    """MetricStreamOutputFormat enum values."""

    JSON = "json"
    OPENTELEMETRY0_7 = "opentelemetry0.7"
    OPENTELEMETRY1_0 = "opentelemetry1.0"


class RecentlyActive:
    """RecentlyActive enum values."""

    PT3H = "PT3H"


class ScanBy:
    """ScanBy enum values."""

    TIMESTAMPDESCENDING = "TimestampDescending"
    TIMESTAMPASCENDING = "TimestampAscending"


class StandardUnit:
    """StandardUnit enum values."""

    SECONDS = "Seconds"
    MICROSECONDS = "Microseconds"
    MILLISECONDS = "Milliseconds"
    BYTES = "Bytes"
    KILOBYTES = "Kilobytes"
    MEGABYTES = "Megabytes"
    GIGABYTES = "Gigabytes"
    TERABYTES = "Terabytes"
    BITS = "Bits"
    KILOBITS = "Kilobits"
    MEGABITS = "Megabits"
    GIGABITS = "Gigabits"
    TERABITS = "Terabits"
    PERCENT = "Percent"
    COUNT = "Count"
    BYTES_SECOND = "Bytes/Second"
    KILOBYTES_SECOND = "Kilobytes/Second"
    MEGABYTES_SECOND = "Megabytes/Second"
    GIGABYTES_SECOND = "Gigabytes/Second"
    TERABYTES_SECOND = "Terabytes/Second"
    BITS_SECOND = "Bits/Second"
    KILOBITS_SECOND = "Kilobits/Second"
    MEGABITS_SECOND = "Megabits/Second"
    GIGABITS_SECOND = "Gigabits/Second"
    TERABITS_SECOND = "Terabits/Second"
    COUNT_SECOND = "Count/Second"
    NONE = "None"


class StateValue:
    """StateValue enum values."""

    OK = "OK"
    ALARM = "ALARM"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"


class Statistic:
    """Statistic enum values."""

    SAMPLECOUNT = "SampleCount"
    AVERAGE = "Average"
    SUM = "Sum"
    MINIMUM = "Minimum"
    MAXIMUM = "Maximum"


class StatusCode:
    """StatusCode enum values."""

    COMPLETE = "Complete"
    INTERNALERROR = "InternalError"
    PARTIALDATA = "PartialData"
    FORBIDDEN = "Forbidden"


# Convenient aliases for enum values
WAITPERIOD = ActionsSuppressedBy.WAITPERIOD
EXTENSIONPERIOD = ActionsSuppressedBy.EXTENSIONPERIOD
ALARM = ActionsSuppressedBy.ALARM
COMPOSITEALARM = AlarmType.COMPOSITEALARM
METRICALARM = AlarmType.METRICALARM
PENDING_TRAINING = AnomalyDetectorStateValue.PENDING_TRAINING
TRAINED_INSUFFICIENT_DATA = AnomalyDetectorStateValue.TRAINED_INSUFFICIENT_DATA
TRAINED = AnomalyDetectorStateValue.TRAINED
SINGLE_METRIC = AnomalyDetectorType.SINGLE_METRIC
METRIC_MATH = AnomalyDetectorType.METRIC_MATH
GREATERTHANOREQUALTOTHRESHOLD = ComparisonOperator.GREATERTHANOREQUALTOTHRESHOLD
GREATERTHANTHRESHOLD = ComparisonOperator.GREATERTHANTHRESHOLD
LESSTHANTHRESHOLD = ComparisonOperator.LESSTHANTHRESHOLD
LESSTHANOREQUALTOTHRESHOLD = ComparisonOperator.LESSTHANOREQUALTOTHRESHOLD
LESSTHANLOWERORGREATERTHANUPPERTHRESHOLD = ComparisonOperator.LESSTHANLOWERORGREATERTHANUPPERTHRESHOLD
LESSTHANLOWERTHRESHOLD = ComparisonOperator.LESSTHANLOWERTHRESHOLD
GREATERTHANUPPERTHRESHOLD = ComparisonOperator.GREATERTHANUPPERTHRESHOLD
PARTIAL_DATA = EvaluationState.PARTIAL_DATA
CONFIGURATIONUPDATE = HistoryItemType.CONFIGURATIONUPDATE
STATEUPDATE = HistoryItemType.STATEUPDATE
ACTION = HistoryItemType.ACTION
ALARMCONTRIBUTORSTATEUPDATE = HistoryItemType.ALARMCONTRIBUTORSTATEUPDATE
ALARMCONTRIBUTORACTION = HistoryItemType.ALARMCONTRIBUTORACTION
JSON = MetricStreamOutputFormat.JSON
OPENTELEMETRY0_7 = MetricStreamOutputFormat.OPENTELEMETRY0_7
OPENTELEMETRY1_0 = MetricStreamOutputFormat.OPENTELEMETRY1_0
PT3H = RecentlyActive.PT3H
TIMESTAMPDESCENDING = ScanBy.TIMESTAMPDESCENDING
TIMESTAMPASCENDING = ScanBy.TIMESTAMPASCENDING
SECONDS = StandardUnit.SECONDS
MICROSECONDS = StandardUnit.MICROSECONDS
MILLISECONDS = StandardUnit.MILLISECONDS
BYTES = StandardUnit.BYTES
KILOBYTES = StandardUnit.KILOBYTES
MEGABYTES = StandardUnit.MEGABYTES
GIGABYTES = StandardUnit.GIGABYTES
TERABYTES = StandardUnit.TERABYTES
BITS = StandardUnit.BITS
KILOBITS = StandardUnit.KILOBITS
MEGABITS = StandardUnit.MEGABITS
GIGABITS = StandardUnit.GIGABITS
TERABITS = StandardUnit.TERABITS
PERCENT = StandardUnit.PERCENT
COUNT = StandardUnit.COUNT
BYTES_SECOND = StandardUnit.BYTES_SECOND
KILOBYTES_SECOND = StandardUnit.KILOBYTES_SECOND
MEGABYTES_SECOND = StandardUnit.MEGABYTES_SECOND
GIGABYTES_SECOND = StandardUnit.GIGABYTES_SECOND
TERABYTES_SECOND = StandardUnit.TERABYTES_SECOND
BITS_SECOND = StandardUnit.BITS_SECOND
KILOBITS_SECOND = StandardUnit.KILOBITS_SECOND
MEGABITS_SECOND = StandardUnit.MEGABITS_SECOND
GIGABITS_SECOND = StandardUnit.GIGABITS_SECOND
TERABITS_SECOND = StandardUnit.TERABITS_SECOND
COUNT_SECOND = StandardUnit.COUNT_SECOND
NONE = StandardUnit.NONE
OK = StateValue.OK
ALARM = StateValue.ALARM
INSUFFICIENT_DATA = StateValue.INSUFFICIENT_DATA
SAMPLECOUNT = Statistic.SAMPLECOUNT
AVERAGE = Statistic.AVERAGE
SUM = Statistic.SUM
MINIMUM = Statistic.MINIMUM
MAXIMUM = Statistic.MAXIMUM
COMPLETE = StatusCode.COMPLETE
INTERNALERROR = StatusCode.INTERNALERROR
PARTIALDATA = StatusCode.PARTIALDATA
FORBIDDEN = StatusCode.FORBIDDEN


@dataclass
class Dimension(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-clo"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "value": "Value",
        "name": "Name",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    value: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    name: Optional[Union[str, Ref, GetAtt, Sub]] = None


@dataclass
class Metric(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-clo"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "metric_name": "MetricName",
        "dimensions": "Dimensions",
        "namespace": "Namespace",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    metric_name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    dimensions: Optional[list[Dimension]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    namespace: Optional[Union[str, Ref, GetAtt, Sub]] = None


@dataclass
class MetricDataQuery(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-clo"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "account_id": "AccountId",
        "return_data": "ReturnData",
        "expression": "Expression",
        "label": "Label",
        "metric_stat": "MetricStat",
        "period": "Period",
        "id": "Id",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    account_id: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    return_data: Optional[Union[bool, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    expression: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    label: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    metric_stat: Optional[MetricStat] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    period: Optional[Union[int, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    id: Optional[Union[str, Ref, GetAtt, Sub]] = None


@dataclass
class MetricStat(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-clo"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "stat": "Stat",
        "period": "Period",
        "metric": "Metric",
        "unit": "Unit",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    stat: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    period: Optional[Union[int, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    metric: Optional[Metric] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    unit: Optional[Union[str, StandardUnit, Ref, GetAtt, Sub]] = None


@dataclass
class Alarm(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloud"""

    resource_type: ClassVar[str] = "AWS::CloudWatch::Alarm"
    _property_mappings: ClassVar[dict[str, str]] = {
        "threshold_metric_id": "ThresholdMetricId",
        "evaluate_low_sample_count_percentile": "EvaluateLowSampleCountPercentile",
        "extended_statistic": "ExtendedStatistic",
        "comparison_operator": "ComparisonOperator",
        "treat_missing_data": "TreatMissingData",
        "dimensions": "Dimensions",
        "period": "Period",
        "evaluation_periods": "EvaluationPeriods",
        "unit": "Unit",
        "namespace": "Namespace",
        "ok_actions": "OKActions",
        "alarm_actions": "AlarmActions",
        "metric_name": "MetricName",
        "actions_enabled": "ActionsEnabled",
        "metrics": "Metrics",
        "alarm_description": "AlarmDescription",
        "alarm_name": "AlarmName",
        "statistic": "Statistic",
        "insufficient_data_actions": "InsufficientDataActions",
        "datapoints_to_alarm": "DatapointsToAlarm",
        "tags": "Tags",
        "threshold": "Threshold",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    threshold_metric_id: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    evaluate_low_sample_count_percentile: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    extended_statistic: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    comparison_operator: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    treat_missing_data: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    dimensions: Optional[list[Dimension]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    period: Optional[Union[int, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    evaluation_periods: Optional[Union[int, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    unit: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    namespace: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    ok_actions: Optional[Union[list[str], Ref]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    alarm_actions: Optional[Union[list[str], Ref]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    metric_name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    actions_enabled: Optional[Union[bool, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    metrics: Optional[list[MetricDataQuery]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    alarm_description: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    alarm_name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    statistic: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    insufficient_data_actions: Optional[Union[list[str], Ref]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    datapoints_to_alarm: Optional[Union[int, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    tags: Optional[list[Tag]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    threshold: Optional[Union[float, Ref, GetAtt, Sub]] = None

    @property
    def attr_arn(self) -> GetAtt:
        """Get the Arn attribute."""
        return self.get_att("Arn")




@dataclass
class Configuration(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-clo"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "metric_time_zone": "MetricTimeZone",
        "excluded_time_ranges": "ExcludedTimeRanges",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    metric_time_zone: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    excluded_time_ranges: Optional[list[Range]] = None


@dataclass
class Dimension(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-clo"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "value": "Value",
        "name": "Name",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    value: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    name: Optional[Union[str, Ref, GetAtt, Sub]] = None


@dataclass
class Metric(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-clo"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "metric_name": "MetricName",
        "dimensions": "Dimensions",
        "namespace": "Namespace",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    metric_name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    dimensions: Optional[list[Dimension]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    namespace: Optional[Union[str, Ref, GetAtt, Sub]] = None


@dataclass
class MetricCharacteristics(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-clo"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "periodic_spikes": "PeriodicSpikes",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    periodic_spikes: Optional[Union[bool, Ref, GetAtt, Sub]] = None


@dataclass
class MetricDataQueries(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-clo"""

    pass


@dataclass
class MetricDataQuery(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-clo"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "account_id": "AccountId",
        "return_data": "ReturnData",
        "expression": "Expression",
        "metric_stat": "MetricStat",
        "label": "Label",
        "period": "Period",
        "id": "Id",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    account_id: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    return_data: Optional[Union[bool, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    expression: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    metric_stat: Optional[MetricStat] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    label: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    period: Optional[Union[int, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    id: Optional[Union[str, Ref, GetAtt, Sub]] = None


@dataclass
class MetricMathAnomalyDetector(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-clo"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "metric_data_queries": "MetricDataQueries",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    metric_data_queries: Optional[list[MetricDataQuery]] = None


@dataclass
class MetricStat(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-clo"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "stat": "Stat",
        "period": "Period",
        "metric": "Metric",
        "unit": "Unit",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    stat: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    period: Optional[Union[int, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    metric: Optional[Metric] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    unit: Optional[Union[str, StandardUnit, Ref, GetAtt, Sub]] = None


@dataclass
class Range(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-clo"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "end_time": "EndTime",
        "start_time": "StartTime",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    end_time: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    start_time: Optional[Union[str, Ref, GetAtt, Sub]] = None


@dataclass
class SingleMetricAnomalyDetector(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-clo"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "metric_name": "MetricName",
        "account_id": "AccountId",
        "stat": "Stat",
        "dimensions": "Dimensions",
        "namespace": "Namespace",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    metric_name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    account_id: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    stat: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    dimensions: Optional[list[Dimension]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    namespace: Optional[Union[str, Ref, GetAtt, Sub]] = None


@dataclass
class AnomalyDetector(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloud"""

    resource_type: ClassVar[str] = "AWS::CloudWatch::AnomalyDetector"
    _property_mappings: ClassVar[dict[str, str]] = {
        "metric_characteristics": "MetricCharacteristics",
        "metric_name": "MetricName",
        "stat": "Stat",
        "configuration": "Configuration",
        "metric_math_anomaly_detector": "MetricMathAnomalyDetector",
        "dimensions": "Dimensions",
        "namespace": "Namespace",
        "single_metric_anomaly_detector": "SingleMetricAnomalyDetector",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    metric_characteristics: Optional[MetricCharacteristics] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    metric_name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    stat: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    configuration: Optional[Configuration] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    metric_math_anomaly_detector: Optional[MetricMathAnomalyDetector] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    dimensions: Optional[list[Dimension]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    namespace: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    single_metric_anomaly_detector: Optional[SingleMetricAnomalyDetector] = None



@dataclass
class CompositeAlarm(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloud"""

    resource_type: ClassVar[str] = "AWS::CloudWatch::CompositeAlarm"
    _property_mappings: ClassVar[dict[str, str]] = {
        "alarm_actions": "AlarmActions",
        "actions_suppressor_wait_period": "ActionsSuppressorWaitPeriod",
        "actions_enabled": "ActionsEnabled",
        "alarm_name": "AlarmName",
        "alarm_description": "AlarmDescription",
        "actions_suppressor": "ActionsSuppressor",
        "alarm_rule": "AlarmRule",
        "insufficient_data_actions": "InsufficientDataActions",
        "ok_actions": "OKActions",
        "actions_suppressor_extension_period": "ActionsSuppressorExtensionPeriod",
        "tags": "Tags",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    alarm_actions: Optional[Union[list[str], Ref]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    actions_suppressor_wait_period: Optional[Union[int, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    actions_enabled: Optional[Union[bool, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    alarm_name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    alarm_description: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    actions_suppressor: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    alarm_rule: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    insufficient_data_actions: Optional[Union[list[str], Ref]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    ok_actions: Optional[Union[list[str], Ref]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    actions_suppressor_extension_period: Optional[Union[int, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    tags: Optional[list[Tag]] = None

    @property
    def attr_arn(self) -> GetAtt:
        """Get the Arn attribute."""
        return self.get_att("Arn")




@dataclass
class Dashboard(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloud"""

    resource_type: ClassVar[str] = "AWS::CloudWatch::Dashboard"
    _property_mappings: ClassVar[dict[str, str]] = {
        "dashboard_name": "DashboardName",
        "dashboard_body": "DashboardBody",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    dashboard_name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    dashboard_body: Optional[Union[str, Ref, GetAtt, Sub]] = None



@dataclass
class Tags(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-clo"""

    pass


@dataclass
class InsightRule(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloud"""

    resource_type: ClassVar[str] = "AWS::CloudWatch::InsightRule"
    _property_mappings: ClassVar[dict[str, str]] = {
        "rule_state": "RuleState",
        "rule_body": "RuleBody",
        "apply_on_transformed_logs": "ApplyOnTransformedLogs",
        "rule_name": "RuleName",
        "tags": "Tags",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    rule_state: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    rule_body: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    apply_on_transformed_logs: Optional[Union[bool, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    rule_name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    tags: Optional[Tags] = None

    @property
    def attr_arn(self) -> GetAtt:
        """Get the Arn attribute."""
        return self.get_att("Arn")

    @property
    def attr_rule_name(self) -> GetAtt:
        """Get the RuleName attribute."""
        return self.get_att("RuleName")




@dataclass
class MetricStreamFilter(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-clo"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "metric_names": "MetricNames",
        "namespace": "Namespace",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    metric_names: Optional[Union[list[str], Ref]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    namespace: Optional[Union[str, Ref, GetAtt, Sub]] = None


@dataclass
class MetricStreamStatisticsConfiguration(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-clo"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "include_metrics": "IncludeMetrics",
        "additional_statistics": "AdditionalStatistics",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    include_metrics: Optional[list[MetricStreamStatisticsMetric]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    additional_statistics: Optional[Union[list[str], Ref]] = None


@dataclass
class MetricStreamStatisticsMetric(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-clo"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "metric_name": "MetricName",
        "namespace": "Namespace",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    metric_name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    namespace: Optional[Union[str, Ref, GetAtt, Sub]] = None


@dataclass
class MetricStream(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloud"""

    resource_type: ClassVar[str] = "AWS::CloudWatch::MetricStream"
    _property_mappings: ClassVar[dict[str, str]] = {
        "statistics_configurations": "StatisticsConfigurations",
        "firehose_arn": "FirehoseArn",
        "include_linked_accounts_metrics": "IncludeLinkedAccountsMetrics",
        "include_filters": "IncludeFilters",
        "output_format": "OutputFormat",
        "exclude_filters": "ExcludeFilters",
        "role_arn": "RoleArn",
        "tags": "Tags",
        "name": "Name",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    statistics_configurations: Optional[list[MetricStreamStatisticsConfiguration]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    firehose_arn: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    include_linked_accounts_metrics: Optional[Union[bool, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    include_filters: Optional[list[MetricStreamFilter]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    output_format: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    exclude_filters: Optional[list[MetricStreamFilter]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    role_arn: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    tags: Optional[list[Tag]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    name: Optional[Union[str, Ref, GetAtt, Sub]] = None

    @property
    def attr_creation_date(self) -> GetAtt:
        """Get the CreationDate attribute."""
        return self.get_att("CreationDate")

    @property
    def attr_state(self) -> GetAtt:
        """Get the State attribute."""
        return self.get_att("State")

    @property
    def attr_arn(self) -> GetAtt:
        """Get the Arn attribute."""
        return self.get_att("Arn")

    @property
    def attr_last_update_date(self) -> GetAtt:
        """Get the LastUpdateDate attribute."""
        return self.get_att("LastUpdateDate")



