"""
AWS CloudFormation ElasticBeanstalk Resources

⚠️  AUTO-GENERATED FILE - DO NOT EDIT MANUALLY ⚠️

This file is automatically generated from the AWS CloudFormation Resource Specification.
Any manual changes will be overwritten when regenerated.

Version Information:
  CloudFormation Spec: 2025.12.11
  Generator Version: 1.0.0
  Combined: spec-2025.12.11_gen-1.0.0
  Generated: 2025-12-17 21:37:42

To regenerate this file:
    uv run python -m cloudformation_dataclasses.codegen.generator --service ElasticBeanstalk
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, ClassVar, Optional, Union

from cloudformation_dataclasses.core.base import CloudFormationResource
from cloudformation_dataclasses.intrinsics.functions import GetAtt, Ref, Sub


# =============================================================================
# Service Constants (auto-generated from botocore)
# =============================================================================

class ActionHistoryStatus:
    """ActionHistoryStatus enum values."""

    COMPLETED = "Completed"
    FAILED = "Failed"
    UNKNOWN = "Unknown"


class ActionStatus:
    """ActionStatus enum values."""

    SCHEDULED = "Scheduled"
    PENDING = "Pending"
    RUNNING = "Running"
    UNKNOWN = "Unknown"


class ActionType:
    """ActionType enum values."""

    INSTANCEREFRESH = "InstanceRefresh"
    PLATFORMUPDATE = "PlatformUpdate"
    UNKNOWN = "Unknown"


class ApplicationVersionStatus:
    """ApplicationVersionStatus enum values."""

    PROCESSED = "Processed"
    UNPROCESSED = "Unprocessed"
    FAILED = "Failed"
    PROCESSING = "Processing"
    BUILDING = "Building"


class ComputeType:
    """ComputeType enum values."""

    BUILD_GENERAL1_SMALL = "BUILD_GENERAL1_SMALL"
    BUILD_GENERAL1_MEDIUM = "BUILD_GENERAL1_MEDIUM"
    BUILD_GENERAL1_LARGE = "BUILD_GENERAL1_LARGE"


class ConfigurationDeploymentStatus:
    """ConfigurationDeploymentStatus enum values."""

    DEPLOYED = "deployed"
    PENDING = "pending"
    FAILED = "failed"


class ConfigurationOptionValueType:
    """ConfigurationOptionValueType enum values."""

    SCALAR = "Scalar"
    LIST = "List"


class EnvironmentHealth:
    """EnvironmentHealth enum values."""

    GREEN = "Green"
    YELLOW = "Yellow"
    RED = "Red"
    GREY = "Grey"


class EnvironmentHealthAttribute:
    """EnvironmentHealthAttribute enum values."""

    STATUS = "Status"
    COLOR = "Color"
    CAUSES = "Causes"
    APPLICATIONMETRICS = "ApplicationMetrics"
    INSTANCESHEALTH = "InstancesHealth"
    ALL = "All"
    HEALTHSTATUS = "HealthStatus"
    REFRESHEDAT = "RefreshedAt"


class EnvironmentHealthStatus:
    """EnvironmentHealthStatus enum values."""

    NODATA = "NoData"
    UNKNOWN = "Unknown"
    PENDING = "Pending"
    OK = "Ok"
    INFO = "Info"
    WARNING = "Warning"
    DEGRADED = "Degraded"
    SEVERE = "Severe"
    SUSPENDED = "Suspended"


class EnvironmentInfoType:
    """EnvironmentInfoType enum values."""

    TAIL = "tail"
    BUNDLE = "bundle"


class EnvironmentStatus:
    """EnvironmentStatus enum values."""

    ABORTING = "Aborting"
    LAUNCHING = "Launching"
    UPDATING = "Updating"
    LINKINGFROM = "LinkingFrom"
    LINKINGTO = "LinkingTo"
    READY = "Ready"
    TERMINATING = "Terminating"
    TERMINATED = "Terminated"


class EventSeverity:
    """EventSeverity enum values."""

    TRACE = "TRACE"
    DEBUG = "DEBUG"
    INFO = "INFO"
    WARN = "WARN"
    ERROR = "ERROR"
    FATAL = "FATAL"


class FailureType:
    """FailureType enum values."""

    UPDATECANCELLED = "UpdateCancelled"
    CANCELLATIONFAILED = "CancellationFailed"
    ROLLBACKFAILED = "RollbackFailed"
    ROLLBACKSUCCESSFUL = "RollbackSuccessful"
    INTERNALFAILURE = "InternalFailure"
    INVALIDENVIRONMENTSTATE = "InvalidEnvironmentState"
    PERMISSIONSERROR = "PermissionsError"


class InstancesHealthAttribute:
    """InstancesHealthAttribute enum values."""

    HEALTHSTATUS = "HealthStatus"
    COLOR = "Color"
    CAUSES = "Causes"
    APPLICATIONMETRICS = "ApplicationMetrics"
    REFRESHEDAT = "RefreshedAt"
    LAUNCHEDAT = "LaunchedAt"
    SYSTEM = "System"
    DEPLOYMENT = "Deployment"
    AVAILABILITYZONE = "AvailabilityZone"
    INSTANCETYPE = "InstanceType"
    ALL = "All"


class PlatformStatus:
    """PlatformStatus enum values."""

    CREATING = "Creating"
    FAILED = "Failed"
    READY = "Ready"
    DELETING = "Deleting"
    DELETED = "Deleted"


class SourceRepository:
    """SourceRepository enum values."""

    CODECOMMIT = "CodeCommit"
    S3 = "S3"


class SourceType:
    """SourceType enum values."""

    GIT = "Git"
    ZIP = "Zip"


class ValidationSeverity:
    """ValidationSeverity enum values."""

    ERROR = "error"
    WARNING = "warning"


# Convenient aliases for enum values
COMPLETED = ActionHistoryStatus.COMPLETED
FAILED = ActionHistoryStatus.FAILED
UNKNOWN = ActionHistoryStatus.UNKNOWN
SCHEDULED = ActionStatus.SCHEDULED
PENDING = ActionStatus.PENDING
RUNNING = ActionStatus.RUNNING
UNKNOWN = ActionStatus.UNKNOWN
INSTANCEREFRESH = ActionType.INSTANCEREFRESH
PLATFORMUPDATE = ActionType.PLATFORMUPDATE
UNKNOWN = ActionType.UNKNOWN
PROCESSED = ApplicationVersionStatus.PROCESSED
UNPROCESSED = ApplicationVersionStatus.UNPROCESSED
FAILED = ApplicationVersionStatus.FAILED
PROCESSING = ApplicationVersionStatus.PROCESSING
BUILDING = ApplicationVersionStatus.BUILDING
BUILD_GENERAL1_SMALL = ComputeType.BUILD_GENERAL1_SMALL
BUILD_GENERAL1_MEDIUM = ComputeType.BUILD_GENERAL1_MEDIUM
BUILD_GENERAL1_LARGE = ComputeType.BUILD_GENERAL1_LARGE
DEPLOYED = ConfigurationDeploymentStatus.DEPLOYED
PENDING = ConfigurationDeploymentStatus.PENDING
FAILED = ConfigurationDeploymentStatus.FAILED
SCALAR = ConfigurationOptionValueType.SCALAR
LIST = ConfigurationOptionValueType.LIST
GREEN = EnvironmentHealth.GREEN
YELLOW = EnvironmentHealth.YELLOW
RED = EnvironmentHealth.RED
GREY = EnvironmentHealth.GREY
STATUS = EnvironmentHealthAttribute.STATUS
COLOR = EnvironmentHealthAttribute.COLOR
CAUSES = EnvironmentHealthAttribute.CAUSES
APPLICATIONMETRICS = EnvironmentHealthAttribute.APPLICATIONMETRICS
INSTANCESHEALTH = EnvironmentHealthAttribute.INSTANCESHEALTH
ALL = EnvironmentHealthAttribute.ALL
HEALTHSTATUS = EnvironmentHealthAttribute.HEALTHSTATUS
REFRESHEDAT = EnvironmentHealthAttribute.REFRESHEDAT
NODATA = EnvironmentHealthStatus.NODATA
UNKNOWN = EnvironmentHealthStatus.UNKNOWN
PENDING = EnvironmentHealthStatus.PENDING
OK = EnvironmentHealthStatus.OK
INFO = EnvironmentHealthStatus.INFO
WARNING = EnvironmentHealthStatus.WARNING
DEGRADED = EnvironmentHealthStatus.DEGRADED
SEVERE = EnvironmentHealthStatus.SEVERE
SUSPENDED = EnvironmentHealthStatus.SUSPENDED
TAIL = EnvironmentInfoType.TAIL
BUNDLE = EnvironmentInfoType.BUNDLE
ABORTING = EnvironmentStatus.ABORTING
LAUNCHING = EnvironmentStatus.LAUNCHING
UPDATING = EnvironmentStatus.UPDATING
LINKINGFROM = EnvironmentStatus.LINKINGFROM
LINKINGTO = EnvironmentStatus.LINKINGTO
READY = EnvironmentStatus.READY
TERMINATING = EnvironmentStatus.TERMINATING
TERMINATED = EnvironmentStatus.TERMINATED
TRACE = EventSeverity.TRACE
DEBUG = EventSeverity.DEBUG
INFO = EventSeverity.INFO
WARN = EventSeverity.WARN
ERROR = EventSeverity.ERROR
FATAL = EventSeverity.FATAL
UPDATECANCELLED = FailureType.UPDATECANCELLED
CANCELLATIONFAILED = FailureType.CANCELLATIONFAILED
ROLLBACKFAILED = FailureType.ROLLBACKFAILED
ROLLBACKSUCCESSFUL = FailureType.ROLLBACKSUCCESSFUL
INTERNALFAILURE = FailureType.INTERNALFAILURE
INVALIDENVIRONMENTSTATE = FailureType.INVALIDENVIRONMENTSTATE
PERMISSIONSERROR = FailureType.PERMISSIONSERROR
HEALTHSTATUS = InstancesHealthAttribute.HEALTHSTATUS
COLOR = InstancesHealthAttribute.COLOR
CAUSES = InstancesHealthAttribute.CAUSES
APPLICATIONMETRICS = InstancesHealthAttribute.APPLICATIONMETRICS
REFRESHEDAT = InstancesHealthAttribute.REFRESHEDAT
LAUNCHEDAT = InstancesHealthAttribute.LAUNCHEDAT
SYSTEM = InstancesHealthAttribute.SYSTEM
DEPLOYMENT = InstancesHealthAttribute.DEPLOYMENT
AVAILABILITYZONE = InstancesHealthAttribute.AVAILABILITYZONE
INSTANCETYPE = InstancesHealthAttribute.INSTANCETYPE
ALL = InstancesHealthAttribute.ALL
CREATING = PlatformStatus.CREATING
FAILED = PlatformStatus.FAILED
READY = PlatformStatus.READY
DELETING = PlatformStatus.DELETING
DELETED = PlatformStatus.DELETED
CODECOMMIT = SourceRepository.CODECOMMIT
S3 = SourceRepository.S3
GIT = SourceType.GIT
ZIP = SourceType.ZIP
ERROR = ValidationSeverity.ERROR
WARNING = ValidationSeverity.WARNING


@dataclass
class ApplicationResourceLifecycleConfig:
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ela"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "service_role": "ServiceRole",
        "version_lifecycle_config": "VersionLifecycleConfig",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    service_role: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    version_lifecycle_config: Optional[ApplicationVersionLifecycleConfig] = None

    def _serialize_value(self, value: Any) -> Any:
        """Recursively serialize a value."""
        if hasattr(value, 'to_dict'):
            return value.to_dict()
        if isinstance(value, list):
            return [self._serialize_value(item) for item in value]
        if isinstance(value, dict):
            return {k: self._serialize_value(v) for k, v in value.items()}
        return value

    def to_dict(self) -> dict[str, Any]:
        """Serialize to CloudFormation format."""
        props: dict[str, Any] = {}
        for field_name, cf_name in self._property_mappings.items():
            value = getattr(self, field_name, None)
            if value is not None:
                props[cf_name] = self._serialize_value(value)
        return props


@dataclass
class ApplicationVersionLifecycleConfig:
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ela"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "max_count_rule": "MaxCountRule",
        "max_age_rule": "MaxAgeRule",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    max_count_rule: Optional[MaxCountRule] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    max_age_rule: Optional[MaxAgeRule] = None

    def _serialize_value(self, value: Any) -> Any:
        """Recursively serialize a value."""
        if hasattr(value, 'to_dict'):
            return value.to_dict()
        if isinstance(value, list):
            return [self._serialize_value(item) for item in value]
        if isinstance(value, dict):
            return {k: self._serialize_value(v) for k, v in value.items()}
        return value

    def to_dict(self) -> dict[str, Any]:
        """Serialize to CloudFormation format."""
        props: dict[str, Any] = {}
        for field_name, cf_name in self._property_mappings.items():
            value = getattr(self, field_name, None)
            if value is not None:
                props[cf_name] = self._serialize_value(value)
        return props


@dataclass
class MaxAgeRule:
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ela"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "delete_source_from_s3": "DeleteSourceFromS3",
        "max_age_in_days": "MaxAgeInDays",
        "enabled": "Enabled",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    delete_source_from_s3: Optional[Union[bool, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    max_age_in_days: Optional[Union[int, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    enabled: Optional[Union[bool, Ref, GetAtt, Sub]] = None

    def _serialize_value(self, value: Any) -> Any:
        """Recursively serialize a value."""
        if hasattr(value, 'to_dict'):
            return value.to_dict()
        if isinstance(value, list):
            return [self._serialize_value(item) for item in value]
        if isinstance(value, dict):
            return {k: self._serialize_value(v) for k, v in value.items()}
        return value

    def to_dict(self) -> dict[str, Any]:
        """Serialize to CloudFormation format."""
        props: dict[str, Any] = {}
        for field_name, cf_name in self._property_mappings.items():
            value = getattr(self, field_name, None)
            if value is not None:
                props[cf_name] = self._serialize_value(value)
        return props


@dataclass
class MaxCountRule:
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ela"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "delete_source_from_s3": "DeleteSourceFromS3",
        "enabled": "Enabled",
        "max_count": "MaxCount",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    delete_source_from_s3: Optional[Union[bool, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    enabled: Optional[Union[bool, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    max_count: Optional[Union[int, Ref, GetAtt, Sub]] = None

    def _serialize_value(self, value: Any) -> Any:
        """Recursively serialize a value."""
        if hasattr(value, 'to_dict'):
            return value.to_dict()
        if isinstance(value, list):
            return [self._serialize_value(item) for item in value]
        if isinstance(value, dict):
            return {k: self._serialize_value(v) for k, v in value.items()}
        return value

    def to_dict(self) -> dict[str, Any]:
        """Serialize to CloudFormation format."""
        props: dict[str, Any] = {}
        for field_name, cf_name in self._property_mappings.items():
            value = getattr(self, field_name, None)
            if value is not None:
                props[cf_name] = self._serialize_value(value)
        return props


@dataclass
class Application(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elast"""

    resource_type: ClassVar[str] = "AWS::ElasticBeanstalk::Application"
    _property_mappings: ClassVar[dict[str, str]] = {
        "application_name": "ApplicationName",
        "description": "Description",
        "resource_lifecycle_config": "ResourceLifecycleConfig",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    application_name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    description: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    resource_lifecycle_config: Optional[ApplicationResourceLifecycleConfig] = None



@dataclass
class SourceBundle:
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ela"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "s3_bucket": "S3Bucket",
        "s3_key": "S3Key",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    s3_bucket: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    s3_key: Optional[Union[str, Ref, GetAtt, Sub]] = None

    def _serialize_value(self, value: Any) -> Any:
        """Recursively serialize a value."""
        if hasattr(value, 'to_dict'):
            return value.to_dict()
        if isinstance(value, list):
            return [self._serialize_value(item) for item in value]
        if isinstance(value, dict):
            return {k: self._serialize_value(v) for k, v in value.items()}
        return value

    def to_dict(self) -> dict[str, Any]:
        """Serialize to CloudFormation format."""
        props: dict[str, Any] = {}
        for field_name, cf_name in self._property_mappings.items():
            value = getattr(self, field_name, None)
            if value is not None:
                props[cf_name] = self._serialize_value(value)
        return props


@dataclass
class ApplicationVersion(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elast"""

    resource_type: ClassVar[str] = "AWS::ElasticBeanstalk::ApplicationVersion"
    _property_mappings: ClassVar[dict[str, str]] = {
        "application_name": "ApplicationName",
        "description": "Description",
        "source_bundle": "SourceBundle",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    application_name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    description: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    source_bundle: Optional[SourceBundle] = None

    @property
    def attr_id(self) -> GetAtt:
        """Get the Id attribute."""
        return self.get_att("Id")




@dataclass
class ConfigurationOptionSetting:
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ela"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "resource_name": "ResourceName",
        "value": "Value",
        "namespace": "Namespace",
        "option_name": "OptionName",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    resource_name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    value: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    namespace: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    option_name: Optional[Union[str, Ref, GetAtt, Sub]] = None

    def _serialize_value(self, value: Any) -> Any:
        """Recursively serialize a value."""
        if hasattr(value, 'to_dict'):
            return value.to_dict()
        if isinstance(value, list):
            return [self._serialize_value(item) for item in value]
        if isinstance(value, dict):
            return {k: self._serialize_value(v) for k, v in value.items()}
        return value

    def to_dict(self) -> dict[str, Any]:
        """Serialize to CloudFormation format."""
        props: dict[str, Any] = {}
        for field_name, cf_name in self._property_mappings.items():
            value = getattr(self, field_name, None)
            if value is not None:
                props[cf_name] = self._serialize_value(value)
        return props


@dataclass
class SourceConfiguration:
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ela"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "application_name": "ApplicationName",
        "template_name": "TemplateName",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    application_name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    template_name: Optional[Union[str, Ref, GetAtt, Sub]] = None

    def _serialize_value(self, value: Any) -> Any:
        """Recursively serialize a value."""
        if hasattr(value, 'to_dict'):
            return value.to_dict()
        if isinstance(value, list):
            return [self._serialize_value(item) for item in value]
        if isinstance(value, dict):
            return {k: self._serialize_value(v) for k, v in value.items()}
        return value

    def to_dict(self) -> dict[str, Any]:
        """Serialize to CloudFormation format."""
        props: dict[str, Any] = {}
        for field_name, cf_name in self._property_mappings.items():
            value = getattr(self, field_name, None)
            if value is not None:
                props[cf_name] = self._serialize_value(value)
        return props


@dataclass
class ConfigurationTemplate(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elast"""

    resource_type: ClassVar[str] = "AWS::ElasticBeanstalk::ConfigurationTemplate"
    _property_mappings: ClassVar[dict[str, str]] = {
        "environment_id": "EnvironmentId",
        "platform_arn": "PlatformArn",
        "application_name": "ApplicationName",
        "description": "Description",
        "option_settings": "OptionSettings",
        "source_configuration": "SourceConfiguration",
        "solution_stack_name": "SolutionStackName",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    environment_id: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    platform_arn: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    application_name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    description: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    option_settings: Optional[list[ConfigurationOptionSetting]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    source_configuration: Optional[SourceConfiguration] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    solution_stack_name: Optional[Union[str, Ref, GetAtt, Sub]] = None

    @property
    def attr_template_name(self) -> GetAtt:
        """Get the TemplateName attribute."""
        return self.get_att("TemplateName")




@dataclass
class OptionSetting:
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ela"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "resource_name": "ResourceName",
        "value": "Value",
        "namespace": "Namespace",
        "option_name": "OptionName",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    resource_name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    value: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    namespace: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    option_name: Optional[Union[str, Ref, GetAtt, Sub]] = None

    def _serialize_value(self, value: Any) -> Any:
        """Recursively serialize a value."""
        if hasattr(value, 'to_dict'):
            return value.to_dict()
        if isinstance(value, list):
            return [self._serialize_value(item) for item in value]
        if isinstance(value, dict):
            return {k: self._serialize_value(v) for k, v in value.items()}
        return value

    def to_dict(self) -> dict[str, Any]:
        """Serialize to CloudFormation format."""
        props: dict[str, Any] = {}
        for field_name, cf_name in self._property_mappings.items():
            value = getattr(self, field_name, None)
            if value is not None:
                props[cf_name] = self._serialize_value(value)
        return props


@dataclass
class Tier:
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ela"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "type_": "Type",
        "version": "Version",
        "name": "Name",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    type_: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    version: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    name: Optional[Union[str, Ref, GetAtt, Sub]] = None

    def _serialize_value(self, value: Any) -> Any:
        """Recursively serialize a value."""
        if hasattr(value, 'to_dict'):
            return value.to_dict()
        if isinstance(value, list):
            return [self._serialize_value(item) for item in value]
        if isinstance(value, dict):
            return {k: self._serialize_value(v) for k, v in value.items()}
        return value

    def to_dict(self) -> dict[str, Any]:
        """Serialize to CloudFormation format."""
        props: dict[str, Any] = {}
        for field_name, cf_name in self._property_mappings.items():
            value = getattr(self, field_name, None)
            if value is not None:
                props[cf_name] = self._serialize_value(value)
        return props


@dataclass
class Environment(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elast"""

    resource_type: ClassVar[str] = "AWS::ElasticBeanstalk::Environment"
    _property_mappings: ClassVar[dict[str, str]] = {
        "platform_arn": "PlatformArn",
        "application_name": "ApplicationName",
        "description": "Description",
        "environment_name": "EnvironmentName",
        "operations_role": "OperationsRole",
        "tier": "Tier",
        "option_settings": "OptionSettings",
        "version_label": "VersionLabel",
        "template_name": "TemplateName",
        "solution_stack_name": "SolutionStackName",
        "cname_prefix": "CNAMEPrefix",
        "tags": "Tags",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    platform_arn: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    application_name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    description: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    environment_name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    operations_role: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    tier: Optional[Tier] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    option_settings: Optional[list[OptionSetting]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    version_label: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    template_name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    solution_stack_name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    cname_prefix: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    tags: Optional[list[Tag]] = None

    @property
    def attr_endpoint_url(self) -> GetAtt:
        """Get the EndpointURL attribute."""
        return self.get_att("EndpointURL")



