"""
AWS CloudFormation IVSChat Resources

⚠️  AUTO-GENERATED FILE - DO NOT EDIT MANUALLY ⚠️

This file is automatically generated from the AWS CloudFormation Resource Specification.
Any manual changes will be overwritten when regenerated.

Version Information:
  CloudFormation Spec: 2025.12.11
  Generator Version: 1.0.0
  Combined: spec-2025.12.11_gen-1.0.0
  Generated: 2025-12-17 21:43:45

To regenerate this file:
    uv run python -m cloudformation_dataclasses.codegen.generator --service IVSChat
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, ClassVar, Optional, Union

from cloudformation_dataclasses.core.base import CloudFormationResource, PropertyType
from cloudformation_dataclasses.intrinsics.functions import GetAtt, Ref, Sub


# =============================================================================
# Service Constants (auto-generated from botocore)
# =============================================================================

class ChatTokenCapability:
    """ChatTokenCapability enum values."""

    SEND_MESSAGE = "SEND_MESSAGE"
    DISCONNECT_USER = "DISCONNECT_USER"
    DELETE_MESSAGE = "DELETE_MESSAGE"


class CreateLoggingConfigurationState:
    """CreateLoggingConfigurationState enum values."""

    ACTIVE = "ACTIVE"


class FallbackResult:
    """FallbackResult enum values."""

    ALLOW = "ALLOW"
    DENY = "DENY"


class LoggingConfigurationState:
    """LoggingConfigurationState enum values."""

    CREATING = "CREATING"
    CREATE_FAILED = "CREATE_FAILED"
    DELETING = "DELETING"
    DELETE_FAILED = "DELETE_FAILED"
    UPDATING = "UPDATING"
    UPDATE_FAILED = "UPDATE_FAILED"
    ACTIVE = "ACTIVE"


class ResourceType:
    """ResourceType enum values."""

    ROOM = "ROOM"


class UpdateLoggingConfigurationState:
    """UpdateLoggingConfigurationState enum values."""

    ACTIVE = "ACTIVE"


class ValidationExceptionReason:
    """ValidationExceptionReason enum values."""

    UNKNOWN_OPERATION = "UNKNOWN_OPERATION"
    FIELD_VALIDATION_FAILED = "FIELD_VALIDATION_FAILED"
    OTHER = "OTHER"


# Convenient aliases for enum values
SEND_MESSAGE = ChatTokenCapability.SEND_MESSAGE
DISCONNECT_USER = ChatTokenCapability.DISCONNECT_USER
DELETE_MESSAGE = ChatTokenCapability.DELETE_MESSAGE
ACTIVE = CreateLoggingConfigurationState.ACTIVE
ALLOW = FallbackResult.ALLOW
DENY = FallbackResult.DENY
CREATING = LoggingConfigurationState.CREATING
CREATE_FAILED = LoggingConfigurationState.CREATE_FAILED
DELETING = LoggingConfigurationState.DELETING
DELETE_FAILED = LoggingConfigurationState.DELETE_FAILED
UPDATING = LoggingConfigurationState.UPDATING
UPDATE_FAILED = LoggingConfigurationState.UPDATE_FAILED
ACTIVE = LoggingConfigurationState.ACTIVE
ROOM = ResourceType.ROOM
ACTIVE = UpdateLoggingConfigurationState.ACTIVE
UNKNOWN_OPERATION = ValidationExceptionReason.UNKNOWN_OPERATION
FIELD_VALIDATION_FAILED = ValidationExceptionReason.FIELD_VALIDATION_FAILED
OTHER = ValidationExceptionReason.OTHER


@dataclass
class CloudWatchLogsDestinationConfiguration(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ivs"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "log_group_name": "LogGroupName",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    log_group_name: Optional[Union[str, Ref, GetAtt, Sub]] = None


@dataclass
class DestinationConfiguration(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ivs"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "s3": "S3",
        "firehose": "Firehose",
        "cloud_watch_logs": "CloudWatchLogs",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    s3: Optional[S3DestinationConfiguration] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    firehose: Optional[FirehoseDestinationConfiguration] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    cloud_watch_logs: Optional[CloudWatchLogsDestinationConfiguration] = None


@dataclass
class FirehoseDestinationConfiguration(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ivs"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "delivery_stream_name": "DeliveryStreamName",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    delivery_stream_name: Optional[Union[str, Ref, GetAtt, Sub]] = None


@dataclass
class S3DestinationConfiguration(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ivs"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "bucket_name": "BucketName",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    bucket_name: Optional[Union[str, Ref, GetAtt, Sub]] = None


@dataclass
class LoggingConfiguration(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ivsch"""

    resource_type: ClassVar[str] = "AWS::IVSChat::LoggingConfiguration"
    _property_mappings: ClassVar[dict[str, str]] = {
        "destination_configuration": "DestinationConfiguration",
        "tags": "Tags",
        "name": "Name",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    destination_configuration: Optional[DestinationConfiguration] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    tags: Optional[list[Tag]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    name: Optional[Union[str, Ref, GetAtt, Sub]] = None

    @property
    def attr_state(self) -> GetAtt:
        """Get the State attribute."""
        return self.get_att("State")

    @property
    def attr_id(self) -> GetAtt:
        """Get the Id attribute."""
        return self.get_att("Id")

    @property
    def attr_arn(self) -> GetAtt:
        """Get the Arn attribute."""
        return self.get_att("Arn")




@dataclass
class MessageReviewHandler(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ivs"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "fallback_result": "FallbackResult",
        "uri": "Uri",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    fallback_result: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    uri: Optional[Union[str, Ref, GetAtt, Sub]] = None


@dataclass
class Room(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ivsch"""

    resource_type: ClassVar[str] = "AWS::IVSChat::Room"
    _property_mappings: ClassVar[dict[str, str]] = {
        "maximum_message_rate_per_second": "MaximumMessageRatePerSecond",
        "maximum_message_length": "MaximumMessageLength",
        "message_review_handler": "MessageReviewHandler",
        "logging_configuration_identifiers": "LoggingConfigurationIdentifiers",
        "tags": "Tags",
        "name": "Name",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    maximum_message_rate_per_second: Optional[Union[int, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    maximum_message_length: Optional[Union[int, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    message_review_handler: Optional[MessageReviewHandler] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    logging_configuration_identifiers: Optional[Union[list[str], Ref]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    tags: Optional[list[Tag]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    name: Optional[Union[str, Ref, GetAtt, Sub]] = None

    @property
    def attr_id(self) -> GetAtt:
        """Get the Id attribute."""
        return self.get_att("Id")

    @property
    def attr_arn(self) -> GetAtt:
        """Get the Arn attribute."""
        return self.get_att("Arn")



