"""
AWS CloudFormation ManagedBlockchain Resources

⚠️  AUTO-GENERATED FILE - DO NOT EDIT MANUALLY ⚠️

This file is automatically generated from the AWS CloudFormation Resource Specification.
Any manual changes will be overwritten when regenerated.

Version Information:
  CloudFormation Spec: 2025.12.11
  Generator Version: 1.0.0
  Combined: spec-2025.12.11_gen-1.0.0
  Generated: 2025-12-17 21:43:51

To regenerate this file:
    uv run python -m cloudformation_dataclasses.codegen.generator --service ManagedBlockchain
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, ClassVar, Optional, Union

from cloudformation_dataclasses.core.base import CloudFormationResource, PropertyType
from cloudformation_dataclasses.intrinsics.functions import GetAtt, Ref, Sub


# =============================================================================
# Service Constants (auto-generated from botocore)
# =============================================================================

class AccessorNetworkType:
    """AccessorNetworkType enum values."""

    ETHEREUM_GOERLI = "ETHEREUM_GOERLI"
    ETHEREUM_MAINNET = "ETHEREUM_MAINNET"
    ETHEREUM_MAINNET_AND_GOERLI = "ETHEREUM_MAINNET_AND_GOERLI"
    POLYGON_MAINNET = "POLYGON_MAINNET"
    POLYGON_MUMBAI = "POLYGON_MUMBAI"


class AccessorStatus:
    """AccessorStatus enum values."""

    AVAILABLE = "AVAILABLE"
    PENDING_DELETION = "PENDING_DELETION"
    DELETED = "DELETED"


class AccessorType:
    """AccessorType enum values."""

    BILLING_TOKEN = "BILLING_TOKEN"


class Edition:
    """Edition enum values."""

    STARTER = "STARTER"
    STANDARD = "STANDARD"


class Framework:
    """Framework enum values."""

    HYPERLEDGER_FABRIC = "HYPERLEDGER_FABRIC"
    ETHEREUM = "ETHEREUM"


class InvitationStatus:
    """InvitationStatus enum values."""

    PENDING = "PENDING"
    ACCEPTED = "ACCEPTED"
    ACCEPTING = "ACCEPTING"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"


class MemberStatus:
    """MemberStatus enum values."""

    CREATING = "CREATING"
    AVAILABLE = "AVAILABLE"
    CREATE_FAILED = "CREATE_FAILED"
    UPDATING = "UPDATING"
    DELETING = "DELETING"
    DELETED = "DELETED"
    INACCESSIBLE_ENCRYPTION_KEY = "INACCESSIBLE_ENCRYPTION_KEY"


class NetworkStatus:
    """NetworkStatus enum values."""

    CREATING = "CREATING"
    AVAILABLE = "AVAILABLE"
    CREATE_FAILED = "CREATE_FAILED"
    DELETING = "DELETING"
    DELETED = "DELETED"


class NodeStatus:
    """NodeStatus enum values."""

    CREATING = "CREATING"
    AVAILABLE = "AVAILABLE"
    UNHEALTHY = "UNHEALTHY"
    CREATE_FAILED = "CREATE_FAILED"
    UPDATING = "UPDATING"
    DELETING = "DELETING"
    DELETED = "DELETED"
    FAILED = "FAILED"
    INACCESSIBLE_ENCRYPTION_KEY = "INACCESSIBLE_ENCRYPTION_KEY"


class ProposalStatus:
    """ProposalStatus enum values."""

    IN_PROGRESS = "IN_PROGRESS"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"
    ACTION_FAILED = "ACTION_FAILED"


class StateDBType:
    """StateDBType enum values."""

    LEVELDB = "LevelDB"
    COUCHDB = "CouchDB"


class ThresholdComparator:
    """ThresholdComparator enum values."""

    GREATER_THAN = "GREATER_THAN"
    GREATER_THAN_OR_EQUAL_TO = "GREATER_THAN_OR_EQUAL_TO"


class VoteValue:
    """VoteValue enum values."""

    YES = "YES"
    NO = "NO"


# Convenient aliases for enum values
ETHEREUM_GOERLI = AccessorNetworkType.ETHEREUM_GOERLI
ETHEREUM_MAINNET = AccessorNetworkType.ETHEREUM_MAINNET
ETHEREUM_MAINNET_AND_GOERLI = AccessorNetworkType.ETHEREUM_MAINNET_AND_GOERLI
POLYGON_MAINNET = AccessorNetworkType.POLYGON_MAINNET
POLYGON_MUMBAI = AccessorNetworkType.POLYGON_MUMBAI
AVAILABLE = AccessorStatus.AVAILABLE
PENDING_DELETION = AccessorStatus.PENDING_DELETION
DELETED = AccessorStatus.DELETED
BILLING_TOKEN = AccessorType.BILLING_TOKEN
STARTER = Edition.STARTER
STANDARD = Edition.STANDARD
HYPERLEDGER_FABRIC = Framework.HYPERLEDGER_FABRIC
ETHEREUM = Framework.ETHEREUM
PENDING = InvitationStatus.PENDING
ACCEPTED = InvitationStatus.ACCEPTED
ACCEPTING = InvitationStatus.ACCEPTING
REJECTED = InvitationStatus.REJECTED
EXPIRED = InvitationStatus.EXPIRED
CREATING = MemberStatus.CREATING
AVAILABLE = MemberStatus.AVAILABLE
CREATE_FAILED = MemberStatus.CREATE_FAILED
UPDATING = MemberStatus.UPDATING
DELETING = MemberStatus.DELETING
DELETED = MemberStatus.DELETED
INACCESSIBLE_ENCRYPTION_KEY = MemberStatus.INACCESSIBLE_ENCRYPTION_KEY
CREATING = NetworkStatus.CREATING
AVAILABLE = NetworkStatus.AVAILABLE
CREATE_FAILED = NetworkStatus.CREATE_FAILED
DELETING = NetworkStatus.DELETING
DELETED = NetworkStatus.DELETED
CREATING = NodeStatus.CREATING
AVAILABLE = NodeStatus.AVAILABLE
UNHEALTHY = NodeStatus.UNHEALTHY
CREATE_FAILED = NodeStatus.CREATE_FAILED
UPDATING = NodeStatus.UPDATING
DELETING = NodeStatus.DELETING
DELETED = NodeStatus.DELETED
FAILED = NodeStatus.FAILED
INACCESSIBLE_ENCRYPTION_KEY = NodeStatus.INACCESSIBLE_ENCRYPTION_KEY
IN_PROGRESS = ProposalStatus.IN_PROGRESS
APPROVED = ProposalStatus.APPROVED
REJECTED = ProposalStatus.REJECTED
EXPIRED = ProposalStatus.EXPIRED
ACTION_FAILED = ProposalStatus.ACTION_FAILED
LEVELDB = StateDBType.LEVELDB
COUCHDB = StateDBType.COUCHDB
GREATER_THAN = ThresholdComparator.GREATER_THAN
GREATER_THAN_OR_EQUAL_TO = ThresholdComparator.GREATER_THAN_OR_EQUAL_TO
YES = VoteValue.YES
NO = VoteValue.NO


@dataclass
class Accessor(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-manag"""

    resource_type: ClassVar[str] = "AWS::ManagedBlockchain::Accessor"
    _property_mappings: ClassVar[dict[str, str]] = {
        "network_type": "NetworkType",
        "tags": "Tags",
        "accessor_type": "AccessorType",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    network_type: Optional[Union[str, AccessorNetworkType, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    tags: Optional[list[Tag]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    accessor_type: Optional[Union[str, Ref, GetAtt, Sub]] = None

    @property
    def attr_status(self) -> GetAtt:
        """Get the Status attribute."""
        return self.get_att("Status")

    @property
    def attr_creation_date(self) -> GetAtt:
        """Get the CreationDate attribute."""
        return self.get_att("CreationDate")

    @property
    def attr_billing_token(self) -> GetAtt:
        """Get the BillingToken attribute."""
        return self.get_att("BillingToken")

    @property
    def attr_id(self) -> GetAtt:
        """Get the Id attribute."""
        return self.get_att("Id")

    @property
    def attr_arn(self) -> GetAtt:
        """Get the Arn attribute."""
        return self.get_att("Arn")




@dataclass
class ApprovalThresholdPolicy(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-man"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "threshold_comparator": "ThresholdComparator",
        "threshold_percentage": "ThresholdPercentage",
        "proposal_duration_in_hours": "ProposalDurationInHours",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    threshold_comparator: Optional[Union[str, ThresholdComparator, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    threshold_percentage: Optional[Union[int, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    proposal_duration_in_hours: Optional[Union[int, Ref, GetAtt, Sub]] = None


@dataclass
class MemberConfiguration(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-man"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "description": "Description",
        "member_framework_configuration": "MemberFrameworkConfiguration",
        "name": "Name",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    description: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    member_framework_configuration: Optional[MemberFrameworkConfiguration] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    name: Optional[Union[str, Ref, GetAtt, Sub]] = None


@dataclass
class MemberFabricConfiguration(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-man"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "admin_username": "AdminUsername",
        "admin_password": "AdminPassword",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    admin_username: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    admin_password: Optional[Union[str, Ref, GetAtt, Sub]] = None


@dataclass
class MemberFrameworkConfiguration(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-man"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "member_fabric_configuration": "MemberFabricConfiguration",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    member_fabric_configuration: Optional[MemberFabricConfiguration] = None


@dataclass
class NetworkConfiguration(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-man"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "description": "Description",
        "framework_version": "FrameworkVersion",
        "voting_policy": "VotingPolicy",
        "framework": "Framework",
        "name": "Name",
        "network_framework_configuration": "NetworkFrameworkConfiguration",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    description: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    framework_version: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    voting_policy: Optional[VotingPolicy] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    framework: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    network_framework_configuration: Optional[NetworkFrameworkConfiguration] = None


@dataclass
class NetworkFabricConfiguration(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-man"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "edition": "Edition",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    edition: Optional[Union[str, Edition, Ref, GetAtt, Sub]] = None


@dataclass
class NetworkFrameworkConfiguration(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-man"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "network_fabric_configuration": "NetworkFabricConfiguration",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    network_fabric_configuration: Optional[NetworkFabricConfiguration] = None


@dataclass
class VotingPolicy(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-man"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "approval_threshold_policy": "ApprovalThresholdPolicy",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    approval_threshold_policy: Optional[ApprovalThresholdPolicy] = None


@dataclass
class Member(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-manag"""

    resource_type: ClassVar[str] = "AWS::ManagedBlockchain::Member"
    _property_mappings: ClassVar[dict[str, str]] = {
        "member_configuration": "MemberConfiguration",
        "network_configuration": "NetworkConfiguration",
        "network_id": "NetworkId",
        "invitation_id": "InvitationId",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    member_configuration: Optional[MemberConfiguration] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    network_configuration: Optional[NetworkConfiguration] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    network_id: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    invitation_id: Optional[Union[str, Ref, GetAtt, Sub]] = None

    @property
    def attr_member_id(self) -> GetAtt:
        """Get the MemberId attribute."""
        return self.get_att("MemberId")

    @property
    def attr_network_id(self) -> GetAtt:
        """Get the NetworkId attribute."""
        return self.get_att("NetworkId")




@dataclass
class NodeConfiguration(PropertyType):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-man"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "availability_zone": "AvailabilityZone",
        "instance_type": "InstanceType",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    availability_zone: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    instance_type: Optional[Union[str, Ref, GetAtt, Sub]] = None


@dataclass
class Node(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-manag"""

    resource_type: ClassVar[str] = "AWS::ManagedBlockchain::Node"
    _property_mappings: ClassVar[dict[str, str]] = {
        "member_id": "MemberId",
        "network_id": "NetworkId",
        "node_configuration": "NodeConfiguration",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    member_id: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    network_id: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    node_configuration: Optional[NodeConfiguration] = None

    @property
    def attr_member_id(self) -> GetAtt:
        """Get the MemberId attribute."""
        return self.get_att("MemberId")

    @property
    def attr_node_id(self) -> GetAtt:
        """Get the NodeId attribute."""
        return self.get_att("NodeId")

    @property
    def attr_arn(self) -> GetAtt:
        """Get the Arn attribute."""
        return self.get_att("Arn")

    @property
    def attr_network_id(self) -> GetAtt:
        """Get the NetworkId attribute."""
        return self.get_att("NetworkId")



