"""
AWS CloudFormation Shield Resources

⚠️  AUTO-GENERATED FILE - DO NOT EDIT MANUALLY ⚠️

This file is automatically generated from the AWS CloudFormation Resource Specification.
Any manual changes will be overwritten when regenerated.

Version Information:
  CloudFormation Spec: 2025.12.11
  Generator Version: 1.0.0
  Combined: spec-2025.12.11_gen-1.0.0
  Generated: 2025-12-17 21:38:04

To regenerate this file:
    uv run python -m cloudformation_dataclasses.codegen.generator --service Shield
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, ClassVar, Optional, Union

from cloudformation_dataclasses.core.base import CloudFormationResource
from cloudformation_dataclasses.intrinsics.functions import GetAtt, Ref, Sub


# =============================================================================
# Service Constants (auto-generated from botocore)
# =============================================================================

class ApplicationLayerAutomaticResponseStatus:
    """ApplicationLayerAutomaticResponseStatus enum values."""

    ENABLED = "ENABLED"
    DISABLED = "DISABLED"


class AttackLayer:
    """AttackLayer enum values."""

    NETWORK = "NETWORK"
    APPLICATION = "APPLICATION"


class AttackPropertyIdentifier:
    """AttackPropertyIdentifier enum values."""

    DESTINATION_URL = "DESTINATION_URL"
    REFERRER = "REFERRER"
    SOURCE_ASN = "SOURCE_ASN"
    SOURCE_COUNTRY = "SOURCE_COUNTRY"
    SOURCE_IP_ADDRESS = "SOURCE_IP_ADDRESS"
    SOURCE_USER_AGENT = "SOURCE_USER_AGENT"
    WORDPRESS_PINGBACK_REFLECTOR = "WORDPRESS_PINGBACK_REFLECTOR"
    WORDPRESS_PINGBACK_SOURCE = "WORDPRESS_PINGBACK_SOURCE"


class AutoRenew:
    """AutoRenew enum values."""

    ENABLED = "ENABLED"
    DISABLED = "DISABLED"


class ProactiveEngagementStatus:
    """ProactiveEngagementStatus enum values."""

    ENABLED = "ENABLED"
    DISABLED = "DISABLED"
    PENDING = "PENDING"


class ProtectedResourceType:
    """ProtectedResourceType enum values."""

    CLOUDFRONT_DISTRIBUTION = "CLOUDFRONT_DISTRIBUTION"
    ROUTE_53_HOSTED_ZONE = "ROUTE_53_HOSTED_ZONE"
    ELASTIC_IP_ALLOCATION = "ELASTIC_IP_ALLOCATION"
    CLASSIC_LOAD_BALANCER = "CLASSIC_LOAD_BALANCER"
    APPLICATION_LOAD_BALANCER = "APPLICATION_LOAD_BALANCER"
    GLOBAL_ACCELERATOR = "GLOBAL_ACCELERATOR"


class ProtectionGroupAggregation:
    """ProtectionGroupAggregation enum values."""

    SUM = "SUM"
    MEAN = "MEAN"
    MAX = "MAX"


class ProtectionGroupPattern:
    """ProtectionGroupPattern enum values."""

    ALL = "ALL"
    ARBITRARY = "ARBITRARY"
    BY_RESOURCE_TYPE = "BY_RESOURCE_TYPE"


class SubResourceType:
    """SubResourceType enum values."""

    IP = "IP"
    URL = "URL"


class SubscriptionState:
    """SubscriptionState enum values."""

    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"


class Unit:
    """Unit enum values."""

    BITS = "BITS"
    BYTES = "BYTES"
    PACKETS = "PACKETS"
    REQUESTS = "REQUESTS"


class ValidationExceptionReason:
    """ValidationExceptionReason enum values."""

    FIELD_VALIDATION_FAILED = "FIELD_VALIDATION_FAILED"
    OTHER = "OTHER"


# Convenient aliases for enum values
ENABLED = ApplicationLayerAutomaticResponseStatus.ENABLED
DISABLED = ApplicationLayerAutomaticResponseStatus.DISABLED
NETWORK = AttackLayer.NETWORK
APPLICATION = AttackLayer.APPLICATION
DESTINATION_URL = AttackPropertyIdentifier.DESTINATION_URL
REFERRER = AttackPropertyIdentifier.REFERRER
SOURCE_ASN = AttackPropertyIdentifier.SOURCE_ASN
SOURCE_COUNTRY = AttackPropertyIdentifier.SOURCE_COUNTRY
SOURCE_IP_ADDRESS = AttackPropertyIdentifier.SOURCE_IP_ADDRESS
SOURCE_USER_AGENT = AttackPropertyIdentifier.SOURCE_USER_AGENT
WORDPRESS_PINGBACK_REFLECTOR = AttackPropertyIdentifier.WORDPRESS_PINGBACK_REFLECTOR
WORDPRESS_PINGBACK_SOURCE = AttackPropertyIdentifier.WORDPRESS_PINGBACK_SOURCE
ENABLED = AutoRenew.ENABLED
DISABLED = AutoRenew.DISABLED
ENABLED = ProactiveEngagementStatus.ENABLED
DISABLED = ProactiveEngagementStatus.DISABLED
PENDING = ProactiveEngagementStatus.PENDING
CLOUDFRONT_DISTRIBUTION = ProtectedResourceType.CLOUDFRONT_DISTRIBUTION
ROUTE_53_HOSTED_ZONE = ProtectedResourceType.ROUTE_53_HOSTED_ZONE
ELASTIC_IP_ALLOCATION = ProtectedResourceType.ELASTIC_IP_ALLOCATION
CLASSIC_LOAD_BALANCER = ProtectedResourceType.CLASSIC_LOAD_BALANCER
APPLICATION_LOAD_BALANCER = ProtectedResourceType.APPLICATION_LOAD_BALANCER
GLOBAL_ACCELERATOR = ProtectedResourceType.GLOBAL_ACCELERATOR
SUM = ProtectionGroupAggregation.SUM
MEAN = ProtectionGroupAggregation.MEAN
MAX = ProtectionGroupAggregation.MAX
ALL = ProtectionGroupPattern.ALL
ARBITRARY = ProtectionGroupPattern.ARBITRARY
BY_RESOURCE_TYPE = ProtectionGroupPattern.BY_RESOURCE_TYPE
IP = SubResourceType.IP
URL = SubResourceType.URL
ACTIVE = SubscriptionState.ACTIVE
INACTIVE = SubscriptionState.INACTIVE
BITS = Unit.BITS
BYTES = Unit.BYTES
PACKETS = Unit.PACKETS
REQUESTS = Unit.REQUESTS
FIELD_VALIDATION_FAILED = ValidationExceptionReason.FIELD_VALIDATION_FAILED
OTHER = ValidationExceptionReason.OTHER


@dataclass
class DRTAccess(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-shiel"""

    resource_type: ClassVar[str] = "AWS::Shield::DRTAccess"
    _property_mappings: ClassVar[dict[str, str]] = {
        "log_bucket_list": "LogBucketList",
        "role_arn": "RoleArn",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    log_bucket_list: Optional[Union[list[str], Ref]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    role_arn: Optional[Union[str, Ref, GetAtt, Sub]] = None

    @property
    def attr_account_id(self) -> GetAtt:
        """Get the AccountId attribute."""
        return self.get_att("AccountId")




@dataclass
class EmergencyContact:
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-shi"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "contact_notes": "ContactNotes",
        "phone_number": "PhoneNumber",
        "email_address": "EmailAddress",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    contact_notes: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    phone_number: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    email_address: Optional[Union[str, Ref, GetAtt, Sub]] = None

    def _serialize_value(self, value: Any) -> Any:
        """Recursively serialize a value."""
        if hasattr(value, 'to_dict'):
            return value.to_dict()
        if isinstance(value, list):
            return [self._serialize_value(item) for item in value]
        if isinstance(value, dict):
            return {k: self._serialize_value(v) for k, v in value.items()}
        return value

    def to_dict(self) -> dict[str, Any]:
        """Serialize to CloudFormation format."""
        props: dict[str, Any] = {}
        for field_name, cf_name in self._property_mappings.items():
            value = getattr(self, field_name, None)
            if value is not None:
                props[cf_name] = self._serialize_value(value)
        return props


@dataclass
class ProactiveEngagement(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-shiel"""

    resource_type: ClassVar[str] = "AWS::Shield::ProactiveEngagement"
    _property_mappings: ClassVar[dict[str, str]] = {
        "proactive_engagement_status": "ProactiveEngagementStatus",
        "emergency_contact_list": "EmergencyContactList",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    proactive_engagement_status: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    emergency_contact_list: Optional[list[EmergencyContact]] = None

    @property
    def attr_account_id(self) -> GetAtt:
        """Get the AccountId attribute."""
        return self.get_att("AccountId")




@dataclass
class Action:
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-shi"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "block": "Block",
        "count": "Count",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    block: Optional[Union[dict[str, Any], Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    count: Optional[Union[dict[str, Any], Ref, GetAtt, Sub]] = None

    def _serialize_value(self, value: Any) -> Any:
        """Recursively serialize a value."""
        if hasattr(value, 'to_dict'):
            return value.to_dict()
        if isinstance(value, list):
            return [self._serialize_value(item) for item in value]
        if isinstance(value, dict):
            return {k: self._serialize_value(v) for k, v in value.items()}
        return value

    def to_dict(self) -> dict[str, Any]:
        """Serialize to CloudFormation format."""
        props: dict[str, Any] = {}
        for field_name, cf_name in self._property_mappings.items():
            value = getattr(self, field_name, None)
            if value is not None:
                props[cf_name] = self._serialize_value(value)
        return props


@dataclass
class ApplicationLayerAutomaticResponseConfiguration:
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-shi"""

    _property_mappings: ClassVar[dict[str, str]] = {
        "status": "Status",
        "action": "Action",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    status: Optional[Union[str, ApplicationLayerAutomaticResponseStatus, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    action: Optional[Action] = None

    def _serialize_value(self, value: Any) -> Any:
        """Recursively serialize a value."""
        if hasattr(value, 'to_dict'):
            return value.to_dict()
        if isinstance(value, list):
            return [self._serialize_value(item) for item in value]
        if isinstance(value, dict):
            return {k: self._serialize_value(v) for k, v in value.items()}
        return value

    def to_dict(self) -> dict[str, Any]:
        """Serialize to CloudFormation format."""
        props: dict[str, Any] = {}
        for field_name, cf_name in self._property_mappings.items():
            value = getattr(self, field_name, None)
            if value is not None:
                props[cf_name] = self._serialize_value(value)
        return props


@dataclass
class Protection(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-shiel"""

    resource_type: ClassVar[str] = "AWS::Shield::Protection"
    _property_mappings: ClassVar[dict[str, str]] = {
        "resource_arn": "ResourceArn",
        "health_check_arns": "HealthCheckArns",
        "application_layer_automatic_response_configuration": "ApplicationLayerAutomaticResponseConfiguration",
        "tags": "Tags",
        "name": "Name",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    resource_arn: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    health_check_arns: Optional[Union[list[str], Ref]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    application_layer_automatic_response_configuration: Optional[ApplicationLayerAutomaticResponseConfiguration] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    tags: Optional[list[Tag]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    name: Optional[Union[str, Ref, GetAtt, Sub]] = None

    @property
    def attr_protection_arn(self) -> GetAtt:
        """Get the ProtectionArn attribute."""
        return self.get_att("ProtectionArn")

    @property
    def attr_protection_id(self) -> GetAtt:
        """Get the ProtectionId attribute."""
        return self.get_att("ProtectionId")




@dataclass
class ProtectionGroup(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-shiel"""

    resource_type: ClassVar[str] = "AWS::Shield::ProtectionGroup"
    _property_mappings: ClassVar[dict[str, str]] = {
        "aggregation": "Aggregation",
        "pattern": "Pattern",
        "protection_group_id": "ProtectionGroupId",
        "resource_type": "ResourceType",
        "members": "Members",
        "tags": "Tags",
    }

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    aggregation: Optional[Union[str, ProtectionGroupAggregation, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    pattern: Optional[Union[str, ProtectionGroupPattern, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    protection_group_id: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    resource_type: Optional[Union[str, ProtectedResourceType, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    members: Optional[Union[list[str], Ref]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    tags: Optional[list[Tag]] = None

    @property
    def attr_protection_group_arn(self) -> GetAtt:
        """Get the ProtectionGroupArn attribute."""
        return self.get_att("ProtectionGroupArn")



