"""Installing Cloudformation helper scripts in RHEL 9

Generated by cfn-dataclasses-import."""

from cloudformation_dataclasses.core import (
    Mapping,
    Parameter,
    ParameterType,
    STRING,
    Template,
    cloudformation_dataclass,
    get_att,
    ref,
)
from cloudformation_dataclasses.core.resource_loader import setup_resources
from cloudformation_dataclasses.aws import ec2
from cloudformation_dataclasses.intrinsics import (
    AWS_REGION,
    Base64,
    FindInMap,
    Sub,
)

from .params import *  # noqa: F403, F401

# Auto-discover and import resource files in topological order
setup_resources(__file__, __name__, globals())

__all__ = [
    "AWSInstanceType2ArchMapping",
    "AWSRegionArch2AMIMapping",
    "AWS_REGION",
    "Base64",
    "EC2Instance",
    "FindInMap",
    "InstanceSecurityGroup",
    "InstanceType",
    "KeyName",
    "Mapping",
    "Parameter",
    "ParameterType",
    "SSHLocation",
    "STRING",
    "Sub",
    "SubnetId",
    "Template",
    "cloudformation_dataclass",
    "ec2",
    "get_att",
    "ref",
]
