"""
AWS CloudFormation FMS Resources

⚠️  AUTO-GENERATED FILE - DO NOT EDIT MANUALLY ⚠️

This file is automatically generated from the AWS CloudFormation Resource Specification.
Any manual changes will be overwritten when regenerated.

Version Information:
  CloudFormation Spec: 2025.12.11
  Generator Version: 1.0.0
  Combined: spec-2025.12.11_gen-1.0.0
  Generated: 2025-12-22 14:55:24

To regenerate:
    uv run python -m cloudformation_dataclasses.codegen.generator --service FMS
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, ClassVar, Optional, Union

from cloudformation_dataclasses.core.base import CloudFormationResource, PropertyType, Tag
from cloudformation_dataclasses.intrinsics.functions import GetAtt, Ref, Sub


# =============================================================================
# Service Constants (auto-generated from botocore)
# =============================================================================

class AccountRoleStatus:
    """AccountRoleStatus enum values."""

    READY = "READY"
    CREATING = "CREATING"
    PENDING_DELETION = "PENDING_DELETION"
    DELETING = "DELETING"
    DELETED = "DELETED"


class CustomerPolicyScopeIdType:
    """CustomerPolicyScopeIdType enum values."""

    ACCOUNT = "ACCOUNT"
    ORG_UNIT = "ORG_UNIT"


class CustomerPolicyStatus:
    """CustomerPolicyStatus enum values."""

    ACTIVE = "ACTIVE"
    OUT_OF_ADMIN_SCOPE = "OUT_OF_ADMIN_SCOPE"


class DependentServiceName:
    """DependentServiceName enum values."""

    AWSCONFIG = "AWSCONFIG"
    AWSWAF = "AWSWAF"
    AWSSHIELD_ADVANCED = "AWSSHIELD_ADVANCED"
    AWSVPC = "AWSVPC"


class DestinationType:
    """DestinationType enum values."""

    IPV4 = "IPV4"
    IPV6 = "IPV6"
    PREFIX_LIST = "PREFIX_LIST"


class EntryType:
    """EntryType enum values."""

    FMS_MANAGED_FIRST_ENTRY = "FMS_MANAGED_FIRST_ENTRY"
    FMS_MANAGED_LAST_ENTRY = "FMS_MANAGED_LAST_ENTRY"
    CUSTOM_ENTRY = "CUSTOM_ENTRY"


class EntryViolationReason:
    """EntryViolationReason enum values."""

    MISSING_EXPECTED_ENTRY = "MISSING_EXPECTED_ENTRY"
    INCORRECT_ENTRY_ORDER = "INCORRECT_ENTRY_ORDER"
    ENTRY_CONFLICT = "ENTRY_CONFLICT"


class FailedItemReason:
    """FailedItemReason enum values."""

    NOT_VALID_ARN = "NOT_VALID_ARN"
    NOT_VALID_PARTITION = "NOT_VALID_PARTITION"
    NOT_VALID_REGION = "NOT_VALID_REGION"
    NOT_VALID_SERVICE = "NOT_VALID_SERVICE"
    NOT_VALID_RESOURCE_TYPE = "NOT_VALID_RESOURCE_TYPE"
    NOT_VALID_ACCOUNT_ID = "NOT_VALID_ACCOUNT_ID"


class FirewallDeploymentModel:
    """FirewallDeploymentModel enum values."""

    CENTRALIZED = "CENTRALIZED"
    DISTRIBUTED = "DISTRIBUTED"


class MarketplaceSubscriptionOnboardingStatus:
    """MarketplaceSubscriptionOnboardingStatus enum values."""

    NO_SUBSCRIPTION = "NO_SUBSCRIPTION"
    NOT_COMPLETE = "NOT_COMPLETE"
    COMPLETE = "COMPLETE"


class NetworkAclRuleAction:
    """NetworkAclRuleAction enum values."""

    ALLOW = "allow"
    DENY = "deny"


class NetworkFirewallOverrideAction:
    """NetworkFirewallOverrideAction enum values."""

    DROP_TO_ALERT = "DROP_TO_ALERT"


class OrganizationStatus:
    """OrganizationStatus enum values."""

    ONBOARDING = "ONBOARDING"
    ONBOARDING_COMPLETE = "ONBOARDING_COMPLETE"
    OFFBOARDING = "OFFBOARDING"
    OFFBOARDING_COMPLETE = "OFFBOARDING_COMPLETE"


class PolicyComplianceStatusType:
    """PolicyComplianceStatusType enum values."""

    COMPLIANT = "COMPLIANT"
    NON_COMPLIANT = "NON_COMPLIANT"


class RemediationActionType:
    """RemediationActionType enum values."""

    REMOVE = "REMOVE"
    MODIFY = "MODIFY"


class ResourceSetStatus:
    """ResourceSetStatus enum values."""

    ACTIVE = "ACTIVE"
    OUT_OF_ADMIN_SCOPE = "OUT_OF_ADMIN_SCOPE"


class ResourceTagLogicalOperator:
    """ResourceTagLogicalOperator enum values."""

    AND = "AND"
    OR = "OR"


class RuleOrder:
    """RuleOrder enum values."""

    STRICT_ORDER = "STRICT_ORDER"
    DEFAULT_ACTION_ORDER = "DEFAULT_ACTION_ORDER"


class SecurityServiceType:
    """SecurityServiceType enum values."""

    WAF = "WAF"
    WAFV2 = "WAFV2"
    SHIELD_ADVANCED = "SHIELD_ADVANCED"
    SECURITY_GROUPS_COMMON = "SECURITY_GROUPS_COMMON"
    SECURITY_GROUPS_CONTENT_AUDIT = "SECURITY_GROUPS_CONTENT_AUDIT"
    SECURITY_GROUPS_USAGE_AUDIT = "SECURITY_GROUPS_USAGE_AUDIT"
    NETWORK_FIREWALL = "NETWORK_FIREWALL"
    DNS_FIREWALL = "DNS_FIREWALL"
    THIRD_PARTY_FIREWALL = "THIRD_PARTY_FIREWALL"
    IMPORT_NETWORK_FIREWALL = "IMPORT_NETWORK_FIREWALL"
    NETWORK_ACL_COMMON = "NETWORK_ACL_COMMON"


class StreamExceptionPolicy:
    """StreamExceptionPolicy enum values."""

    DROP = "DROP"
    CONTINUE = "CONTINUE"
    REJECT = "REJECT"
    FMS_IGNORE = "FMS_IGNORE"


class TargetType:
    """TargetType enum values."""

    GATEWAY = "GATEWAY"
    CARRIER_GATEWAY = "CARRIER_GATEWAY"
    INSTANCE = "INSTANCE"
    LOCAL_GATEWAY = "LOCAL_GATEWAY"
    NAT_GATEWAY = "NAT_GATEWAY"
    NETWORK_INTERFACE = "NETWORK_INTERFACE"
    VPC_ENDPOINT = "VPC_ENDPOINT"
    VPC_PEERING_CONNECTION = "VPC_PEERING_CONNECTION"
    EGRESS_ONLY_INTERNET_GATEWAY = "EGRESS_ONLY_INTERNET_GATEWAY"
    TRANSIT_GATEWAY = "TRANSIT_GATEWAY"


class ThirdPartyFirewall:
    """ThirdPartyFirewall enum values."""

    PALO_ALTO_NETWORKS_CLOUD_NGFW = "PALO_ALTO_NETWORKS_CLOUD_NGFW"
    FORTIGATE_CLOUD_NATIVE_FIREWALL = "FORTIGATE_CLOUD_NATIVE_FIREWALL"


class ThirdPartyFirewallAssociationStatus:
    """ThirdPartyFirewallAssociationStatus enum values."""

    ONBOARDING = "ONBOARDING"
    ONBOARD_COMPLETE = "ONBOARD_COMPLETE"
    OFFBOARDING = "OFFBOARDING"
    OFFBOARD_COMPLETE = "OFFBOARD_COMPLETE"
    NOT_EXIST = "NOT_EXIST"


class ViolationReason:
    """ViolationReason enum values."""

    WEB_ACL_MISSING_RULE_GROUP = "WEB_ACL_MISSING_RULE_GROUP"
    RESOURCE_MISSING_WEB_ACL = "RESOURCE_MISSING_WEB_ACL"
    RESOURCE_INCORRECT_WEB_ACL = "RESOURCE_INCORRECT_WEB_ACL"
    RESOURCE_MISSING_SHIELD_PROTECTION = "RESOURCE_MISSING_SHIELD_PROTECTION"
    RESOURCE_MISSING_WEB_ACL_OR_SHIELD_PROTECTION = "RESOURCE_MISSING_WEB_ACL_OR_SHIELD_PROTECTION"
    RESOURCE_MISSING_SECURITY_GROUP = "RESOURCE_MISSING_SECURITY_GROUP"
    RESOURCE_VIOLATES_AUDIT_SECURITY_GROUP = "RESOURCE_VIOLATES_AUDIT_SECURITY_GROUP"
    SECURITY_GROUP_UNUSED = "SECURITY_GROUP_UNUSED"
    SECURITY_GROUP_REDUNDANT = "SECURITY_GROUP_REDUNDANT"
    FMS_CREATED_SECURITY_GROUP_EDITED = "FMS_CREATED_SECURITY_GROUP_EDITED"
    MISSING_FIREWALL = "MISSING_FIREWALL"
    MISSING_FIREWALL_SUBNET_IN_AZ = "MISSING_FIREWALL_SUBNET_IN_AZ"
    MISSING_EXPECTED_ROUTE_TABLE = "MISSING_EXPECTED_ROUTE_TABLE"
    NETWORK_FIREWALL_POLICY_MODIFIED = "NETWORK_FIREWALL_POLICY_MODIFIED"
    FIREWALL_SUBNET_IS_OUT_OF_SCOPE = "FIREWALL_SUBNET_IS_OUT_OF_SCOPE"
    INTERNET_GATEWAY_MISSING_EXPECTED_ROUTE = "INTERNET_GATEWAY_MISSING_EXPECTED_ROUTE"
    FIREWALL_SUBNET_MISSING_EXPECTED_ROUTE = "FIREWALL_SUBNET_MISSING_EXPECTED_ROUTE"
    UNEXPECTED_FIREWALL_ROUTES = "UNEXPECTED_FIREWALL_ROUTES"
    UNEXPECTED_TARGET_GATEWAY_ROUTES = "UNEXPECTED_TARGET_GATEWAY_ROUTES"
    TRAFFIC_INSPECTION_CROSSES_AZ_BOUNDARY = "TRAFFIC_INSPECTION_CROSSES_AZ_BOUNDARY"
    INVALID_ROUTE_CONFIGURATION = "INVALID_ROUTE_CONFIGURATION"
    MISSING_TARGET_GATEWAY = "MISSING_TARGET_GATEWAY"
    INTERNET_TRAFFIC_NOT_INSPECTED = "INTERNET_TRAFFIC_NOT_INSPECTED"
    BLACK_HOLE_ROUTE_DETECTED = "BLACK_HOLE_ROUTE_DETECTED"
    BLACK_HOLE_ROUTE_DETECTED_IN_FIREWALL_SUBNET = "BLACK_HOLE_ROUTE_DETECTED_IN_FIREWALL_SUBNET"
    RESOURCE_MISSING_DNS_FIREWALL = "RESOURCE_MISSING_DNS_FIREWALL"
    ROUTE_HAS_OUT_OF_SCOPE_ENDPOINT = "ROUTE_HAS_OUT_OF_SCOPE_ENDPOINT"
    FIREWALL_SUBNET_MISSING_VPCE_ENDPOINT = "FIREWALL_SUBNET_MISSING_VPCE_ENDPOINT"
    INVALID_NETWORK_ACL_ENTRY = "INVALID_NETWORK_ACL_ENTRY"
    WEB_ACL_CONFIGURATION_OR_SCOPE_OF_USE = "WEB_ACL_CONFIGURATION_OR_SCOPE_OF_USE"


# Convenient aliases for enum values
READY = AccountRoleStatus.READY
CREATING = AccountRoleStatus.CREATING
PENDING_DELETION = AccountRoleStatus.PENDING_DELETION
DELETING = AccountRoleStatus.DELETING
DELETED = AccountRoleStatus.DELETED
ACCOUNT = CustomerPolicyScopeIdType.ACCOUNT
ORG_UNIT = CustomerPolicyScopeIdType.ORG_UNIT
ACTIVE = CustomerPolicyStatus.ACTIVE
OUT_OF_ADMIN_SCOPE = CustomerPolicyStatus.OUT_OF_ADMIN_SCOPE
AWSCONFIG = DependentServiceName.AWSCONFIG
AWSWAF = DependentServiceName.AWSWAF
AWSSHIELD_ADVANCED = DependentServiceName.AWSSHIELD_ADVANCED
AWSVPC = DependentServiceName.AWSVPC
IPV4 = DestinationType.IPV4
IPV6 = DestinationType.IPV6
PREFIX_LIST = DestinationType.PREFIX_LIST
FMS_MANAGED_FIRST_ENTRY = EntryType.FMS_MANAGED_FIRST_ENTRY
FMS_MANAGED_LAST_ENTRY = EntryType.FMS_MANAGED_LAST_ENTRY
CUSTOM_ENTRY = EntryType.CUSTOM_ENTRY
MISSING_EXPECTED_ENTRY = EntryViolationReason.MISSING_EXPECTED_ENTRY
INCORRECT_ENTRY_ORDER = EntryViolationReason.INCORRECT_ENTRY_ORDER
ENTRY_CONFLICT = EntryViolationReason.ENTRY_CONFLICT
NOT_VALID_ARN = FailedItemReason.NOT_VALID_ARN
NOT_VALID_PARTITION = FailedItemReason.NOT_VALID_PARTITION
NOT_VALID_REGION = FailedItemReason.NOT_VALID_REGION
NOT_VALID_SERVICE = FailedItemReason.NOT_VALID_SERVICE
NOT_VALID_RESOURCE_TYPE = FailedItemReason.NOT_VALID_RESOURCE_TYPE
NOT_VALID_ACCOUNT_ID = FailedItemReason.NOT_VALID_ACCOUNT_ID
CENTRALIZED = FirewallDeploymentModel.CENTRALIZED
DISTRIBUTED = FirewallDeploymentModel.DISTRIBUTED
NO_SUBSCRIPTION = MarketplaceSubscriptionOnboardingStatus.NO_SUBSCRIPTION
NOT_COMPLETE = MarketplaceSubscriptionOnboardingStatus.NOT_COMPLETE
COMPLETE = MarketplaceSubscriptionOnboardingStatus.COMPLETE
ALLOW = NetworkAclRuleAction.ALLOW
DENY = NetworkAclRuleAction.DENY
DROP_TO_ALERT = NetworkFirewallOverrideAction.DROP_TO_ALERT
ONBOARDING = OrganizationStatus.ONBOARDING
ONBOARDING_COMPLETE = OrganizationStatus.ONBOARDING_COMPLETE
OFFBOARDING = OrganizationStatus.OFFBOARDING
OFFBOARDING_COMPLETE = OrganizationStatus.OFFBOARDING_COMPLETE
COMPLIANT = PolicyComplianceStatusType.COMPLIANT
NON_COMPLIANT = PolicyComplianceStatusType.NON_COMPLIANT
REMOVE = RemediationActionType.REMOVE
MODIFY = RemediationActionType.MODIFY
ACTIVE = ResourceSetStatus.ACTIVE
OUT_OF_ADMIN_SCOPE = ResourceSetStatus.OUT_OF_ADMIN_SCOPE
AND = ResourceTagLogicalOperator.AND
OR = ResourceTagLogicalOperator.OR
STRICT_ORDER = RuleOrder.STRICT_ORDER
DEFAULT_ACTION_ORDER = RuleOrder.DEFAULT_ACTION_ORDER
WAF = SecurityServiceType.WAF
WAFV2 = SecurityServiceType.WAFV2
SHIELD_ADVANCED = SecurityServiceType.SHIELD_ADVANCED
SECURITY_GROUPS_COMMON = SecurityServiceType.SECURITY_GROUPS_COMMON
SECURITY_GROUPS_CONTENT_AUDIT = SecurityServiceType.SECURITY_GROUPS_CONTENT_AUDIT
SECURITY_GROUPS_USAGE_AUDIT = SecurityServiceType.SECURITY_GROUPS_USAGE_AUDIT
NETWORK_FIREWALL = SecurityServiceType.NETWORK_FIREWALL
DNS_FIREWALL = SecurityServiceType.DNS_FIREWALL
THIRD_PARTY_FIREWALL = SecurityServiceType.THIRD_PARTY_FIREWALL
IMPORT_NETWORK_FIREWALL = SecurityServiceType.IMPORT_NETWORK_FIREWALL
NETWORK_ACL_COMMON = SecurityServiceType.NETWORK_ACL_COMMON
DROP = StreamExceptionPolicy.DROP
CONTINUE = StreamExceptionPolicy.CONTINUE
REJECT = StreamExceptionPolicy.REJECT
FMS_IGNORE = StreamExceptionPolicy.FMS_IGNORE
GATEWAY = TargetType.GATEWAY
CARRIER_GATEWAY = TargetType.CARRIER_GATEWAY
INSTANCE = TargetType.INSTANCE
LOCAL_GATEWAY = TargetType.LOCAL_GATEWAY
NAT_GATEWAY = TargetType.NAT_GATEWAY
NETWORK_INTERFACE = TargetType.NETWORK_INTERFACE
VPC_ENDPOINT = TargetType.VPC_ENDPOINT
VPC_PEERING_CONNECTION = TargetType.VPC_PEERING_CONNECTION
EGRESS_ONLY_INTERNET_GATEWAY = TargetType.EGRESS_ONLY_INTERNET_GATEWAY
TRANSIT_GATEWAY = TargetType.TRANSIT_GATEWAY
PALO_ALTO_NETWORKS_CLOUD_NGFW = ThirdPartyFirewall.PALO_ALTO_NETWORKS_CLOUD_NGFW
FORTIGATE_CLOUD_NATIVE_FIREWALL = ThirdPartyFirewall.FORTIGATE_CLOUD_NATIVE_FIREWALL
ONBOARDING = ThirdPartyFirewallAssociationStatus.ONBOARDING
ONBOARD_COMPLETE = ThirdPartyFirewallAssociationStatus.ONBOARD_COMPLETE
OFFBOARDING = ThirdPartyFirewallAssociationStatus.OFFBOARDING
OFFBOARD_COMPLETE = ThirdPartyFirewallAssociationStatus.OFFBOARD_COMPLETE
NOT_EXIST = ThirdPartyFirewallAssociationStatus.NOT_EXIST
WEB_ACL_MISSING_RULE_GROUP = ViolationReason.WEB_ACL_MISSING_RULE_GROUP
RESOURCE_MISSING_WEB_ACL = ViolationReason.RESOURCE_MISSING_WEB_ACL
RESOURCE_INCORRECT_WEB_ACL = ViolationReason.RESOURCE_INCORRECT_WEB_ACL
RESOURCE_MISSING_SHIELD_PROTECTION = ViolationReason.RESOURCE_MISSING_SHIELD_PROTECTION
RESOURCE_MISSING_WEB_ACL_OR_SHIELD_PROTECTION = ViolationReason.RESOURCE_MISSING_WEB_ACL_OR_SHIELD_PROTECTION
RESOURCE_MISSING_SECURITY_GROUP = ViolationReason.RESOURCE_MISSING_SECURITY_GROUP
RESOURCE_VIOLATES_AUDIT_SECURITY_GROUP = ViolationReason.RESOURCE_VIOLATES_AUDIT_SECURITY_GROUP
SECURITY_GROUP_UNUSED = ViolationReason.SECURITY_GROUP_UNUSED
SECURITY_GROUP_REDUNDANT = ViolationReason.SECURITY_GROUP_REDUNDANT
FMS_CREATED_SECURITY_GROUP_EDITED = ViolationReason.FMS_CREATED_SECURITY_GROUP_EDITED
MISSING_FIREWALL = ViolationReason.MISSING_FIREWALL
MISSING_FIREWALL_SUBNET_IN_AZ = ViolationReason.MISSING_FIREWALL_SUBNET_IN_AZ
MISSING_EXPECTED_ROUTE_TABLE = ViolationReason.MISSING_EXPECTED_ROUTE_TABLE
NETWORK_FIREWALL_POLICY_MODIFIED = ViolationReason.NETWORK_FIREWALL_POLICY_MODIFIED
FIREWALL_SUBNET_IS_OUT_OF_SCOPE = ViolationReason.FIREWALL_SUBNET_IS_OUT_OF_SCOPE
INTERNET_GATEWAY_MISSING_EXPECTED_ROUTE = ViolationReason.INTERNET_GATEWAY_MISSING_EXPECTED_ROUTE
FIREWALL_SUBNET_MISSING_EXPECTED_ROUTE = ViolationReason.FIREWALL_SUBNET_MISSING_EXPECTED_ROUTE
UNEXPECTED_FIREWALL_ROUTES = ViolationReason.UNEXPECTED_FIREWALL_ROUTES
UNEXPECTED_TARGET_GATEWAY_ROUTES = ViolationReason.UNEXPECTED_TARGET_GATEWAY_ROUTES
TRAFFIC_INSPECTION_CROSSES_AZ_BOUNDARY = ViolationReason.TRAFFIC_INSPECTION_CROSSES_AZ_BOUNDARY
INVALID_ROUTE_CONFIGURATION = ViolationReason.INVALID_ROUTE_CONFIGURATION
MISSING_TARGET_GATEWAY = ViolationReason.MISSING_TARGET_GATEWAY
INTERNET_TRAFFIC_NOT_INSPECTED = ViolationReason.INTERNET_TRAFFIC_NOT_INSPECTED
BLACK_HOLE_ROUTE_DETECTED = ViolationReason.BLACK_HOLE_ROUTE_DETECTED
BLACK_HOLE_ROUTE_DETECTED_IN_FIREWALL_SUBNET = ViolationReason.BLACK_HOLE_ROUTE_DETECTED_IN_FIREWALL_SUBNET
RESOURCE_MISSING_DNS_FIREWALL = ViolationReason.RESOURCE_MISSING_DNS_FIREWALL
ROUTE_HAS_OUT_OF_SCOPE_ENDPOINT = ViolationReason.ROUTE_HAS_OUT_OF_SCOPE_ENDPOINT
FIREWALL_SUBNET_MISSING_VPCE_ENDPOINT = ViolationReason.FIREWALL_SUBNET_MISSING_VPCE_ENDPOINT
INVALID_NETWORK_ACL_ENTRY = ViolationReason.INVALID_NETWORK_ACL_ENTRY
WEB_ACL_CONFIGURATION_OR_SCOPE_OF_USE = ViolationReason.WEB_ACL_CONFIGURATION_OR_SCOPE_OF_USE


# PropertyType submodules (e.g., ec2.instance.NetworkInterface)
from . import policy


@dataclass
class NotificationChannel(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-fms-n"""

    resource_type: ClassVar[str] = "AWS::FMS::NotificationChannel"
    SNS_TOPIC_ARN = "SnsTopicArn"
    SNS_ROLE_NAME = "SnsRoleName"

    _property_mappings: ClassVar[dict[str, str]] = {
        "sns_topic_arn": "SnsTopicArn",
        "sns_role_name": "SnsRoleName",
    }

    sns_topic_arn: Optional[Union[str, Ref, GetAtt, Sub]] = None
    sns_role_name: Optional[Union[str, Ref, GetAtt, Sub]] = None


@dataclass
class Policy(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-fms-p"""

    resource_type: ClassVar[str] = "AWS::FMS::Policy"
    RESOURCE_TAG_LOGICAL_OPERATOR = "ResourceTagLogicalOperator"
    RESOURCES_CLEAN_UP = "ResourcesCleanUp"
    RESOURCE_TAGS = "ResourceTags"
    EXCLUDE_RESOURCE_TAGS = "ExcludeResourceTags"
    RESOURCE_TYPE = "ResourceType"
    RESOURCE_SET_IDS = "ResourceSetIds"
    SECURITY_SERVICE_POLICY_DATA = "SecurityServicePolicyData"
    REMEDIATION_ENABLED = "RemediationEnabled"
    DELETE_ALL_POLICY_RESOURCES = "DeleteAllPolicyResources"
    EXCLUDE_MAP = "ExcludeMap"
    INCLUDE_MAP = "IncludeMap"
    POLICY_DESCRIPTION = "PolicyDescription"
    POLICY_NAME = "PolicyName"
    RESOURCE_TYPE_LIST = "ResourceTypeList"
    TAGS = "Tags"

    _property_mappings: ClassVar[dict[str, str]] = {
        "resource_tag_logical_operator": "ResourceTagLogicalOperator",
        "resources_clean_up": "ResourcesCleanUp",
        "resource_tags": "ResourceTags",
        "exclude_resource_tags": "ExcludeResourceTags",
        "resource_type": "ResourceType",
        "resource_set_ids": "ResourceSetIds",
        "security_service_policy_data": "SecurityServicePolicyData",
        "remediation_enabled": "RemediationEnabled",
        "delete_all_policy_resources": "DeleteAllPolicyResources",
        "exclude_map": "ExcludeMap",
        "include_map": "IncludeMap",
        "policy_description": "PolicyDescription",
        "policy_name": "PolicyName",
        "resource_type_list": "ResourceTypeList",
        "tags": "Tags",
    }

    resource_tag_logical_operator: Optional[Union[str, ResourceTagLogicalOperator, Ref, GetAtt, Sub]] = None
    resources_clean_up: Optional[Union[bool, Ref, GetAtt, Sub]] = None
    resource_tags: Optional[list[policy.ResourceTag]] = None
    exclude_resource_tags: Optional[Union[bool, Ref, GetAtt, Sub]] = None
    resource_type: Optional[Union[str, Ref, GetAtt, Sub]] = None
    resource_set_ids: Optional[Union[list[str], Ref]] = None
    security_service_policy_data: Optional[policy.SecurityServicePolicyData] = None
    remediation_enabled: Optional[Union[bool, Ref, GetAtt, Sub]] = None
    delete_all_policy_resources: Optional[Union[bool, Ref, GetAtt, Sub]] = None
    exclude_map: Optional[policy.IEMap] = None
    include_map: Optional[policy.IEMap] = None
    policy_description: Optional[Union[str, Ref, GetAtt, Sub]] = None
    policy_name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    resource_type_list: Optional[Union[list[str], Ref]] = None
    tags: Optional[list[policy.PolicyTag]] = None

    @property
    def attr_id(self) -> GetAtt:
        """Get the Id attribute."""
        return self.get_att("Id")

    @property
    def attr_arn(self) -> GetAtt:
        """Get the Arn attribute."""
        return self.get_att("Arn")



@dataclass
class ResourceSet(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-fms-r"""

    resource_type: ClassVar[str] = "AWS::FMS::ResourceSet"
    DESCRIPTION = "Description"
    RESOURCE_TYPE_LIST = "ResourceTypeList"
    RESOURCES = "Resources"
    TAGS = "Tags"
    NAME = "Name"

    _property_mappings: ClassVar[dict[str, str]] = {
        "description": "Description",
        "resource_type_list": "ResourceTypeList",
        "resources": "Resources",
        "tags": "Tags",
        "name": "Name",
    }

    description: Optional[Union[str, Ref, GetAtt, Sub]] = None
    resource_type_list: Optional[Union[list[str], Ref]] = None
    resources: Optional[Union[list[str], Ref]] = None
    tags: Optional[list[Tag]] = None
    name: Optional[Union[str, Ref, GetAtt, Sub]] = None

    @property
    def attr_id(self) -> GetAtt:
        """Get the Id attribute."""
        return self.get_att("Id")


