"""
AWS CloudFormation QBusiness Resources

⚠️  AUTO-GENERATED FILE - DO NOT EDIT MANUALLY ⚠️

This file is automatically generated from the AWS CloudFormation Resource Specification.
Any manual changes will be overwritten when regenerated.

Version Information:
  CloudFormation Spec: 2025.12.11
  Generator Version: 1.0.0
  Combined: spec-2025.12.11_gen-1.0.0
  Generated: 2025-12-22 18:30:21

To regenerate:
    uv run python -m cloudformation_dataclasses.codegen.generator --service QBusiness
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, ClassVar, Optional, Union

from cloudformation_dataclasses.core.base import CloudFormationResource, PropertyType, Tag
from cloudformation_dataclasses.intrinsics.functions import GetAtt, Ref, Sub


# =============================================================================
# Service Constants (auto-generated from botocore)
# =============================================================================

class APISchemaType:
    """APISchemaType enum values."""

    OPEN_API_V3 = "OPEN_API_V3"


class ActionPayloadFieldType:
    """ActionPayloadFieldType enum values."""

    STRING = "STRING"
    NUMBER = "NUMBER"
    ARRAY = "ARRAY"
    BOOLEAN = "BOOLEAN"


class ApplicationStatus:
    """ApplicationStatus enum values."""

    CREATING = "CREATING"
    ACTIVE = "ACTIVE"
    DELETING = "DELETING"
    FAILED = "FAILED"
    UPDATING = "UPDATING"


class AttachmentStatus:
    """AttachmentStatus enum values."""

    FAILED = "FAILED"
    SUCCESS = "SUCCESS"


class AttachmentsControlMode:
    """AttachmentsControlMode enum values."""

    ENABLED = "ENABLED"
    DISABLED = "DISABLED"


class AttributeType:
    """AttributeType enum values."""

    STRING = "STRING"
    STRING_LIST = "STRING_LIST"
    NUMBER = "NUMBER"
    DATE = "DATE"


class AttributeValueOperator:
    """AttributeValueOperator enum values."""

    DELETE = "DELETE"


class AudioExtractionStatus:
    """AudioExtractionStatus enum values."""

    ENABLED = "ENABLED"
    DISABLED = "DISABLED"


class AudioExtractionType:
    """AudioExtractionType enum values."""

    TRANSCRIPT = "TRANSCRIPT"
    SUMMARY = "SUMMARY"


class AutoSubscriptionStatus:
    """AutoSubscriptionStatus enum values."""

    ENABLED = "ENABLED"
    DISABLED = "DISABLED"


class BrowserExtension:
    """BrowserExtension enum values."""

    FIREFOX = "FIREFOX"
    CHROME = "CHROME"


class ChatMode:
    """ChatMode enum values."""

    RETRIEVAL_MODE = "RETRIEVAL_MODE"
    CREATOR_MODE = "CREATOR_MODE"
    PLUGIN_MODE = "PLUGIN_MODE"


class ChatResponseConfigurationStatus:
    """ChatResponseConfigurationStatus enum values."""

    CREATING = "CREATING"
    UPDATING = "UPDATING"
    FAILED = "FAILED"
    ACTIVE = "ACTIVE"


class ContentType:
    """ContentType enum values."""

    PDF = "PDF"
    HTML = "HTML"
    MS_WORD = "MS_WORD"
    PLAIN_TEXT = "PLAIN_TEXT"
    PPT = "PPT"
    RTF = "RTF"
    XML = "XML"
    XSLT = "XSLT"
    MS_EXCEL = "MS_EXCEL"
    CSV = "CSV"
    JSON = "JSON"
    MD = "MD"


class CreatorModeControl:
    """CreatorModeControl enum values."""

    ENABLED = "ENABLED"
    DISABLED = "DISABLED"


class DataAccessorAuthenticationType:
    """DataAccessorAuthenticationType enum values."""

    AWS_IAM_IDC_TTI = "AWS_IAM_IDC_TTI"
    AWS_IAM_IDC_AUTH_CODE = "AWS_IAM_IDC_AUTH_CODE"


class DataSourceStatus:
    """DataSourceStatus enum values."""

    PENDING_CREATION = "PENDING_CREATION"
    CREATING = "CREATING"
    ACTIVE = "ACTIVE"
    DELETING = "DELETING"
    FAILED = "FAILED"
    UPDATING = "UPDATING"


class DataSourceSyncJobStatus:
    """DataSourceSyncJobStatus enum values."""

    FAILED = "FAILED"
    SUCCEEDED = "SUCCEEDED"
    SYNCING = "SYNCING"
    INCOMPLETE = "INCOMPLETE"
    STOPPING = "STOPPING"
    ABORTED = "ABORTED"
    SYNCING_INDEXING = "SYNCING_INDEXING"


class DocumentAttributeBoostingLevel:
    """DocumentAttributeBoostingLevel enum values."""

    NONE = "NONE"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    VERY_HIGH = "VERY_HIGH"
    ONE = "ONE"
    TWO = "TWO"


class DocumentContentOperator:
    """DocumentContentOperator enum values."""

    DELETE = "DELETE"


class DocumentEnrichmentConditionOperator:
    """DocumentEnrichmentConditionOperator enum values."""

    GREATER_THAN = "GREATER_THAN"
    GREATER_THAN_OR_EQUALS = "GREATER_THAN_OR_EQUALS"
    LESS_THAN = "LESS_THAN"
    LESS_THAN_OR_EQUALS = "LESS_THAN_OR_EQUALS"
    EQUALS = "EQUALS"
    NOT_EQUALS = "NOT_EQUALS"
    CONTAINS = "CONTAINS"
    NOT_CONTAINS = "NOT_CONTAINS"
    EXISTS = "EXISTS"
    NOT_EXISTS = "NOT_EXISTS"
    BEGINS_WITH = "BEGINS_WITH"


class DocumentStatus:
    """DocumentStatus enum values."""

    RECEIVED = "RECEIVED"
    PROCESSING = "PROCESSING"
    INDEXED = "INDEXED"
    UPDATED = "UPDATED"
    FAILED = "FAILED"
    DELETING = "DELETING"
    DELETED = "DELETED"
    DOCUMENT_FAILED_TO_INDEX = "DOCUMENT_FAILED_TO_INDEX"


class ErrorCode:
    """ErrorCode enum values."""

    INTERNALERROR = "InternalError"
    INVALIDREQUEST = "InvalidRequest"
    RESOURCEINACTIVE = "ResourceInactive"
    RESOURCENOTFOUND = "ResourceNotFound"


class GroupStatus:
    """GroupStatus enum values."""

    FAILED = "FAILED"
    SUCCEEDED = "SUCCEEDED"
    PROCESSING = "PROCESSING"
    DELETING = "DELETING"
    DELETED = "DELETED"


class HallucinationReductionControl:
    """HallucinationReductionControl enum values."""

    ENABLED = "ENABLED"
    DISABLED = "DISABLED"


class IdentityType:
    """IdentityType enum values."""

    AWS_IAM_IDP_SAML = "AWS_IAM_IDP_SAML"
    AWS_IAM_IDP_OIDC = "AWS_IAM_IDP_OIDC"
    AWS_IAM_IDC = "AWS_IAM_IDC"
    AWS_QUICKSIGHT_IDP = "AWS_QUICKSIGHT_IDP"
    ANONYMOUS = "ANONYMOUS"


class ImageExtractionStatus:
    """ImageExtractionStatus enum values."""

    ENABLED = "ENABLED"
    DISABLED = "DISABLED"


class IndexStatus:
    """IndexStatus enum values."""

    CREATING = "CREATING"
    ACTIVE = "ACTIVE"
    DELETING = "DELETING"
    FAILED = "FAILED"
    UPDATING = "UPDATING"


class IndexType:
    """IndexType enum values."""

    ENTERPRISE = "ENTERPRISE"
    STARTER = "STARTER"


class MemberRelation:
    """MemberRelation enum values."""

    AND = "AND"
    OR = "OR"


class MembershipType:
    """MembershipType enum values."""

    INDEX = "INDEX"
    DATASOURCE = "DATASOURCE"


class MessageType:
    """MessageType enum values."""

    USER = "USER"
    SYSTEM = "SYSTEM"


class MessageUsefulness:
    """MessageUsefulness enum values."""

    USEFUL = "USEFUL"
    NOT_USEFUL = "NOT_USEFUL"


class MessageUsefulnessReason:
    """MessageUsefulnessReason enum values."""

    NOT_FACTUALLY_CORRECT = "NOT_FACTUALLY_CORRECT"
    HARMFUL_OR_UNSAFE = "HARMFUL_OR_UNSAFE"
    INCORRECT_OR_MISSING_SOURCES = "INCORRECT_OR_MISSING_SOURCES"
    NOT_HELPFUL = "NOT_HELPFUL"
    FACTUALLY_CORRECT = "FACTUALLY_CORRECT"
    COMPLETE = "COMPLETE"
    RELEVANT_SOURCES = "RELEVANT_SOURCES"
    HELPFUL = "HELPFUL"
    NOT_BASED_ON_DOCUMENTS = "NOT_BASED_ON_DOCUMENTS"
    NOT_COMPLETE = "NOT_COMPLETE"
    NOT_CONCISE = "NOT_CONCISE"
    OTHER = "OTHER"


class NumberAttributeBoostingType:
    """NumberAttributeBoostingType enum values."""

    PRIORITIZE_LARGER_VALUES = "PRIORITIZE_LARGER_VALUES"
    PRIORITIZE_SMALLER_VALUES = "PRIORITIZE_SMALLER_VALUES"


class OrchestrationControl:
    """OrchestrationControl enum values."""

    ENABLED = "ENABLED"
    DISABLED = "DISABLED"


class OutputFormat:
    """OutputFormat enum values."""

    RAW = "RAW"
    EXTRACTED = "EXTRACTED"


class PermissionConditionOperator:
    """PermissionConditionOperator enum values."""

    STRINGEQUALS = "StringEquals"


class PersonalizationControlMode:
    """PersonalizationControlMode enum values."""

    ENABLED = "ENABLED"
    DISABLED = "DISABLED"


class PluginBuildStatus:
    """PluginBuildStatus enum values."""

    READY = "READY"
    CREATE_IN_PROGRESS = "CREATE_IN_PROGRESS"
    CREATE_FAILED = "CREATE_FAILED"
    UPDATE_IN_PROGRESS = "UPDATE_IN_PROGRESS"
    UPDATE_FAILED = "UPDATE_FAILED"
    DELETE_IN_PROGRESS = "DELETE_IN_PROGRESS"
    DELETE_FAILED = "DELETE_FAILED"


class PluginState:
    """PluginState enum values."""

    ENABLED = "ENABLED"
    DISABLED = "DISABLED"


class PluginType:
    """PluginType enum values."""

    SERVICE_NOW = "SERVICE_NOW"
    SALESFORCE = "SALESFORCE"
    JIRA = "JIRA"
    ZENDESK = "ZENDESK"
    CUSTOM = "CUSTOM"
    QUICKSIGHT = "QUICKSIGHT"
    SERVICENOW_NOW_PLATFORM = "SERVICENOW_NOW_PLATFORM"
    JIRA_CLOUD = "JIRA_CLOUD"
    SALESFORCE_CRM = "SALESFORCE_CRM"
    ZENDESK_SUITE = "ZENDESK_SUITE"
    ATLASSIAN_CONFLUENCE = "ATLASSIAN_CONFLUENCE"
    GOOGLE_CALENDAR = "GOOGLE_CALENDAR"
    MICROSOFT_TEAMS = "MICROSOFT_TEAMS"
    MICROSOFT_EXCHANGE = "MICROSOFT_EXCHANGE"
    PAGERDUTY_ADVANCE = "PAGERDUTY_ADVANCE"
    SMARTSHEET = "SMARTSHEET"
    ASANA = "ASANA"


class PluginTypeCategory:
    """PluginTypeCategory enum values."""

    CUSTOMER_RELATIONSHIP_MANAGEMENT_CRM = "Customer relationship management (CRM)"
    PROJECT_MANAGEMENT = "Project management"
    COMMUNICATION = "Communication"
    PRODUCTIVITY = "Productivity"
    TICKETING_AND_INCIDENT_MANAGEMENT = "Ticketing and incident management"


class QAppsControlMode:
    """QAppsControlMode enum values."""

    ENABLED = "ENABLED"
    DISABLED = "DISABLED"


class ReadAccessType:
    """ReadAccessType enum values."""

    ALLOW = "ALLOW"
    DENY = "DENY"


class ResponseConfigurationType:
    """ResponseConfigurationType enum values."""

    ALL = "ALL"


class ResponseScope:
    """ResponseScope enum values."""

    ENTERPRISE_CONTENT_ONLY = "ENTERPRISE_CONTENT_ONLY"
    EXTENDED_KNOWLEDGE_ENABLED = "EXTENDED_KNOWLEDGE_ENABLED"


class RetrieverStatus:
    """RetrieverStatus enum values."""

    CREATING = "CREATING"
    ACTIVE = "ACTIVE"
    FAILED = "FAILED"


class RetrieverType:
    """RetrieverType enum values."""

    NATIVE_INDEX = "NATIVE_INDEX"
    KENDRA_INDEX = "KENDRA_INDEX"


class RuleType:
    """RuleType enum values."""

    CONTENT_BLOCKER_RULE = "CONTENT_BLOCKER_RULE"
    CONTENT_RETRIEVAL_RULE = "CONTENT_RETRIEVAL_RULE"


class ScoreConfidence:
    """ScoreConfidence enum values."""

    VERY_HIGH = "VERY_HIGH"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    NOT_AVAILABLE = "NOT_AVAILABLE"


class Status:
    """Status enum values."""

    ENABLED = "ENABLED"
    DISABLED = "DISABLED"


class StringAttributeValueBoostingLevel:
    """StringAttributeValueBoostingLevel enum values."""

    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    VERY_HIGH = "VERY_HIGH"
    ONE = "ONE"
    TWO = "TWO"
    THREE = "THREE"
    FOUR = "FOUR"
    FIVE = "FIVE"


class SubscriptionType:
    """SubscriptionType enum values."""

    Q_LITE = "Q_LITE"
    Q_BUSINESS = "Q_BUSINESS"


class SystemMessageType:
    """SystemMessageType enum values."""

    RESPONSE = "RESPONSE"
    GROUNDED_RESPONSE = "GROUNDED_RESPONSE"


class ValidationExceptionReason:
    """ValidationExceptionReason enum values."""

    CANNOT_PARSE = "CANNOT_PARSE"
    FIELD_VALIDATION_FAILED = "FIELD_VALIDATION_FAILED"
    UNKNOWN_OPERATION = "UNKNOWN_OPERATION"


class VideoExtractionStatus:
    """VideoExtractionStatus enum values."""

    ENABLED = "ENABLED"
    DISABLED = "DISABLED"


class VideoExtractionType:
    """VideoExtractionType enum values."""

    TRANSCRIPT = "TRANSCRIPT"
    SUMMARY = "SUMMARY"


class WebExperienceSamplePromptsControlMode:
    """WebExperienceSamplePromptsControlMode enum values."""

    ENABLED = "ENABLED"
    DISABLED = "DISABLED"


class WebExperienceStatus:
    """WebExperienceStatus enum values."""

    CREATING = "CREATING"
    ACTIVE = "ACTIVE"
    DELETING = "DELETING"
    FAILED = "FAILED"
    PENDING_AUTH_CONFIG = "PENDING_AUTH_CONFIG"


# Convenient aliases for enum values
OPEN_API_V3 = APISchemaType.OPEN_API_V3
STRING = ActionPayloadFieldType.STRING
NUMBER = ActionPayloadFieldType.NUMBER
ARRAY = ActionPayloadFieldType.ARRAY
BOOLEAN = ActionPayloadFieldType.BOOLEAN
CREATING = ApplicationStatus.CREATING
ACTIVE = ApplicationStatus.ACTIVE
DELETING = ApplicationStatus.DELETING
FAILED = ApplicationStatus.FAILED
UPDATING = ApplicationStatus.UPDATING
FAILED = AttachmentStatus.FAILED
SUCCESS = AttachmentStatus.SUCCESS
ENABLED = AttachmentsControlMode.ENABLED
DISABLED = AttachmentsControlMode.DISABLED
STRING = AttributeType.STRING
STRING_LIST = AttributeType.STRING_LIST
NUMBER = AttributeType.NUMBER
DATE = AttributeType.DATE
DELETE = AttributeValueOperator.DELETE
ENABLED = AudioExtractionStatus.ENABLED
DISABLED = AudioExtractionStatus.DISABLED
TRANSCRIPT = AudioExtractionType.TRANSCRIPT
SUMMARY = AudioExtractionType.SUMMARY
ENABLED = AutoSubscriptionStatus.ENABLED
DISABLED = AutoSubscriptionStatus.DISABLED
FIREFOX = BrowserExtension.FIREFOX
CHROME = BrowserExtension.CHROME
RETRIEVAL_MODE = ChatMode.RETRIEVAL_MODE
CREATOR_MODE = ChatMode.CREATOR_MODE
PLUGIN_MODE = ChatMode.PLUGIN_MODE
CREATING = ChatResponseConfigurationStatus.CREATING
UPDATING = ChatResponseConfigurationStatus.UPDATING
FAILED = ChatResponseConfigurationStatus.FAILED
ACTIVE = ChatResponseConfigurationStatus.ACTIVE
PDF = ContentType.PDF
HTML = ContentType.HTML
MS_WORD = ContentType.MS_WORD
PLAIN_TEXT = ContentType.PLAIN_TEXT
PPT = ContentType.PPT
RTF = ContentType.RTF
XML = ContentType.XML
XSLT = ContentType.XSLT
MS_EXCEL = ContentType.MS_EXCEL
CSV = ContentType.CSV
JSON = ContentType.JSON
MD = ContentType.MD
ENABLED = CreatorModeControl.ENABLED
DISABLED = CreatorModeControl.DISABLED
AWS_IAM_IDC_TTI = DataAccessorAuthenticationType.AWS_IAM_IDC_TTI
AWS_IAM_IDC_AUTH_CODE = DataAccessorAuthenticationType.AWS_IAM_IDC_AUTH_CODE
PENDING_CREATION = DataSourceStatus.PENDING_CREATION
CREATING = DataSourceStatus.CREATING
ACTIVE = DataSourceStatus.ACTIVE
DELETING = DataSourceStatus.DELETING
FAILED = DataSourceStatus.FAILED
UPDATING = DataSourceStatus.UPDATING
FAILED = DataSourceSyncJobStatus.FAILED
SUCCEEDED = DataSourceSyncJobStatus.SUCCEEDED
SYNCING = DataSourceSyncJobStatus.SYNCING
INCOMPLETE = DataSourceSyncJobStatus.INCOMPLETE
STOPPING = DataSourceSyncJobStatus.STOPPING
ABORTED = DataSourceSyncJobStatus.ABORTED
SYNCING_INDEXING = DataSourceSyncJobStatus.SYNCING_INDEXING
NONE = DocumentAttributeBoostingLevel.NONE
LOW = DocumentAttributeBoostingLevel.LOW
MEDIUM = DocumentAttributeBoostingLevel.MEDIUM
HIGH = DocumentAttributeBoostingLevel.HIGH
VERY_HIGH = DocumentAttributeBoostingLevel.VERY_HIGH
ONE = DocumentAttributeBoostingLevel.ONE
TWO = DocumentAttributeBoostingLevel.TWO
DELETE = DocumentContentOperator.DELETE
GREATER_THAN = DocumentEnrichmentConditionOperator.GREATER_THAN
GREATER_THAN_OR_EQUALS = DocumentEnrichmentConditionOperator.GREATER_THAN_OR_EQUALS
LESS_THAN = DocumentEnrichmentConditionOperator.LESS_THAN
LESS_THAN_OR_EQUALS = DocumentEnrichmentConditionOperator.LESS_THAN_OR_EQUALS
EQUALS = DocumentEnrichmentConditionOperator.EQUALS
NOT_EQUALS = DocumentEnrichmentConditionOperator.NOT_EQUALS
CONTAINS = DocumentEnrichmentConditionOperator.CONTAINS
NOT_CONTAINS = DocumentEnrichmentConditionOperator.NOT_CONTAINS
EXISTS = DocumentEnrichmentConditionOperator.EXISTS
NOT_EXISTS = DocumentEnrichmentConditionOperator.NOT_EXISTS
BEGINS_WITH = DocumentEnrichmentConditionOperator.BEGINS_WITH
RECEIVED = DocumentStatus.RECEIVED
PROCESSING = DocumentStatus.PROCESSING
INDEXED = DocumentStatus.INDEXED
UPDATED = DocumentStatus.UPDATED
FAILED = DocumentStatus.FAILED
DELETING = DocumentStatus.DELETING
DELETED = DocumentStatus.DELETED
DOCUMENT_FAILED_TO_INDEX = DocumentStatus.DOCUMENT_FAILED_TO_INDEX
INTERNALERROR = ErrorCode.INTERNALERROR
INVALIDREQUEST = ErrorCode.INVALIDREQUEST
RESOURCEINACTIVE = ErrorCode.RESOURCEINACTIVE
RESOURCENOTFOUND = ErrorCode.RESOURCENOTFOUND
FAILED = GroupStatus.FAILED
SUCCEEDED = GroupStatus.SUCCEEDED
PROCESSING = GroupStatus.PROCESSING
DELETING = GroupStatus.DELETING
DELETED = GroupStatus.DELETED
ENABLED = HallucinationReductionControl.ENABLED
DISABLED = HallucinationReductionControl.DISABLED
AWS_IAM_IDP_SAML = IdentityType.AWS_IAM_IDP_SAML
AWS_IAM_IDP_OIDC = IdentityType.AWS_IAM_IDP_OIDC
AWS_IAM_IDC = IdentityType.AWS_IAM_IDC
AWS_QUICKSIGHT_IDP = IdentityType.AWS_QUICKSIGHT_IDP
ANONYMOUS = IdentityType.ANONYMOUS
ENABLED = ImageExtractionStatus.ENABLED
DISABLED = ImageExtractionStatus.DISABLED
CREATING = IndexStatus.CREATING
ACTIVE = IndexStatus.ACTIVE
DELETING = IndexStatus.DELETING
FAILED = IndexStatus.FAILED
UPDATING = IndexStatus.UPDATING
ENTERPRISE = IndexType.ENTERPRISE
STARTER = IndexType.STARTER
AND = MemberRelation.AND
OR = MemberRelation.OR
INDEX = MembershipType.INDEX
DATASOURCE = MembershipType.DATASOURCE
USER = MessageType.USER
SYSTEM = MessageType.SYSTEM
USEFUL = MessageUsefulness.USEFUL
NOT_USEFUL = MessageUsefulness.NOT_USEFUL
NOT_FACTUALLY_CORRECT = MessageUsefulnessReason.NOT_FACTUALLY_CORRECT
HARMFUL_OR_UNSAFE = MessageUsefulnessReason.HARMFUL_OR_UNSAFE
INCORRECT_OR_MISSING_SOURCES = MessageUsefulnessReason.INCORRECT_OR_MISSING_SOURCES
NOT_HELPFUL = MessageUsefulnessReason.NOT_HELPFUL
FACTUALLY_CORRECT = MessageUsefulnessReason.FACTUALLY_CORRECT
COMPLETE = MessageUsefulnessReason.COMPLETE
RELEVANT_SOURCES = MessageUsefulnessReason.RELEVANT_SOURCES
HELPFUL = MessageUsefulnessReason.HELPFUL
NOT_BASED_ON_DOCUMENTS = MessageUsefulnessReason.NOT_BASED_ON_DOCUMENTS
NOT_COMPLETE = MessageUsefulnessReason.NOT_COMPLETE
NOT_CONCISE = MessageUsefulnessReason.NOT_CONCISE
OTHER = MessageUsefulnessReason.OTHER
PRIORITIZE_LARGER_VALUES = NumberAttributeBoostingType.PRIORITIZE_LARGER_VALUES
PRIORITIZE_SMALLER_VALUES = NumberAttributeBoostingType.PRIORITIZE_SMALLER_VALUES
ENABLED = OrchestrationControl.ENABLED
DISABLED = OrchestrationControl.DISABLED
RAW = OutputFormat.RAW
EXTRACTED = OutputFormat.EXTRACTED
STRINGEQUALS = PermissionConditionOperator.STRINGEQUALS
ENABLED = PersonalizationControlMode.ENABLED
DISABLED = PersonalizationControlMode.DISABLED
READY = PluginBuildStatus.READY
CREATE_IN_PROGRESS = PluginBuildStatus.CREATE_IN_PROGRESS
CREATE_FAILED = PluginBuildStatus.CREATE_FAILED
UPDATE_IN_PROGRESS = PluginBuildStatus.UPDATE_IN_PROGRESS
UPDATE_FAILED = PluginBuildStatus.UPDATE_FAILED
DELETE_IN_PROGRESS = PluginBuildStatus.DELETE_IN_PROGRESS
DELETE_FAILED = PluginBuildStatus.DELETE_FAILED
ENABLED = PluginState.ENABLED
DISABLED = PluginState.DISABLED
SERVICE_NOW = PluginType.SERVICE_NOW
SALESFORCE = PluginType.SALESFORCE
JIRA = PluginType.JIRA
ZENDESK = PluginType.ZENDESK
CUSTOM = PluginType.CUSTOM
QUICKSIGHT = PluginType.QUICKSIGHT
SERVICENOW_NOW_PLATFORM = PluginType.SERVICENOW_NOW_PLATFORM
JIRA_CLOUD = PluginType.JIRA_CLOUD
SALESFORCE_CRM = PluginType.SALESFORCE_CRM
ZENDESK_SUITE = PluginType.ZENDESK_SUITE
ATLASSIAN_CONFLUENCE = PluginType.ATLASSIAN_CONFLUENCE
GOOGLE_CALENDAR = PluginType.GOOGLE_CALENDAR
MICROSOFT_TEAMS = PluginType.MICROSOFT_TEAMS
MICROSOFT_EXCHANGE = PluginType.MICROSOFT_EXCHANGE
PAGERDUTY_ADVANCE = PluginType.PAGERDUTY_ADVANCE
SMARTSHEET = PluginType.SMARTSHEET
ASANA = PluginType.ASANA
CUSTOMER_RELATIONSHIP_MANAGEMENT_CRM = PluginTypeCategory.CUSTOMER_RELATIONSHIP_MANAGEMENT_CRM
PROJECT_MANAGEMENT = PluginTypeCategory.PROJECT_MANAGEMENT
COMMUNICATION = PluginTypeCategory.COMMUNICATION
PRODUCTIVITY = PluginTypeCategory.PRODUCTIVITY
TICKETING_AND_INCIDENT_MANAGEMENT = PluginTypeCategory.TICKETING_AND_INCIDENT_MANAGEMENT
ENABLED = QAppsControlMode.ENABLED
DISABLED = QAppsControlMode.DISABLED
ALLOW = ReadAccessType.ALLOW
DENY = ReadAccessType.DENY
ALL = ResponseConfigurationType.ALL
ENTERPRISE_CONTENT_ONLY = ResponseScope.ENTERPRISE_CONTENT_ONLY
EXTENDED_KNOWLEDGE_ENABLED = ResponseScope.EXTENDED_KNOWLEDGE_ENABLED
CREATING = RetrieverStatus.CREATING
ACTIVE = RetrieverStatus.ACTIVE
FAILED = RetrieverStatus.FAILED
NATIVE_INDEX = RetrieverType.NATIVE_INDEX
KENDRA_INDEX = RetrieverType.KENDRA_INDEX
CONTENT_BLOCKER_RULE = RuleType.CONTENT_BLOCKER_RULE
CONTENT_RETRIEVAL_RULE = RuleType.CONTENT_RETRIEVAL_RULE
VERY_HIGH = ScoreConfidence.VERY_HIGH
HIGH = ScoreConfidence.HIGH
MEDIUM = ScoreConfidence.MEDIUM
LOW = ScoreConfidence.LOW
NOT_AVAILABLE = ScoreConfidence.NOT_AVAILABLE
ENABLED = Status.ENABLED
DISABLED = Status.DISABLED
LOW = StringAttributeValueBoostingLevel.LOW
MEDIUM = StringAttributeValueBoostingLevel.MEDIUM
HIGH = StringAttributeValueBoostingLevel.HIGH
VERY_HIGH = StringAttributeValueBoostingLevel.VERY_HIGH
ONE = StringAttributeValueBoostingLevel.ONE
TWO = StringAttributeValueBoostingLevel.TWO
THREE = StringAttributeValueBoostingLevel.THREE
FOUR = StringAttributeValueBoostingLevel.FOUR
FIVE = StringAttributeValueBoostingLevel.FIVE
Q_LITE = SubscriptionType.Q_LITE
Q_BUSINESS = SubscriptionType.Q_BUSINESS
RESPONSE = SystemMessageType.RESPONSE
GROUNDED_RESPONSE = SystemMessageType.GROUNDED_RESPONSE
CANNOT_PARSE = ValidationExceptionReason.CANNOT_PARSE
FIELD_VALIDATION_FAILED = ValidationExceptionReason.FIELD_VALIDATION_FAILED
UNKNOWN_OPERATION = ValidationExceptionReason.UNKNOWN_OPERATION
ENABLED = VideoExtractionStatus.ENABLED
DISABLED = VideoExtractionStatus.DISABLED
TRANSCRIPT = VideoExtractionType.TRANSCRIPT
SUMMARY = VideoExtractionType.SUMMARY
ENABLED = WebExperienceSamplePromptsControlMode.ENABLED
DISABLED = WebExperienceSamplePromptsControlMode.DISABLED
CREATING = WebExperienceStatus.CREATING
ACTIVE = WebExperienceStatus.ACTIVE
DELETING = WebExperienceStatus.DELETING
FAILED = WebExperienceStatus.FAILED
PENDING_AUTH_CONFIG = WebExperienceStatus.PENDING_AUTH_CONFIG


# PropertyType submodules (e.g., ec2.instance.NetworkInterface)
from . import application
from . import data_accessor
from . import data_source
from . import index
from . import permission
from . import plugin
from . import retriever
from . import web_experience


@dataclass
class Application(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-qbusi"""

    resource_type: ClassVar[str] = "AWS::QBusiness::Application"
    name_field: ClassVar[str] = "display_name"
    IDENTITY_TYPE = "IdentityType"
    DESCRIPTION = "Description"
    IDENTITY_CENTER_INSTANCE_ARN = "IdentityCenterInstanceArn"
    ENCRYPTION_CONFIGURATION = "EncryptionConfiguration"
    IAM_IDENTITY_PROVIDER_ARN = "IamIdentityProviderArn"
    ROLE_ARN = "RoleArn"
    ATTACHMENTS_CONFIGURATION = "AttachmentsConfiguration"
    CLIENT_IDS_FOR_OIDC = "ClientIdsForOIDC"
    QUICK_SIGHT_CONFIGURATION = "QuickSightConfiguration"
    PERSONALIZATION_CONFIGURATION = "PersonalizationConfiguration"
    DISPLAY_NAME = "DisplayName"
    AUTO_SUBSCRIPTION_CONFIGURATION = "AutoSubscriptionConfiguration"
    Q_APPS_CONFIGURATION = "QAppsConfiguration"
    TAGS = "Tags"

    _property_mappings: ClassVar[dict[str, str]] = {
        "identity_type": "IdentityType",
        "description": "Description",
        "identity_center_instance_arn": "IdentityCenterInstanceArn",
        "encryption_configuration": "EncryptionConfiguration",
        "iam_identity_provider_arn": "IamIdentityProviderArn",
        "role_arn": "RoleArn",
        "attachments_configuration": "AttachmentsConfiguration",
        "client_ids_for_oidc": "ClientIdsForOIDC",
        "quick_sight_configuration": "QuickSightConfiguration",
        "personalization_configuration": "PersonalizationConfiguration",
        "display_name": "DisplayName",
        "auto_subscription_configuration": "AutoSubscriptionConfiguration",
        "q_apps_configuration": "QAppsConfiguration",
        "tags": "Tags",
    }

    identity_type: Optional[Union[str, Ref, GetAtt, Sub]] = None
    description: Optional[Union[str, Ref, GetAtt, Sub]] = None
    identity_center_instance_arn: Optional[Union[str, Ref, GetAtt, Sub]] = None
    encryption_configuration: Optional[application.EncryptionConfiguration] = None
    iam_identity_provider_arn: Optional[Union[str, Ref, GetAtt, Sub]] = None
    role_arn: Optional[Union[str, Ref, GetAtt, Sub]] = None
    attachments_configuration: Optional[application.AttachmentsConfiguration] = None
    client_ids_for_oidc: Optional[Union[list[str], Ref]] = None
    quick_sight_configuration: Optional[application.QuickSightConfiguration] = None
    personalization_configuration: Optional[application.PersonalizationConfiguration] = None
    display_name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    auto_subscription_configuration: Optional[application.AutoSubscriptionConfiguration] = None
    q_apps_configuration: Optional[application.QAppsConfiguration] = None
    tags: Optional[list[application.Tag]] = None

    @property
    def attr_status(self) -> GetAtt:
        """Get the Status attribute."""
        return self.get_att("Status")

    @property
    def attr_identity_center_application_arn(self) -> GetAtt:
        """Get the IdentityCenterApplicationArn attribute."""
        return self.get_att("IdentityCenterApplicationArn")

    @property
    def attr_application_arn(self) -> GetAtt:
        """Get the ApplicationArn attribute."""
        return self.get_att("ApplicationArn")

    @property
    def attr_created_at(self) -> GetAtt:
        """Get the CreatedAt attribute."""
        return self.get_att("CreatedAt")

    @property
    def attr_application_id(self) -> GetAtt:
        """Get the ApplicationId attribute."""
        return self.get_att("ApplicationId")

    @property
    def attr_updated_at(self) -> GetAtt:
        """Get the UpdatedAt attribute."""
        return self.get_att("UpdatedAt")



@dataclass
class DataAccessor(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-qbusi"""

    resource_type: ClassVar[str] = "AWS::QBusiness::DataAccessor"
    name_field: ClassVar[str] = "display_name"
    DISPLAY_NAME = "DisplayName"
    ACTION_CONFIGURATIONS = "ActionConfigurations"
    APPLICATION_ID = "ApplicationId"
    PRINCIPAL = "Principal"
    TAGS = "Tags"
    AUTHENTICATION_DETAIL = "AuthenticationDetail"

    _property_mappings: ClassVar[dict[str, str]] = {
        "display_name": "DisplayName",
        "action_configurations": "ActionConfigurations",
        "application_id": "ApplicationId",
        "principal": "Principal",
        "tags": "Tags",
        "authentication_detail": "AuthenticationDetail",
    }

    display_name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    action_configurations: Optional[list[data_accessor.ActionConfiguration]] = None
    application_id: Optional[Union[str, Ref, GetAtt, Sub]] = None
    principal: Optional[Union[str, Ref, GetAtt, Sub]] = None
    tags: Optional[list[data_accessor.Tag]] = None
    authentication_detail: Optional[data_accessor.DataAccessorAuthenticationDetail] = None

    @property
    def attr_idc_application_arn(self) -> GetAtt:
        """Get the IdcApplicationArn attribute."""
        return self.get_att("IdcApplicationArn")

    @property
    def attr_created_at(self) -> GetAtt:
        """Get the CreatedAt attribute."""
        return self.get_att("CreatedAt")

    @property
    def attr_data_accessor_arn(self) -> GetAtt:
        """Get the DataAccessorArn attribute."""
        return self.get_att("DataAccessorArn")

    @property
    def attr_updated_at(self) -> GetAtt:
        """Get the UpdatedAt attribute."""
        return self.get_att("UpdatedAt")

    @property
    def attr_data_accessor_id(self) -> GetAtt:
        """Get the DataAccessorId attribute."""
        return self.get_att("DataAccessorId")



@dataclass
class DataSource(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-qbusi"""

    resource_type: ClassVar[str] = "AWS::QBusiness::DataSource"
    name_field: ClassVar[str] = "display_name"
    INDEX_ID = "IndexId"
    DESCRIPTION = "Description"
    CONFIGURATION = "Configuration"
    SYNC_SCHEDULE = "SyncSchedule"
    DOCUMENT_ENRICHMENT_CONFIGURATION = "DocumentEnrichmentConfiguration"
    MEDIA_EXTRACTION_CONFIGURATION = "MediaExtractionConfiguration"
    DISPLAY_NAME = "DisplayName"
    VPC_CONFIGURATION = "VpcConfiguration"
    APPLICATION_ID = "ApplicationId"
    ROLE_ARN = "RoleArn"
    TAGS = "Tags"

    _property_mappings: ClassVar[dict[str, str]] = {
        "index_id": "IndexId",
        "description": "Description",
        "configuration": "Configuration",
        "sync_schedule": "SyncSchedule",
        "document_enrichment_configuration": "DocumentEnrichmentConfiguration",
        "media_extraction_configuration": "MediaExtractionConfiguration",
        "display_name": "DisplayName",
        "vpc_configuration": "VpcConfiguration",
        "application_id": "ApplicationId",
        "role_arn": "RoleArn",
        "tags": "Tags",
    }

    index_id: Optional[Union[str, Ref, GetAtt, Sub]] = None
    description: Optional[Union[str, Ref, GetAtt, Sub]] = None
    configuration: Optional[Union[dict[str, Any], Ref, GetAtt, Sub]] = None
    sync_schedule: Optional[Union[str, Ref, GetAtt, Sub]] = None
    document_enrichment_configuration: Optional[data_source.DocumentEnrichmentConfiguration] = None
    media_extraction_configuration: Optional[data_source.MediaExtractionConfiguration] = None
    display_name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    vpc_configuration: Optional[data_source.DataSourceVpcConfiguration] = None
    application_id: Optional[Union[str, Ref, GetAtt, Sub]] = None
    role_arn: Optional[Union[str, Ref, GetAtt, Sub]] = None
    tags: Optional[list[data_source.Tag]] = None

    @property
    def attr_status(self) -> GetAtt:
        """Get the Status attribute."""
        return self.get_att("Status")

    @property
    def attr_data_source_arn(self) -> GetAtt:
        """Get the DataSourceArn attribute."""
        return self.get_att("DataSourceArn")

    @property
    def attr_type(self) -> GetAtt:
        """Get the Type attribute."""
        return self.get_att("Type")

    @property
    def attr_created_at(self) -> GetAtt:
        """Get the CreatedAt attribute."""
        return self.get_att("CreatedAt")

    @property
    def attr_updated_at(self) -> GetAtt:
        """Get the UpdatedAt attribute."""
        return self.get_att("UpdatedAt")

    @property
    def attr_data_source_id(self) -> GetAtt:
        """Get the DataSourceId attribute."""
        return self.get_att("DataSourceId")



@dataclass
class Index(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-qbusi"""

    resource_type: ClassVar[str] = "AWS::QBusiness::Index"
    name_field: ClassVar[str] = "display_name"
    TYPE = "Type"
    DESCRIPTION = "Description"
    DISPLAY_NAME = "DisplayName"
    DOCUMENT_ATTRIBUTE_CONFIGURATIONS = "DocumentAttributeConfigurations"
    APPLICATION_ID = "ApplicationId"
    TAGS = "Tags"
    CAPACITY_CONFIGURATION = "CapacityConfiguration"

    _property_mappings: ClassVar[dict[str, str]] = {
        "type_": "Type",
        "description": "Description",
        "display_name": "DisplayName",
        "document_attribute_configurations": "DocumentAttributeConfigurations",
        "application_id": "ApplicationId",
        "tags": "Tags",
        "capacity_configuration": "CapacityConfiguration",
    }

    type_: Optional[Union[str, Ref, GetAtt, Sub]] = None
    description: Optional[Union[str, Ref, GetAtt, Sub]] = None
    display_name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    document_attribute_configurations: Optional[list[index.DocumentAttributeConfiguration]] = None
    application_id: Optional[Union[str, Ref, GetAtt, Sub]] = None
    tags: Optional[list[index.Tag]] = None
    capacity_configuration: Optional[index.IndexCapacityConfiguration] = None

    @property
    def attr_status(self) -> GetAtt:
        """Get the Status attribute."""
        return self.get_att("Status")

    @property
    def attr_index_statistics(self) -> GetAtt:
        """Get the IndexStatistics attribute."""
        return self.get_att("IndexStatistics")

    @property
    def attr_index_statistics__text_document_statistics__indexed_text_document_count(self) -> GetAtt:
        """Get the IndexStatistics.TextDocumentStatistics.IndexedTextDocumentCount attribute."""
        return self.get_att("IndexStatistics.TextDocumentStatistics.IndexedTextDocumentCount")

    @property
    def attr_index_id(self) -> GetAtt:
        """Get the IndexId attribute."""
        return self.get_att("IndexId")

    @property
    def attr_index_arn(self) -> GetAtt:
        """Get the IndexArn attribute."""
        return self.get_att("IndexArn")

    @property
    def attr_index_statistics__text_document_statistics(self) -> GetAtt:
        """Get the IndexStatistics.TextDocumentStatistics attribute."""
        return self.get_att("IndexStatistics.TextDocumentStatistics")

    @property
    def attr_created_at(self) -> GetAtt:
        """Get the CreatedAt attribute."""
        return self.get_att("CreatedAt")

    @property
    def attr_index_statistics__text_document_statistics__indexed_text_bytes(self) -> GetAtt:
        """Get the IndexStatistics.TextDocumentStatistics.IndexedTextBytes attribute."""
        return self.get_att("IndexStatistics.TextDocumentStatistics.IndexedTextBytes")

    @property
    def attr_updated_at(self) -> GetAtt:
        """Get the UpdatedAt attribute."""
        return self.get_att("UpdatedAt")



@dataclass
class Permission(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-qbusi"""

    resource_type: ClassVar[str] = "AWS::QBusiness::Permission"
    ACTIONS = "Actions"
    STATEMENT_ID = "StatementId"
    APPLICATION_ID = "ApplicationId"
    CONDITIONS = "Conditions"
    PRINCIPAL = "Principal"

    _property_mappings: ClassVar[dict[str, str]] = {
        "actions": "Actions",
        "statement_id": "StatementId",
        "application_id": "ApplicationId",
        "conditions": "Conditions",
        "principal": "Principal",
    }

    actions: Optional[Union[list[str], Ref]] = None
    statement_id: Optional[Union[str, Ref, GetAtt, Sub]] = None
    application_id: Optional[Union[str, Ref, GetAtt, Sub]] = None
    conditions: Optional[list[permission.Condition]] = None
    principal: Optional[Union[str, Ref, GetAtt, Sub]] = None


@dataclass
class Plugin(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-qbusi"""

    resource_type: ClassVar[str] = "AWS::QBusiness::Plugin"
    name_field: ClassVar[str] = "display_name"
    SERVER_URL = "ServerUrl"
    CUSTOM_PLUGIN_CONFIGURATION = "CustomPluginConfiguration"
    TYPE = "Type"
    STATE = "State"
    DISPLAY_NAME = "DisplayName"
    AUTH_CONFIGURATION = "AuthConfiguration"
    APPLICATION_ID = "ApplicationId"
    TAGS = "Tags"

    _property_mappings: ClassVar[dict[str, str]] = {
        "server_url": "ServerUrl",
        "custom_plugin_configuration": "CustomPluginConfiguration",
        "type_": "Type",
        "state": "State",
        "display_name": "DisplayName",
        "auth_configuration": "AuthConfiguration",
        "application_id": "ApplicationId",
        "tags": "Tags",
    }

    server_url: Optional[Union[str, Ref, GetAtt, Sub]] = None
    custom_plugin_configuration: Optional[plugin.CustomPluginConfiguration] = None
    type_: Optional[Union[str, Ref, GetAtt, Sub]] = None
    state: Optional[Union[str, Ref, GetAtt, Sub]] = None
    display_name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    auth_configuration: Optional[plugin.PluginAuthConfiguration] = None
    application_id: Optional[Union[str, Ref, GetAtt, Sub]] = None
    tags: Optional[list[plugin.Tag]] = None

    @property
    def attr_plugin_arn(self) -> GetAtt:
        """Get the PluginArn attribute."""
        return self.get_att("PluginArn")

    @property
    def attr_created_at(self) -> GetAtt:
        """Get the CreatedAt attribute."""
        return self.get_att("CreatedAt")

    @property
    def attr_build_status(self) -> GetAtt:
        """Get the BuildStatus attribute."""
        return self.get_att("BuildStatus")

    @property
    def attr_plugin_id(self) -> GetAtt:
        """Get the PluginId attribute."""
        return self.get_att("PluginId")

    @property
    def attr_updated_at(self) -> GetAtt:
        """Get the UpdatedAt attribute."""
        return self.get_att("UpdatedAt")



@dataclass
class Retriever(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-qbusi"""

    resource_type: ClassVar[str] = "AWS::QBusiness::Retriever"
    name_field: ClassVar[str] = "display_name"
    TYPE = "Type"
    CONFIGURATION = "Configuration"
    DISPLAY_NAME = "DisplayName"
    APPLICATION_ID = "ApplicationId"
    ROLE_ARN = "RoleArn"
    TAGS = "Tags"

    _property_mappings: ClassVar[dict[str, str]] = {
        "type_": "Type",
        "configuration": "Configuration",
        "display_name": "DisplayName",
        "application_id": "ApplicationId",
        "role_arn": "RoleArn",
        "tags": "Tags",
    }

    type_: Optional[Union[str, Ref, GetAtt, Sub]] = None
    configuration: Optional[retriever.RetrieverConfiguration] = None
    display_name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    application_id: Optional[Union[str, Ref, GetAtt, Sub]] = None
    role_arn: Optional[Union[str, Ref, GetAtt, Sub]] = None
    tags: Optional[list[retriever.Tag]] = None

    @property
    def attr_status(self) -> GetAtt:
        """Get the Status attribute."""
        return self.get_att("Status")

    @property
    def attr_retriever_arn(self) -> GetAtt:
        """Get the RetrieverArn attribute."""
        return self.get_att("RetrieverArn")

    @property
    def attr_created_at(self) -> GetAtt:
        """Get the CreatedAt attribute."""
        return self.get_att("CreatedAt")

    @property
    def attr_retriever_id(self) -> GetAtt:
        """Get the RetrieverId attribute."""
        return self.get_att("RetrieverId")

    @property
    def attr_updated_at(self) -> GetAtt:
        """Get the UpdatedAt attribute."""
        return self.get_att("UpdatedAt")



@dataclass
class WebExperience(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-qbusi"""

    resource_type: ClassVar[str] = "AWS::QBusiness::WebExperience"
    ORIGINS = "Origins"
    SUBTITLE = "Subtitle"
    CUSTOMIZATION_CONFIGURATION = "CustomizationConfiguration"
    SAMPLE_PROMPTS_CONTROL_MODE = "SamplePromptsControlMode"
    TITLE = "Title"
    IDENTITY_PROVIDER_CONFIGURATION = "IdentityProviderConfiguration"
    WELCOME_MESSAGE = "WelcomeMessage"
    APPLICATION_ID = "ApplicationId"
    ROLE_ARN = "RoleArn"
    TAGS = "Tags"
    BROWSER_EXTENSION_CONFIGURATION = "BrowserExtensionConfiguration"

    _property_mappings: ClassVar[dict[str, str]] = {
        "origins": "Origins",
        "subtitle": "Subtitle",
        "customization_configuration": "CustomizationConfiguration",
        "sample_prompts_control_mode": "SamplePromptsControlMode",
        "title": "Title",
        "identity_provider_configuration": "IdentityProviderConfiguration",
        "welcome_message": "WelcomeMessage",
        "application_id": "ApplicationId",
        "role_arn": "RoleArn",
        "tags": "Tags",
        "browser_extension_configuration": "BrowserExtensionConfiguration",
    }

    origins: Optional[Union[list[str], Ref]] = None
    subtitle: Optional[Union[str, Ref, GetAtt, Sub]] = None
    customization_configuration: Optional[web_experience.CustomizationConfiguration] = None
    sample_prompts_control_mode: Optional[Union[str, Ref, GetAtt, Sub]] = None
    title: Optional[Union[str, Ref, GetAtt, Sub]] = None
    identity_provider_configuration: Optional[web_experience.IdentityProviderConfiguration] = None
    welcome_message: Optional[Union[str, Ref, GetAtt, Sub]] = None
    application_id: Optional[Union[str, Ref, GetAtt, Sub]] = None
    role_arn: Optional[Union[str, Ref, GetAtt, Sub]] = None
    tags: Optional[list[web_experience.Tag]] = None
    browser_extension_configuration: Optional[web_experience.BrowserExtensionConfiguration] = None

    @property
    def attr_status(self) -> GetAtt:
        """Get the Status attribute."""
        return self.get_att("Status")

    @property
    def attr_web_experience_id(self) -> GetAtt:
        """Get the WebExperienceId attribute."""
        return self.get_att("WebExperienceId")

    @property
    def attr_default_endpoint(self) -> GetAtt:
        """Get the DefaultEndpoint attribute."""
        return self.get_att("DefaultEndpoint")

    @property
    def attr_web_experience_arn(self) -> GetAtt:
        """Get the WebExperienceArn attribute."""
        return self.get_att("WebExperienceArn")

    @property
    def attr_created_at(self) -> GetAtt:
        """Get the CreatedAt attribute."""
        return self.get_att("CreatedAt")

    @property
    def attr_updated_at(self) -> GetAtt:
        """Get the UpdatedAt attribute."""
        return self.get_att("UpdatedAt")


