"""
AWS CloudFormation VoiceID Resources

⚠️  AUTO-GENERATED FILE - DO NOT EDIT MANUALLY ⚠️

This file is automatically generated from the AWS CloudFormation Resource Specification.
Any manual changes will be overwritten when regenerated.

Version Information:
  CloudFormation Spec: 2025.12.11
  Generator Version: 1.0.0
  Combined: spec-2025.12.11_gen-1.0.0
  Generated: 2025-12-22 18:51:21

To regenerate:
    uv run python -m cloudformation_dataclasses.codegen.generator --service VoiceID
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, ClassVar, Optional, Union

from cloudformation_dataclasses.core.base import CloudFormationResource, PropertyType, Tag
from cloudformation_dataclasses.intrinsics.functions import GetAtt, Ref, Sub


# PropertyType submodules (e.g., ec2.instance.NetworkInterface)
from . import domain


@dataclass
class Domain(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-voice"""

    resource_type: ClassVar[str] = "AWS::VoiceID::Domain"
    name_field: ClassVar[str] = "name"
    DESCRIPTION = "Description"
    SERVER_SIDE_ENCRYPTION_CONFIGURATION = "ServerSideEncryptionConfiguration"
    TAGS = "Tags"
    NAME = "Name"

    _property_mappings: ClassVar[dict[str, str]] = {
        "description": "Description",
        "server_side_encryption_configuration": "ServerSideEncryptionConfiguration",
        "tags": "Tags",
        "name": "Name",
    }

    description: Optional[Union[str, Ref, GetAtt, Sub]] = None
    server_side_encryption_configuration: Optional[domain.ServerSideEncryptionConfiguration] = None
    tags: Optional[list[domain.Tag]] = None
    name: Optional[Union[str, Ref, GetAtt, Sub]] = None

    @property
    def attr_domain_id(self) -> GetAtt:
        """Get the DomainId attribute."""
        return self.get_att("DomainId")


