"""Generated by cfn-dataclasses-import."""

from cloudformation_dataclasses.core import (
    NUMBER,
    Parameter,
    ParameterType,
    Template,
    cloudformation_dataclass,
    get_att,
    ref,
)
from cloudformation_dataclasses.aws import s3

from .stack import *  # noqa: F403, F401

__all__ = [
    "BucketToCopyA",
    "BucketToCopyB",
    "BucketToCopyC",
    "BucketToCopyD",
    "NUMBER",
    "Parameter",
    "ParameterType",
    "Template",
    "TestCount",
    "TestList",
    "cloudformation_dataclass",
    "get_att",
    "ref",
    "s3",
]
