"""
AWS CloudFormation IoTFleetWise Resources

⚠️  AUTO-GENERATED FILE - DO NOT EDIT MANUALLY ⚠️

This file is automatically generated from the AWS CloudFormation Resource Specification.
Any manual changes will be overwritten when regenerated.

Version Information:
  CloudFormation Spec: 2025.12.11
  Generator Version: 1.0.0
  Combined: spec-2025.12.11_gen-1.0.0
  Generated: 2025-12-22 14:55:25

To regenerate:
    uv run python -m cloudformation_dataclasses.codegen.generator --service IoTFleetWise
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, ClassVar, Optional, Union

from cloudformation_dataclasses.core.base import CloudFormationResource, PropertyType, Tag
from cloudformation_dataclasses.intrinsics.functions import GetAtt, Ref, Sub


# =============================================================================
# Service Constants (auto-generated from botocore)
# =============================================================================

class CampaignStatus:
    """CampaignStatus enum values."""

    CREATING = "CREATING"
    WAITING_FOR_APPROVAL = "WAITING_FOR_APPROVAL"
    RUNNING = "RUNNING"
    SUSPENDED = "SUSPENDED"


class Compression:
    """Compression enum values."""

    OFF = "OFF"
    SNAPPY = "SNAPPY"


class DataFormat:
    """DataFormat enum values."""

    JSON = "JSON"
    PARQUET = "PARQUET"


class DefaultForUnmappedSignalsType:
    """DefaultForUnmappedSignalsType enum values."""

    CUSTOM_DECODING = "CUSTOM_DECODING"


class DiagnosticsMode:
    """DiagnosticsMode enum values."""

    OFF = "OFF"
    SEND_ACTIVE_DTCS = "SEND_ACTIVE_DTCS"


class EncryptionStatus:
    """EncryptionStatus enum values."""

    PENDING = "PENDING"
    SUCCESS = "SUCCESS"
    FAILURE = "FAILURE"


class EncryptionType:
    """EncryptionType enum values."""

    KMS_BASED_ENCRYPTION = "KMS_BASED_ENCRYPTION"
    FLEETWISE_DEFAULT_ENCRYPTION = "FLEETWISE_DEFAULT_ENCRYPTION"


class ListResponseScope:
    """ListResponseScope enum values."""

    METADATA_ONLY = "METADATA_ONLY"


class LogType:
    """LogType enum values."""

    OFF = "OFF"
    ERROR = "ERROR"


class ManifestStatus:
    """ManifestStatus enum values."""

    ACTIVE = "ACTIVE"
    DRAFT = "DRAFT"
    INVALID = "INVALID"
    VALIDATING = "VALIDATING"


class NetworkInterfaceFailureReason:
    """NetworkInterfaceFailureReason enum values."""

    DUPLICATE_NETWORK_INTERFACE = "DUPLICATE_NETWORK_INTERFACE"
    CONFLICTING_NETWORK_INTERFACE = "CONFLICTING_NETWORK_INTERFACE"
    NETWORK_INTERFACE_TO_ADD_ALREADY_EXISTS = "NETWORK_INTERFACE_TO_ADD_ALREADY_EXISTS"
    CAN_NETWORK_INTERFACE_INFO_IS_NULL = "CAN_NETWORK_INTERFACE_INFO_IS_NULL"
    OBD_NETWORK_INTERFACE_INFO_IS_NULL = "OBD_NETWORK_INTERFACE_INFO_IS_NULL"
    NETWORK_INTERFACE_TO_REMOVE_ASSOCIATED_WITH_SIGNALS = "NETWORK_INTERFACE_TO_REMOVE_ASSOCIATED_WITH_SIGNALS"
    VEHICLE_MIDDLEWARE_NETWORK_INTERFACE_INFO_IS_NULL = "VEHICLE_MIDDLEWARE_NETWORK_INTERFACE_INFO_IS_NULL"
    CUSTOM_DECODING_SIGNAL_NETWORK_INTERFACE_INFO_IS_NULL = "CUSTOM_DECODING_SIGNAL_NETWORK_INTERFACE_INFO_IS_NULL"


class NetworkInterfaceType:
    """NetworkInterfaceType enum values."""

    CAN_INTERFACE = "CAN_INTERFACE"
    OBD_INTERFACE = "OBD_INTERFACE"
    VEHICLE_MIDDLEWARE = "VEHICLE_MIDDLEWARE"
    CUSTOM_DECODING_INTERFACE = "CUSTOM_DECODING_INTERFACE"


class NodeDataEncoding:
    """NodeDataEncoding enum values."""

    BINARY = "BINARY"
    TYPED = "TYPED"


class NodeDataType:
    """NodeDataType enum values."""

    INT8 = "INT8"
    UINT8 = "UINT8"
    INT16 = "INT16"
    UINT16 = "UINT16"
    INT32 = "INT32"
    UINT32 = "UINT32"
    INT64 = "INT64"
    UINT64 = "UINT64"
    BOOLEAN = "BOOLEAN"
    FLOAT = "FLOAT"
    DOUBLE = "DOUBLE"
    STRING = "STRING"
    UNIX_TIMESTAMP = "UNIX_TIMESTAMP"
    INT8_ARRAY = "INT8_ARRAY"
    UINT8_ARRAY = "UINT8_ARRAY"
    INT16_ARRAY = "INT16_ARRAY"
    UINT16_ARRAY = "UINT16_ARRAY"
    INT32_ARRAY = "INT32_ARRAY"
    UINT32_ARRAY = "UINT32_ARRAY"
    INT64_ARRAY = "INT64_ARRAY"
    UINT64_ARRAY = "UINT64_ARRAY"
    BOOLEAN_ARRAY = "BOOLEAN_ARRAY"
    FLOAT_ARRAY = "FLOAT_ARRAY"
    DOUBLE_ARRAY = "DOUBLE_ARRAY"
    STRING_ARRAY = "STRING_ARRAY"
    UNIX_TIMESTAMP_ARRAY = "UNIX_TIMESTAMP_ARRAY"
    UNKNOWN = "UNKNOWN"
    STRUCT = "STRUCT"
    STRUCT_ARRAY = "STRUCT_ARRAY"


class ROS2PrimitiveType:
    """ROS2PrimitiveType enum values."""

    BOOL = "BOOL"
    BYTE = "BYTE"
    CHAR = "CHAR"
    FLOAT32 = "FLOAT32"
    FLOAT64 = "FLOAT64"
    INT8 = "INT8"
    UINT8 = "UINT8"
    INT16 = "INT16"
    UINT16 = "UINT16"
    INT32 = "INT32"
    UINT32 = "UINT32"
    INT64 = "INT64"
    UINT64 = "UINT64"
    STRING = "STRING"
    WSTRING = "WSTRING"


class RegistrationStatus:
    """RegistrationStatus enum values."""

    REGISTRATION_PENDING = "REGISTRATION_PENDING"
    REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS"
    REGISTRATION_FAILURE = "REGISTRATION_FAILURE"


class SignalDecoderFailureReason:
    """SignalDecoderFailureReason enum values."""

    DUPLICATE_SIGNAL = "DUPLICATE_SIGNAL"
    CONFLICTING_SIGNAL = "CONFLICTING_SIGNAL"
    SIGNAL_TO_ADD_ALREADY_EXISTS = "SIGNAL_TO_ADD_ALREADY_EXISTS"
    SIGNAL_NOT_ASSOCIATED_WITH_NETWORK_INTERFACE = "SIGNAL_NOT_ASSOCIATED_WITH_NETWORK_INTERFACE"
    NETWORK_INTERFACE_TYPE_INCOMPATIBLE_WITH_SIGNAL_DECODER_TYPE = "NETWORK_INTERFACE_TYPE_INCOMPATIBLE_WITH_SIGNAL_DECODER_TYPE"
    SIGNAL_NOT_IN_MODEL = "SIGNAL_NOT_IN_MODEL"
    CAN_SIGNAL_INFO_IS_NULL = "CAN_SIGNAL_INFO_IS_NULL"
    OBD_SIGNAL_INFO_IS_NULL = "OBD_SIGNAL_INFO_IS_NULL"
    NO_DECODER_INFO_FOR_SIGNAL_IN_MODEL = "NO_DECODER_INFO_FOR_SIGNAL_IN_MODEL"
    MESSAGE_SIGNAL_INFO_IS_NULL = "MESSAGE_SIGNAL_INFO_IS_NULL"
    SIGNAL_DECODER_TYPE_INCOMPATIBLE_WITH_MESSAGE_SIGNAL_TYPE = "SIGNAL_DECODER_TYPE_INCOMPATIBLE_WITH_MESSAGE_SIGNAL_TYPE"
    STRUCT_SIZE_MISMATCH = "STRUCT_SIZE_MISMATCH"
    NO_SIGNAL_IN_CATALOG_FOR_DECODER_SIGNAL = "NO_SIGNAL_IN_CATALOG_FOR_DECODER_SIGNAL"
    SIGNAL_DECODER_INCOMPATIBLE_WITH_SIGNAL_CATALOG = "SIGNAL_DECODER_INCOMPATIBLE_WITH_SIGNAL_CATALOG"
    EMPTY_MESSAGE_SIGNAL = "EMPTY_MESSAGE_SIGNAL"
    CUSTOM_DECODING_SIGNAL_INFO_IS_NULL = "CUSTOM_DECODING_SIGNAL_INFO_IS_NULL"


class SignalDecoderType:
    """SignalDecoderType enum values."""

    CAN_SIGNAL = "CAN_SIGNAL"
    OBD_SIGNAL = "OBD_SIGNAL"
    MESSAGE_SIGNAL = "MESSAGE_SIGNAL"
    CUSTOM_DECODING_SIGNAL = "CUSTOM_DECODING_SIGNAL"


class SignalNodeType:
    """SignalNodeType enum values."""

    SENSOR = "SENSOR"
    ACTUATOR = "ACTUATOR"
    ATTRIBUTE = "ATTRIBUTE"
    BRANCH = "BRANCH"
    CUSTOM_STRUCT = "CUSTOM_STRUCT"
    CUSTOM_PROPERTY = "CUSTOM_PROPERTY"


class SignalValueType:
    """SignalValueType enum values."""

    INTEGER = "INTEGER"
    FLOATING_POINT = "FLOATING_POINT"


class SpoolingMode:
    """SpoolingMode enum values."""

    OFF = "OFF"
    TO_DISK = "TO_DISK"


class StorageCompressionFormat:
    """StorageCompressionFormat enum values."""

    NONE = "NONE"
    GZIP = "GZIP"


class StorageMaximumSizeUnit:
    """StorageMaximumSizeUnit enum values."""

    MB = "MB"
    GB = "GB"
    TB = "TB"


class StorageMinimumTimeToLiveUnit:
    """StorageMinimumTimeToLiveUnit enum values."""

    HOURS = "HOURS"
    DAYS = "DAYS"
    WEEKS = "WEEKS"


class StructuredMessageListType:
    """StructuredMessageListType enum values."""

    FIXED_CAPACITY = "FIXED_CAPACITY"
    DYNAMIC_UNBOUNDED_CAPACITY = "DYNAMIC_UNBOUNDED_CAPACITY"
    DYNAMIC_BOUNDED_CAPACITY = "DYNAMIC_BOUNDED_CAPACITY"


class TimeUnit:
    """TimeUnit enum values."""

    MILLISECOND = "MILLISECOND"
    SECOND = "SECOND"
    MINUTE = "MINUTE"
    HOUR = "HOUR"


class TriggerMode:
    """TriggerMode enum values."""

    ALWAYS = "ALWAYS"
    RISING_EDGE = "RISING_EDGE"


class UpdateCampaignAction:
    """UpdateCampaignAction enum values."""

    APPROVE = "APPROVE"
    SUSPEND = "SUSPEND"
    RESUME = "RESUME"
    UPDATE = "UPDATE"


class UpdateMode:
    """UpdateMode enum values."""

    OVERWRITE = "Overwrite"
    MERGE = "Merge"


class ValidationExceptionReason:
    """ValidationExceptionReason enum values."""

    UNKNOWNOPERATION = "unknownOperation"
    CANNOTPARSE = "cannotParse"
    FIELDVALIDATIONFAILED = "fieldValidationFailed"
    OTHER = "other"


class VehicleAssociationBehavior:
    """VehicleAssociationBehavior enum values."""

    CREATEIOTTHING = "CreateIotThing"
    VALIDATEIOTTHINGEXISTS = "ValidateIotThingExists"


class VehicleMiddlewareProtocol:
    """VehicleMiddlewareProtocol enum values."""

    ROS_2 = "ROS_2"


class VehicleState:
    """VehicleState enum values."""

    CREATED = "CREATED"
    READY = "READY"
    HEALTHY = "HEALTHY"
    SUSPENDED = "SUSPENDED"
    DELETING = "DELETING"
    READY_FOR_CHECKIN = "READY_FOR_CHECKIN"


# Convenient aliases for enum values
CREATING = CampaignStatus.CREATING
WAITING_FOR_APPROVAL = CampaignStatus.WAITING_FOR_APPROVAL
RUNNING = CampaignStatus.RUNNING
SUSPENDED = CampaignStatus.SUSPENDED
OFF = Compression.OFF
SNAPPY = Compression.SNAPPY
JSON = DataFormat.JSON
PARQUET = DataFormat.PARQUET
CUSTOM_DECODING = DefaultForUnmappedSignalsType.CUSTOM_DECODING
OFF = DiagnosticsMode.OFF
SEND_ACTIVE_DTCS = DiagnosticsMode.SEND_ACTIVE_DTCS
PENDING = EncryptionStatus.PENDING
SUCCESS = EncryptionStatus.SUCCESS
FAILURE = EncryptionStatus.FAILURE
KMS_BASED_ENCRYPTION = EncryptionType.KMS_BASED_ENCRYPTION
FLEETWISE_DEFAULT_ENCRYPTION = EncryptionType.FLEETWISE_DEFAULT_ENCRYPTION
METADATA_ONLY = ListResponseScope.METADATA_ONLY
OFF = LogType.OFF
ERROR = LogType.ERROR
ACTIVE = ManifestStatus.ACTIVE
DRAFT = ManifestStatus.DRAFT
INVALID = ManifestStatus.INVALID
VALIDATING = ManifestStatus.VALIDATING
DUPLICATE_NETWORK_INTERFACE = NetworkInterfaceFailureReason.DUPLICATE_NETWORK_INTERFACE
CONFLICTING_NETWORK_INTERFACE = NetworkInterfaceFailureReason.CONFLICTING_NETWORK_INTERFACE
NETWORK_INTERFACE_TO_ADD_ALREADY_EXISTS = NetworkInterfaceFailureReason.NETWORK_INTERFACE_TO_ADD_ALREADY_EXISTS
CAN_NETWORK_INTERFACE_INFO_IS_NULL = NetworkInterfaceFailureReason.CAN_NETWORK_INTERFACE_INFO_IS_NULL
OBD_NETWORK_INTERFACE_INFO_IS_NULL = NetworkInterfaceFailureReason.OBD_NETWORK_INTERFACE_INFO_IS_NULL
NETWORK_INTERFACE_TO_REMOVE_ASSOCIATED_WITH_SIGNALS = NetworkInterfaceFailureReason.NETWORK_INTERFACE_TO_REMOVE_ASSOCIATED_WITH_SIGNALS
VEHICLE_MIDDLEWARE_NETWORK_INTERFACE_INFO_IS_NULL = NetworkInterfaceFailureReason.VEHICLE_MIDDLEWARE_NETWORK_INTERFACE_INFO_IS_NULL
CUSTOM_DECODING_SIGNAL_NETWORK_INTERFACE_INFO_IS_NULL = NetworkInterfaceFailureReason.CUSTOM_DECODING_SIGNAL_NETWORK_INTERFACE_INFO_IS_NULL
CAN_INTERFACE = NetworkInterfaceType.CAN_INTERFACE
OBD_INTERFACE = NetworkInterfaceType.OBD_INTERFACE
VEHICLE_MIDDLEWARE = NetworkInterfaceType.VEHICLE_MIDDLEWARE
CUSTOM_DECODING_INTERFACE = NetworkInterfaceType.CUSTOM_DECODING_INTERFACE
BINARY = NodeDataEncoding.BINARY
TYPED = NodeDataEncoding.TYPED
INT8 = NodeDataType.INT8
UINT8 = NodeDataType.UINT8
INT16 = NodeDataType.INT16
UINT16 = NodeDataType.UINT16
INT32 = NodeDataType.INT32
UINT32 = NodeDataType.UINT32
INT64 = NodeDataType.INT64
UINT64 = NodeDataType.UINT64
BOOLEAN = NodeDataType.BOOLEAN
FLOAT = NodeDataType.FLOAT
DOUBLE = NodeDataType.DOUBLE
STRING = NodeDataType.STRING
UNIX_TIMESTAMP = NodeDataType.UNIX_TIMESTAMP
INT8_ARRAY = NodeDataType.INT8_ARRAY
UINT8_ARRAY = NodeDataType.UINT8_ARRAY
INT16_ARRAY = NodeDataType.INT16_ARRAY
UINT16_ARRAY = NodeDataType.UINT16_ARRAY
INT32_ARRAY = NodeDataType.INT32_ARRAY
UINT32_ARRAY = NodeDataType.UINT32_ARRAY
INT64_ARRAY = NodeDataType.INT64_ARRAY
UINT64_ARRAY = NodeDataType.UINT64_ARRAY
BOOLEAN_ARRAY = NodeDataType.BOOLEAN_ARRAY
FLOAT_ARRAY = NodeDataType.FLOAT_ARRAY
DOUBLE_ARRAY = NodeDataType.DOUBLE_ARRAY
STRING_ARRAY = NodeDataType.STRING_ARRAY
UNIX_TIMESTAMP_ARRAY = NodeDataType.UNIX_TIMESTAMP_ARRAY
UNKNOWN = NodeDataType.UNKNOWN
STRUCT = NodeDataType.STRUCT
STRUCT_ARRAY = NodeDataType.STRUCT_ARRAY
BOOL = ROS2PrimitiveType.BOOL
BYTE = ROS2PrimitiveType.BYTE
CHAR = ROS2PrimitiveType.CHAR
FLOAT32 = ROS2PrimitiveType.FLOAT32
FLOAT64 = ROS2PrimitiveType.FLOAT64
INT8 = ROS2PrimitiveType.INT8
UINT8 = ROS2PrimitiveType.UINT8
INT16 = ROS2PrimitiveType.INT16
UINT16 = ROS2PrimitiveType.UINT16
INT32 = ROS2PrimitiveType.INT32
UINT32 = ROS2PrimitiveType.UINT32
INT64 = ROS2PrimitiveType.INT64
UINT64 = ROS2PrimitiveType.UINT64
STRING = ROS2PrimitiveType.STRING
WSTRING = ROS2PrimitiveType.WSTRING
REGISTRATION_PENDING = RegistrationStatus.REGISTRATION_PENDING
REGISTRATION_SUCCESS = RegistrationStatus.REGISTRATION_SUCCESS
REGISTRATION_FAILURE = RegistrationStatus.REGISTRATION_FAILURE
DUPLICATE_SIGNAL = SignalDecoderFailureReason.DUPLICATE_SIGNAL
CONFLICTING_SIGNAL = SignalDecoderFailureReason.CONFLICTING_SIGNAL
SIGNAL_TO_ADD_ALREADY_EXISTS = SignalDecoderFailureReason.SIGNAL_TO_ADD_ALREADY_EXISTS
SIGNAL_NOT_ASSOCIATED_WITH_NETWORK_INTERFACE = SignalDecoderFailureReason.SIGNAL_NOT_ASSOCIATED_WITH_NETWORK_INTERFACE
NETWORK_INTERFACE_TYPE_INCOMPATIBLE_WITH_SIGNAL_DECODER_TYPE = SignalDecoderFailureReason.NETWORK_INTERFACE_TYPE_INCOMPATIBLE_WITH_SIGNAL_DECODER_TYPE
SIGNAL_NOT_IN_MODEL = SignalDecoderFailureReason.SIGNAL_NOT_IN_MODEL
CAN_SIGNAL_INFO_IS_NULL = SignalDecoderFailureReason.CAN_SIGNAL_INFO_IS_NULL
OBD_SIGNAL_INFO_IS_NULL = SignalDecoderFailureReason.OBD_SIGNAL_INFO_IS_NULL
NO_DECODER_INFO_FOR_SIGNAL_IN_MODEL = SignalDecoderFailureReason.NO_DECODER_INFO_FOR_SIGNAL_IN_MODEL
MESSAGE_SIGNAL_INFO_IS_NULL = SignalDecoderFailureReason.MESSAGE_SIGNAL_INFO_IS_NULL
SIGNAL_DECODER_TYPE_INCOMPATIBLE_WITH_MESSAGE_SIGNAL_TYPE = SignalDecoderFailureReason.SIGNAL_DECODER_TYPE_INCOMPATIBLE_WITH_MESSAGE_SIGNAL_TYPE
STRUCT_SIZE_MISMATCH = SignalDecoderFailureReason.STRUCT_SIZE_MISMATCH
NO_SIGNAL_IN_CATALOG_FOR_DECODER_SIGNAL = SignalDecoderFailureReason.NO_SIGNAL_IN_CATALOG_FOR_DECODER_SIGNAL
SIGNAL_DECODER_INCOMPATIBLE_WITH_SIGNAL_CATALOG = SignalDecoderFailureReason.SIGNAL_DECODER_INCOMPATIBLE_WITH_SIGNAL_CATALOG
EMPTY_MESSAGE_SIGNAL = SignalDecoderFailureReason.EMPTY_MESSAGE_SIGNAL
CUSTOM_DECODING_SIGNAL_INFO_IS_NULL = SignalDecoderFailureReason.CUSTOM_DECODING_SIGNAL_INFO_IS_NULL
CAN_SIGNAL = SignalDecoderType.CAN_SIGNAL
OBD_SIGNAL = SignalDecoderType.OBD_SIGNAL
MESSAGE_SIGNAL = SignalDecoderType.MESSAGE_SIGNAL
CUSTOM_DECODING_SIGNAL = SignalDecoderType.CUSTOM_DECODING_SIGNAL
SENSOR = SignalNodeType.SENSOR
ACTUATOR = SignalNodeType.ACTUATOR
ATTRIBUTE = SignalNodeType.ATTRIBUTE
BRANCH = SignalNodeType.BRANCH
CUSTOM_STRUCT = SignalNodeType.CUSTOM_STRUCT
CUSTOM_PROPERTY = SignalNodeType.CUSTOM_PROPERTY
INTEGER = SignalValueType.INTEGER
FLOATING_POINT = SignalValueType.FLOATING_POINT
OFF = SpoolingMode.OFF
TO_DISK = SpoolingMode.TO_DISK
NONE = StorageCompressionFormat.NONE
GZIP = StorageCompressionFormat.GZIP
MB = StorageMaximumSizeUnit.MB
GB = StorageMaximumSizeUnit.GB
TB = StorageMaximumSizeUnit.TB
HOURS = StorageMinimumTimeToLiveUnit.HOURS
DAYS = StorageMinimumTimeToLiveUnit.DAYS
WEEKS = StorageMinimumTimeToLiveUnit.WEEKS
FIXED_CAPACITY = StructuredMessageListType.FIXED_CAPACITY
DYNAMIC_UNBOUNDED_CAPACITY = StructuredMessageListType.DYNAMIC_UNBOUNDED_CAPACITY
DYNAMIC_BOUNDED_CAPACITY = StructuredMessageListType.DYNAMIC_BOUNDED_CAPACITY
MILLISECOND = TimeUnit.MILLISECOND
SECOND = TimeUnit.SECOND
MINUTE = TimeUnit.MINUTE
HOUR = TimeUnit.HOUR
ALWAYS = TriggerMode.ALWAYS
RISING_EDGE = TriggerMode.RISING_EDGE
APPROVE = UpdateCampaignAction.APPROVE
SUSPEND = UpdateCampaignAction.SUSPEND
RESUME = UpdateCampaignAction.RESUME
UPDATE = UpdateCampaignAction.UPDATE
OVERWRITE = UpdateMode.OVERWRITE
MERGE = UpdateMode.MERGE
UNKNOWNOPERATION = ValidationExceptionReason.UNKNOWNOPERATION
CANNOTPARSE = ValidationExceptionReason.CANNOTPARSE
FIELDVALIDATIONFAILED = ValidationExceptionReason.FIELDVALIDATIONFAILED
OTHER = ValidationExceptionReason.OTHER
CREATEIOTTHING = VehicleAssociationBehavior.CREATEIOTTHING
VALIDATEIOTTHINGEXISTS = VehicleAssociationBehavior.VALIDATEIOTTHINGEXISTS
ROS_2 = VehicleMiddlewareProtocol.ROS_2
CREATED = VehicleState.CREATED
READY = VehicleState.READY
HEALTHY = VehicleState.HEALTHY
SUSPENDED = VehicleState.SUSPENDED
DELETING = VehicleState.DELETING
READY_FOR_CHECKIN = VehicleState.READY_FOR_CHECKIN


# PropertyType submodules (e.g., ec2.instance.NetworkInterface)
from . import campaign
from . import decoder_manifest
from . import signal_catalog
from . import vehicle


@dataclass
class Campaign(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iotfl"""

    resource_type: ClassVar[str] = "AWS::IoTFleetWise::Campaign"
    ACTION = "Action"
    COMPRESSION = "Compression"
    DESCRIPTION = "Description"
    DATA_PARTITIONS = "DataPartitions"
    PRIORITY = "Priority"
    SIGNALS_TO_COLLECT = "SignalsToCollect"
    START_TIME = "StartTime"
    SIGNALS_TO_FETCH = "SignalsToFetch"
    EXPIRY_TIME = "ExpiryTime"
    SPOOLING_MODE = "SpoolingMode"
    DATA_DESTINATION_CONFIGS = "DataDestinationConfigs"
    SIGNAL_CATALOG_ARN = "SignalCatalogArn"
    NAME = "Name"
    POST_TRIGGER_COLLECTION_DURATION = "PostTriggerCollectionDuration"
    DATA_EXTRA_DIMENSIONS = "DataExtraDimensions"
    DIAGNOSTICS_MODE = "DiagnosticsMode"
    TARGET_ARN = "TargetArn"
    COLLECTION_SCHEME = "CollectionScheme"
    TAGS = "Tags"

    _property_mappings: ClassVar[dict[str, str]] = {
        "action": "Action",
        "compression": "Compression",
        "description": "Description",
        "data_partitions": "DataPartitions",
        "priority": "Priority",
        "signals_to_collect": "SignalsToCollect",
        "start_time": "StartTime",
        "signals_to_fetch": "SignalsToFetch",
        "expiry_time": "ExpiryTime",
        "spooling_mode": "SpoolingMode",
        "data_destination_configs": "DataDestinationConfigs",
        "signal_catalog_arn": "SignalCatalogArn",
        "name": "Name",
        "post_trigger_collection_duration": "PostTriggerCollectionDuration",
        "data_extra_dimensions": "DataExtraDimensions",
        "diagnostics_mode": "DiagnosticsMode",
        "target_arn": "TargetArn",
        "collection_scheme": "CollectionScheme",
        "tags": "Tags",
    }

    action: Optional[Union[str, Ref, GetAtt, Sub]] = None
    compression: Optional[Union[str, Ref, GetAtt, Sub]] = None
    description: Optional[Union[str, Ref, GetAtt, Sub]] = None
    data_partitions: Optional[list[campaign.DataPartition]] = None
    priority: Optional[Union[int, Ref, GetAtt, Sub]] = None
    signals_to_collect: Optional[list[campaign.SignalInformation]] = None
    start_time: Optional[Union[str, Ref, GetAtt, Sub]] = None
    signals_to_fetch: Optional[list[campaign.SignalFetchInformation]] = None
    expiry_time: Optional[Union[str, Ref, GetAtt, Sub]] = None
    spooling_mode: Optional[Union[str, Ref, GetAtt, Sub]] = None
    data_destination_configs: Optional[list[campaign.DataDestinationConfig]] = None
    signal_catalog_arn: Optional[Union[str, Ref, GetAtt, Sub]] = None
    name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    post_trigger_collection_duration: Optional[Union[float, Ref, GetAtt, Sub]] = None
    data_extra_dimensions: Optional[Union[list[str], Ref]] = None
    diagnostics_mode: Optional[Union[str, Ref, GetAtt, Sub]] = None
    target_arn: Optional[Union[str, Ref, GetAtt, Sub]] = None
    collection_scheme: Optional[campaign.CollectionScheme] = None
    tags: Optional[list[campaign.Tag]] = None

    @property
    def attr_status(self) -> GetAtt:
        """Get the Status attribute."""
        return self.get_att("Status")

    @property
    def attr_last_modification_time(self) -> GetAtt:
        """Get the LastModificationTime attribute."""
        return self.get_att("LastModificationTime")

    @property
    def attr_creation_time(self) -> GetAtt:
        """Get the CreationTime attribute."""
        return self.get_att("CreationTime")

    @property
    def attr_arn(self) -> GetAtt:
        """Get the Arn attribute."""
        return self.get_att("Arn")



@dataclass
class DecoderManifest(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iotfl"""

    resource_type: ClassVar[str] = "AWS::IoTFleetWise::DecoderManifest"
    SIGNAL_DECODERS = "SignalDecoders"
    STATUS = "Status"
    DESCRIPTION = "Description"
    NETWORK_INTERFACES = "NetworkInterfaces"
    MODEL_MANIFEST_ARN = "ModelManifestArn"
    DEFAULT_FOR_UNMAPPED_SIGNALS = "DefaultForUnmappedSignals"
    TAGS = "Tags"
    NAME = "Name"

    _property_mappings: ClassVar[dict[str, str]] = {
        "signal_decoders": "SignalDecoders",
        "status": "Status",
        "description": "Description",
        "network_interfaces": "NetworkInterfaces",
        "model_manifest_arn": "ModelManifestArn",
        "default_for_unmapped_signals": "DefaultForUnmappedSignals",
        "tags": "Tags",
        "name": "Name",
    }

    signal_decoders: Optional[list[decoder_manifest.SignalDecodersItems]] = None
    status: Optional[Union[str, Ref, GetAtt, Sub]] = None
    description: Optional[Union[str, Ref, GetAtt, Sub]] = None
    network_interfaces: Optional[list[decoder_manifest.NetworkInterfacesItems]] = None
    model_manifest_arn: Optional[Union[str, Ref, GetAtt, Sub]] = None
    default_for_unmapped_signals: Optional[Union[str, Ref, GetAtt, Sub]] = None
    tags: Optional[list[decoder_manifest.Tag]] = None
    name: Optional[Union[str, Ref, GetAtt, Sub]] = None

    @property
    def attr_last_modification_time(self) -> GetAtt:
        """Get the LastModificationTime attribute."""
        return self.get_att("LastModificationTime")

    @property
    def attr_creation_time(self) -> GetAtt:
        """Get the CreationTime attribute."""
        return self.get_att("CreationTime")

    @property
    def attr_arn(self) -> GetAtt:
        """Get the Arn attribute."""
        return self.get_att("Arn")



@dataclass
class Fleet(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iotfl"""

    resource_type: ClassVar[str] = "AWS::IoTFleetWise::Fleet"
    DESCRIPTION = "Description"
    ID = "Id"
    SIGNAL_CATALOG_ARN = "SignalCatalogArn"
    TAGS = "Tags"

    _property_mappings: ClassVar[dict[str, str]] = {
        "description": "Description",
        "id": "Id",
        "signal_catalog_arn": "SignalCatalogArn",
        "tags": "Tags",
    }

    description: Optional[Union[str, Ref, GetAtt, Sub]] = None
    id: Optional[Union[str, Ref, GetAtt, Sub]] = None
    signal_catalog_arn: Optional[Union[str, Ref, GetAtt, Sub]] = None
    tags: Optional[list[Tag]] = None

    @property
    def attr_last_modification_time(self) -> GetAtt:
        """Get the LastModificationTime attribute."""
        return self.get_att("LastModificationTime")

    @property
    def attr_creation_time(self) -> GetAtt:
        """Get the CreationTime attribute."""
        return self.get_att("CreationTime")

    @property
    def attr_arn(self) -> GetAtt:
        """Get the Arn attribute."""
        return self.get_att("Arn")



@dataclass
class ModelManifest(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iotfl"""

    resource_type: ClassVar[str] = "AWS::IoTFleetWise::ModelManifest"
    STATUS = "Status"
    DESCRIPTION = "Description"
    SIGNAL_CATALOG_ARN = "SignalCatalogArn"
    NODES = "Nodes"
    TAGS = "Tags"
    NAME = "Name"

    _property_mappings: ClassVar[dict[str, str]] = {
        "status": "Status",
        "description": "Description",
        "signal_catalog_arn": "SignalCatalogArn",
        "nodes": "Nodes",
        "tags": "Tags",
        "name": "Name",
    }

    status: Optional[Union[str, Ref, GetAtt, Sub]] = None
    description: Optional[Union[str, Ref, GetAtt, Sub]] = None
    signal_catalog_arn: Optional[Union[str, Ref, GetAtt, Sub]] = None
    nodes: Optional[Union[list[str], Ref]] = None
    tags: Optional[list[Tag]] = None
    name: Optional[Union[str, Ref, GetAtt, Sub]] = None

    @property
    def attr_last_modification_time(self) -> GetAtt:
        """Get the LastModificationTime attribute."""
        return self.get_att("LastModificationTime")

    @property
    def attr_creation_time(self) -> GetAtt:
        """Get the CreationTime attribute."""
        return self.get_att("CreationTime")

    @property
    def attr_arn(self) -> GetAtt:
        """Get the Arn attribute."""
        return self.get_att("Arn")



@dataclass
class SignalCatalog(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iotfl"""

    resource_type: ClassVar[str] = "AWS::IoTFleetWise::SignalCatalog"
    DESCRIPTION = "Description"
    NODE_COUNTS = "NodeCounts"
    NODES = "Nodes"
    TAGS = "Tags"
    NAME = "Name"

    _property_mappings: ClassVar[dict[str, str]] = {
        "description": "Description",
        "node_counts": "NodeCounts",
        "nodes": "Nodes",
        "tags": "Tags",
        "name": "Name",
    }

    description: Optional[Union[str, Ref, GetAtt, Sub]] = None
    node_counts: Optional[signal_catalog.NodeCounts] = None
    nodes: Optional[list[signal_catalog.Node]] = None
    tags: Optional[list[signal_catalog.Tag]] = None
    name: Optional[Union[str, Ref, GetAtt, Sub]] = None

    @property
    def attr_last_modification_time(self) -> GetAtt:
        """Get the LastModificationTime attribute."""
        return self.get_att("LastModificationTime")

    @property
    def attr_node_counts__total_nodes(self) -> GetAtt:
        """Get the NodeCounts.TotalNodes attribute."""
        return self.get_att("NodeCounts.TotalNodes")

    @property
    def attr_node_counts__total_sensors(self) -> GetAtt:
        """Get the NodeCounts.TotalSensors attribute."""
        return self.get_att("NodeCounts.TotalSensors")

    @property
    def attr_node_counts__total_attributes(self) -> GetAtt:
        """Get the NodeCounts.TotalAttributes attribute."""
        return self.get_att("NodeCounts.TotalAttributes")

    @property
    def attr_node_counts__total_branches(self) -> GetAtt:
        """Get the NodeCounts.TotalBranches attribute."""
        return self.get_att("NodeCounts.TotalBranches")

    @property
    def attr_node_counts__total_actuators(self) -> GetAtt:
        """Get the NodeCounts.TotalActuators attribute."""
        return self.get_att("NodeCounts.TotalActuators")

    @property
    def attr_creation_time(self) -> GetAtt:
        """Get the CreationTime attribute."""
        return self.get_att("CreationTime")

    @property
    def attr_arn(self) -> GetAtt:
        """Get the Arn attribute."""
        return self.get_att("Arn")



@dataclass
class StateTemplate(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iotfl"""

    resource_type: ClassVar[str] = "AWS::IoTFleetWise::StateTemplate"
    STATE_TEMPLATE_PROPERTIES = "StateTemplateProperties"
    DESCRIPTION = "Description"
    DATA_EXTRA_DIMENSIONS = "DataExtraDimensions"
    SIGNAL_CATALOG_ARN = "SignalCatalogArn"
    METADATA_EXTRA_DIMENSIONS = "MetadataExtraDimensions"
    TAGS = "Tags"
    NAME = "Name"

    _property_mappings: ClassVar[dict[str, str]] = {
        "state_template_properties": "StateTemplateProperties",
        "description": "Description",
        "data_extra_dimensions": "DataExtraDimensions",
        "signal_catalog_arn": "SignalCatalogArn",
        "metadata_extra_dimensions": "MetadataExtraDimensions",
        "tags": "Tags",
        "name": "Name",
    }

    state_template_properties: Optional[Union[list[str], Ref]] = None
    description: Optional[Union[str, Ref, GetAtt, Sub]] = None
    data_extra_dimensions: Optional[Union[list[str], Ref]] = None
    signal_catalog_arn: Optional[Union[str, Ref, GetAtt, Sub]] = None
    metadata_extra_dimensions: Optional[Union[list[str], Ref]] = None
    tags: Optional[list[Tag]] = None
    name: Optional[Union[str, Ref, GetAtt, Sub]] = None

    @property
    def attr_last_modification_time(self) -> GetAtt:
        """Get the LastModificationTime attribute."""
        return self.get_att("LastModificationTime")

    @property
    def attr_creation_time(self) -> GetAtt:
        """Get the CreationTime attribute."""
        return self.get_att("CreationTime")

    @property
    def attr_id(self) -> GetAtt:
        """Get the Id attribute."""
        return self.get_att("Id")

    @property
    def attr_arn(self) -> GetAtt:
        """Get the Arn attribute."""
        return self.get_att("Arn")



@dataclass
class Vehicle(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iotfl"""

    resource_type: ClassVar[str] = "AWS::IoTFleetWise::Vehicle"
    ASSOCIATION_BEHAVIOR = "AssociationBehavior"
    ATTRIBUTES = "Attributes"
    DECODER_MANIFEST_ARN = "DecoderManifestArn"
    STATE_TEMPLATES = "StateTemplates"
    MODEL_MANIFEST_ARN = "ModelManifestArn"
    TAGS = "Tags"
    NAME = "Name"

    _property_mappings: ClassVar[dict[str, str]] = {
        "association_behavior": "AssociationBehavior",
        "attributes": "Attributes",
        "decoder_manifest_arn": "DecoderManifestArn",
        "state_templates": "StateTemplates",
        "model_manifest_arn": "ModelManifestArn",
        "tags": "Tags",
        "name": "Name",
    }

    association_behavior: Optional[Union[str, Ref, GetAtt, Sub]] = None
    attributes: Optional[dict[str, str]] = None
    decoder_manifest_arn: Optional[Union[str, Ref, GetAtt, Sub]] = None
    state_templates: Optional[list[vehicle.StateTemplateAssociation]] = None
    model_manifest_arn: Optional[Union[str, Ref, GetAtt, Sub]] = None
    tags: Optional[list[vehicle.Tag]] = None
    name: Optional[Union[str, Ref, GetAtt, Sub]] = None

    @property
    def attr_last_modification_time(self) -> GetAtt:
        """Get the LastModificationTime attribute."""
        return self.get_att("LastModificationTime")

    @property
    def attr_creation_time(self) -> GetAtt:
        """Get the CreationTime attribute."""
        return self.get_att("CreationTime")

    @property
    def attr_arn(self) -> GetAtt:
        """Get the Arn attribute."""
        return self.get_att("Arn")


