"""Generated by cfn-dataclasses-import."""

from cloudformation_dataclasses.core import (
    Parameter,
    PolicyDocument,
    PolicyStatement,
    STRING,
    Template,
    cloudformation_dataclass,
    get_att,
    ref,
)
from cloudformation_dataclasses.core.resource_loader import setup_resources
from cloudformation_dataclasses.aws import iam, lambda_, s3
from cloudformation_dataclasses.aws.s3 import ServerSideEncryption
from cloudformation_dataclasses.intrinsics import AWS_ACCOUNT_ID, Sub

from .params import *  # noqa: F403, F401

# Auto-discover and import resource files in topological order
setup_resources(__file__, __name__, globals())

__all__ = [
    "AWS_ACCOUNT_ID",
    "LambdaIAMRole",
    "LambdaInvokePermission",
    "NotificationBucket",
    "Parameter",
    "PolicyDocument",
    "PolicyStatement",
    "S3BucketNotification",
    "S3TriggerLambdaFunction",
    "STRING",
    "ServerSideEncryption",
    "Sub",
    "Template",
    "cloudformation_dataclass",
    "get_att",
    "iam",
    "lambda_",
    "ref",
    "s3",
]
