"""This CloudFormation sample template DMSAuroraToS3FullLoadAndOngoingReplication creates an Aurora RDS instance and DMS instance in a VPC, and an S3 bucket. The Aurora RDS instance is configured as t...

Generated by cfn-dataclasses-import."""

from cloudformation_dataclasses.core import (
    Output,
    Parameter,
    PolicyDocument,
    PolicyStatement,
    STRING,
    Template,
    cloudformation_dataclass,
    get_att,
    ref,
)
from cloudformation_dataclasses.core.template import Condition as TemplateCondition
from cloudformation_dataclasses.core.resource_loader import setup_resources
from cloudformation_dataclasses.aws import (
    dms,
    ec2,
    iam,
    rds,
    s3,
)
from cloudformation_dataclasses.aws.dms import ReplicationInstance, ReplicationSubnetGroup, ReplicationTask
from cloudformation_dataclasses.aws.ec2 import Subnet, SubnetRouteTableAssociation, VPCGatewayAttachment
from cloudformation_dataclasses.aws.s3 import ServerSideEncryption
from cloudformation_dataclasses.intrinsics import (
    AWS_REGION,
    AWS_STACK_ID,
    AWS_STACK_NAME,
    Equals,
    GetAZs,
    Select,
    Sub,
)

from .params import *  # noqa: F403, F401

# Auto-discover and import resource files in topological order
setup_resources(__file__, __name__, globals())

# Import outputs after resources (outputs reference resource classes)
from .outputs import *  # noqa: F403, F401

__all__ = [
    "AWS_REGION",
    "AWS_STACK_ID",
    "AWS_STACK_NAME",
    "AttachGateway",
    "AuroraCluster",
    "AuroraDB",
    "AuroraDBSubnetGroup",
    "AuroraEndpointOutput",
    "AuroraSecurityGroup",
    "AuroraSourceEndpoint",
    "ClientIP",
    "DBSubnet1",
    "DBSubnet2",
    "DMSCloudwatchRole",
    "DMSReplicationInstance",
    "DMSReplicationSubnetGroup",
    "DMSReplicationTask",
    "DMSSecurityGroup",
    "DMSVpcRole",
    "Equals",
    "ExistsDMSCloudwatchRole",
    "ExistsDMSVPCRole",
    "GetAZs",
    "InternetGateway",
    "NotExistsDMSCloudwatchRoleCondition",
    "NotExistsDMSVPCRoleCondition",
    "Output",
    "Parameter",
    "PolicyDocument",
    "PolicyStatement",
    "RegionNameOutput",
    "ReplicationInstance",
    "ReplicationSubnetGroup",
    "ReplicationTask",
    "Route",
    "RouteTable",
    "S3Bucket",
    "S3BucketNameOutput",
    "S3TargetDMSRole",
    "S3TargetEndpoint",
    "STRING",
    "Select",
    "ServerSideEncryption",
    "SnapshotIdentifier",
    "StackNameOutput",
    "Sub",
    "Subnet",
    "SubnetRouteTableAssociation",
    "SubnetRouteTableAssociation1",
    "Template",
    "VPC",
    "VPCGatewayAttachment",
    "cloudformation_dataclass",
    "dms",
    "ec2",
    "get_att",
    "iam",
    "rds",
    "ref",
    "s3",
]
