"""AWS CloudFormation Sample Template RDS_PIOPS: Sample template showing how to create an Amazon RDS Database Instance with provisioned IOPs.**WARNING** This template creates an Amazon Relational Data...

Generated by cfn-dataclasses-import."""

from cloudformation_dataclasses.core import (
    Parameter,
    STRING,
    Template,
    cloudformation_dataclass,
    get_att,
    ref,
)
from cloudformation_dataclasses.core.resource_loader import setup_resources
from cloudformation_dataclasses.aws import rds, secretsmanager
from cloudformation_dataclasses.intrinsics import Sub

from .params import *  # noqa: F403, F401

# Auto-discover and import resource files in topological order
setup_resources(__file__, __name__, globals())

__all__ = [
    "DBCredential",
    "DBUser",
    "Parameter",
    "STRING",
    "Sub",
    "Template",
    "cloudformation_dataclass",
    "get_att",
    "myDB",
    "rds",
    "ref",
    "secretsmanager",
]
