"""StackSet execution role for target accounts

Generated by cfn-dataclasses-import."""

from cloudformation_dataclasses.core import (
    Output,
    Parameter,
    PolicyDocument,
    PolicyStatement,
    STRING,
    Template,
    cloudformation_dataclass,
    get_att,
    ref,
)
from cloudformation_dataclasses.core.resource_loader import setup_resources
from cloudformation_dataclasses.aws import iam
from cloudformation_dataclasses.intrinsics import Sub

from .params import *  # noqa: F403, F401

# Auto-discover and import resource files in topological order
setup_resources(__file__, __name__, globals())

# Import outputs after resources (outputs reference resource classes)
from .outputs import *  # noqa: F403, F401

__all__ = [
    "AWSCloudFormationStackSetExecutionRole",
    "AdministrationAccountId",
    "ExecutionRoleArnOutput",
    "Output",
    "Parameter",
    "PolicyDocument",
    "PolicyStatement",
    "STRING",
    "Sub",
    "Template",
    "cloudformation_dataclass",
    "get_att",
    "iam",
    "ref",
]
