"""CloudFormation intrinsic functions and pseudo-parameters."""

from cloudformation_dataclasses.intrinsics.functions import (
    And,
    Base64,
    Cidr,
    Condition,
    Equals,
    FindInMap,
    GetAtt,
    GetAZs,
    If,
    ImportValue,
    IntrinsicFunction,
    Join,
    Not,
    Or,
    Ref,
    Select,
    Split,
    Sub,
    Transform,
)
from cloudformation_dataclasses.intrinsics.pseudo import (
    AWS_ACCOUNT_ID,
    AWS_NO_VALUE,
    AWS_NOTIFICATION_ARNS,
    AWS_PARTITION,
    AWS_REGION,
    AWS_STACK_ID,
    AWS_STACK_NAME,
    AWS_URL_SUFFIX,
)

__all__ = [
    # Intrinsic functions
    "And",
    "Base64",
    "Cidr",
    "Condition",
    "Equals",
    "FindInMap",
    "GetAtt",
    "GetAZs",
    "If",
    "ImportValue",
    "IntrinsicFunction",
    "Join",
    "Not",
    "Or",
    "Ref",
    "Select",
    "Split",
    "Sub",
    "Transform",
    # Pseudo-parameters
    "AWS_ACCOUNT_ID",
    "AWS_NO_VALUE",
    "AWS_NOTIFICATION_ARNS",
    "AWS_PARTITION",
    "AWS_REGION",
    "AWS_STACK_ID",
    "AWS_STACK_NAME",
    "AWS_URL_SUFFIX",
]
